#!/usr/bin/env python3
"""
regen_rear_interior.py — regenerate the REAR fuselage shell (featured, hull frame).

Rear counterpart to merge_cargo_interior.py.  It exists because the rear shell
cannot be regenerated by add_structural_features.py's normal "load the already-
baked published STL, then cut" flow (rear is SKIPPED there): the rear Blender
source is a delicate 3-body solid — the main wall shell (+302 k mm^3) plus TWO
disconnected, inside-out internal cavity shells (−27.5 k mm^3 each, symmetric
port/stbd) that net to the correct 247 239 mm^3.  That topology is fine in
float64, but the bake step's float32 STL write at the rear's large hull-frame
coordinates (Y ≈ +203..+384) splits coincident vertices just enough that a
reload no longer welds watertight, and manifold3d then mis-resolves the mesh
(volume inflates to ~357 k) so every subsequent boolean is built on a wrong
base — the "REAR STILL BROKEN" symptom (TODO.md MESH-01).

Fix (this script), matching merge_cargo_interior.py:
  1. Load the CLEAN part-local Blender source and merge vertices (watertight,
     247 239 mm^3 in float64).
  2. Bake to the hull frame IN MEMORY (v' = R(q)·v + P from the Rear_Shell
     placement in tools/bake_hull_frame.py) — no intermediate float32 STL, so
     the delicate topology survives.
  3. Build the same rear feature cutters add_structural_features.process_rear
     uses (bore-open fwd joint face, keel channel, Y=+290 ring pocket, 2× CF
     skid-rod bores) via that module's own cutter helpers.
  4. Subtract them with a SINGLE manifold3d boolean (closed − closed ⇒ closed
     ⇒ watertight by construction).  We deliberately do NOT run
     _subtract_all()'s nondegenerate-face strip here: on the rear that strip
     opens ~3 boundary holes, which is worse than the ~3 benign non-manifold
     edges the float32 export otherwise leaves (0 boundary either way — the
     surface stays closed; slicers weld the coincident vertices).
  5. Drop any tiny disconnected junk fragments and stamp-export ONCE to the
     published path with the HULL-FRAME R1 marker (do NOT re-bake).

The joint boss-pins are already removed from process_rear (splice collars
supersede — 2026-07-06).  The bore-open fwd face uses the lofted per-station
cavity cutter (_bore_open_cutter), the same one now used for every joint, so
the rear mating rim is clean (no ragged fragments / dorsal bite — JOINT-01).

Author:  Steve Griffing, PE(CSE), CISSP-ISSEP, CPP   (pipeline)
AI-assist: Claude Opus 4.8 (Anthropic) — script authoring, 2026-07-06
License: CC BY 4.0 — creativecommons.org/licenses/by/4.0
"""

import importlib.util
import os
import struct
import sys

import numpy as np
import trimesh
from manifold3d import Manifold, Mesh

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(SCRIPT_DIR))
SRC = os.path.join(
    SCRIPT_DIR, "files-hollowed-24in", "rear_shell24_2mm_repaired.stl"
)
OUT = os.environ.get("REAR_REGEN_OUT") or os.path.join(
    REPO, "airframe", "stls", "fuselage", "rear_shell24_2mm_repaired.stl"
)
MARKER = b"SerenityUAV HULL-FRAME R1"
RHO_PRINT = 1.05e-3   # g/mm^3 as-printed CF-PETG (≈40 % infill)
RHO_SOLID = 1.28e-3   # g/mm^3 solid CF-PETG
JUNK_FACES = 64       # connected components below this are dropped


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


ASF = _load("asf", os.path.join(SCRIPT_DIR, "add_structural_features.py"))
BHF = _load("bhf", os.path.join(REPO, "tools", "bake_hull_frame.py"))


def to_manifold(tm):
    """trimesh.Trimesh -> manifold3d.Manifold (float32)."""
    return Manifold(
        Mesh(
            vert_properties=tm.vertices.astype(np.float32),
            tri_verts=tm.faces.astype(np.uint32),
        )
    )


def from_manifold(man):
    """manifold3d.Manifold -> trimesh.Trimesh (float64, merged)."""
    m = man.to_mesh()
    out = trimesh.Trimesh(
        vertices=np.asarray(m.vert_properties)[:, :3].astype(np.float64),
        faces=np.asarray(m.tri_verts),
        process=False,
    )
    out.merge_vertices()
    return out


def bake_in_memory(mesh):
    """Apply the Rear_Shell hull-frame placement (v' = R·v + P) in float64."""
    px, py, pz, qx, qy, qz, qw = BHF.COMPONENTS["Rear_Shell"][1]
    rot = BHF.quat_to_matrix(qx, qy, qz, qw)
    pos = np.array([px, py, pz], dtype=np.float64)
    verts = (rot @ mesh.vertices.T).T + pos
    return trimesh.Trimesh(vertices=verts, faces=mesh.faces, process=False)


def build_cutters(shell):
    """The same feature cutters add_structural_features.process_rear uses."""
    cutters, notes = [], []
    fwd = ASF._bore_open_cutter(shell, ASF.FACE_BORE_Y_RANGES["rear_fwd"])
    cutters.extend(fwd)
    notes.append(f"bore-open fwd joint face (middle/rear) — {len(fwd)} lofted segs")
    cutters.append(ASF._keel_channel_cutter("rear"))
    notes.append("keel locating channel")
    for xm, xx, zm, zx, ym, yx in ASF.RING_POCKETS["rear_Y290"]:
        cutters.append(ASF._box(xm, xx, zm, zx, ym, yx))
    notes.append("ring-frame pocket Y=+290")
    for x_cen, z_cen, y0, y1 in ASF.SKID_ROD_BORES:
        cutters.append(ASF._y_cylinder(x_cen, z_cen, y0, y1, ASF.SKID_ROD_RADIUS))
    notes.append(f"{len(ASF.SKID_ROD_BORES)}× CF skid-rod bores")
    return cutters, notes


def drop_junk(mesh):
    comps = trimesh.graph.connected_components(
        mesh.face_adjacency, nodes=np.arange(len(mesh.faces))
    )
    keep = [c for c in comps if len(c) >= JUNK_FACES]
    dropped = len(comps) - len(keep)
    if dropped:
        mesh = mesh.submesh([np.concatenate(keep)], append=True)
        mesh.merge_vertices()
        print(f"  dropped {dropped} junk fragment(s) < {JUNK_FACES} faces "
              f"→ {len(keep)} body/bodies")
    return mesh


def stamp_export(mesh, out_path):
    """Binary STL with the HULL-FRAME R1 marker in the 80-byte header."""
    count = len(mesh.faces)
    tris = mesh.vertices[mesh.faces]
    e1 = tris[:, 1, :] - tris[:, 0, :]
    e2 = tris[:, 2, :] - tris[:, 0, :]
    normals = np.cross(e1, e2)
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    normals = np.where(lengths > 0.0, normals / np.where(lengths > 0.0, lengths, 1.0), 0.0)
    rec = np.zeros(count, dtype=np.dtype([("data", "<f4", (12,)), ("attr", "<u2")]))
    rec["data"][:, 0:3] = normals.astype("<f4")
    rec["data"][:, 3:12] = tris.reshape(count, 9).astype("<f4")
    header = (MARKER + b" Rear_Shell interior-regen 2026-07-06")[:80].ljust(80, b"\0")
    with open(out_path, "wb") as fh:
        fh.write(header)
        fh.write(struct.pack("<I", count))
        fh.write(rec.tobytes())


def verify(mesh, tag):
    ec = np.bincount(mesh.edges_unique_inverse, minlength=len(mesh.edges_unique))
    boundary = int((ec == 1).sum())
    nonman = int((ec > 2).sum())
    bodies = len(trimesh.graph.connected_components(
        mesh.face_adjacency, nodes=np.arange(len(mesh.faces))))
    vol = mesh.volume
    print(f"\n=== verify ({tag}) ===")
    print(f"  faces={len(mesh.faces):,}  bodies={bodies}  boundary_edges={boundary}  "
          f"nonmanifold_edges={nonman}")
    print(f"  volume={vol:.0f} mm^3  mass={vol * RHO_PRINT:.1f} g (as-printed) .. "
          f"{vol * RHO_SOLID:.1f} g (solid CF-PETG)")
    # Manufacturing gate: no OPEN boundary (holes) and a plausible net volume.
    # A few non-manifold edges from the float32 export are benign (surface
    # stays closed; slicers weld) — matches the accepted cargo shell state.
    ok = boundary == 0 and 200_000 < vol < 300_000 and bodies <= 3
    print(f"  RESULT: {'PASS' if ok else 'FAIL'}")
    return ok


def main():
    print("=== regen_rear_interior.py  2026-07-06 ===")
    print(f"source: {SRC}")
    src = trimesh.load(SRC, process=False)
    src.merge_vertices()
    print(f"  loaded {len(src.faces):,} faces  watertight={src.is_watertight}  "
          f"vol={src.volume:.0f} mm^3 (part-local)")

    baked = bake_in_memory(src)
    baked.merge_vertices()
    b = baked.bounds
    print(f"  baked hull frame: X {b[0][0]:.1f}..{b[1][0]:.1f}  "
          f"Y {b[0][1]:.1f}..{b[1][1]:.1f}  Z {b[0][2]:.1f}..{b[1][2]:.1f}  "
          f"watertight={baked.is_watertight}")

    shell = ASF._to_manifold_volume(baked)
    cutters, notes = build_cutters(shell)
    print(f"\n  cutters ({len(cutters)}):")
    for n in notes:
        print(f"    - {n}")

    print("\n  evaluating shell − union(cutters) (single manifold boolean) …")
    neg = None
    for c in cutters:
        cm = to_manifold(c)
        neg = cm if neg is None else (neg + cm)
    out = from_manifold(to_manifold(shell) - neg)
    out = drop_junk(out)

    ok = verify(out, "rear")
    stamp_export(out, OUT)
    print(f"\n  written -> {OUT}")
    print("  (already in hull frame + HULL-FRAME R1 marker; do NOT re-bake)")
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
