// ===========================================================================
// HULL-FRAME COORDINATE STANDARD - Rev R1 (2026-06-11).  See AGENTS.md.
//   Hull frame (canonical for ALL design artifacts): X = +port (left),
//   Y = +aft (back), Z = +dorsal (up); origin = SerenityAssembly.FCStd
//   world origin.
//   This file: MODELLED DIRECTLY IN HULL FRAME.  The exported STL imports
//   into serenity_assembly.py at identity placement.  Print orientation is
//   set in the slicer (see PRINT ORIENTATION), not here.
// ===========================================================================
// ============================================================
// battery_cradle.scad -- Rev T5 (2026-09-15)
// Roof-hung inverted-U cradle for the 6S 4000 mAh flight battery, cargo
// section roof band.  SUPERSEDES battery_tray.scad (Rev R1, keel-rail tray,
// 140 g measured -- MA-6) for the Rev T5 cargo layout.
//
// WHY A CRADLE AND NOT VELCRO / STRAPS ALONE (docs/BATTERY_MOUNT.md Rev T5 SS3):
//   * Hook-and-loop alone locates the pack in nothing but friction; a 750 g
//     pack at the 2.5 g hard-landing case (18.4 N) on a 142 x 50 mm face of
//     industrial hook-and-loop (shear ~ 20 kPa dry, far less with LiPo skin
//     grease) is marginal, and it loses everything when the skin is cold or
//     the loop side has picked up lint.  It also gives no vibration control.
//   * A cradle gives POSITIVE location in X, Y, roll and yaw and in +Z
//     (the ceiling), with the two silicone cam straps carrying only the
//     -Z (hanging) load.  Fore/aft station is therefore repeatable to the
//     print tolerance, which is what the CG ledger (A0) needs.
//   * The 3 mm Shore A 20-30 silicone-foam pad between the pack and the
//     ceiling is the vibration isolator: k = E.A/t ~ 0.4 MPa x 7,100 mm^2 /
//     3 mm ~ 950 N/mm (E ASSUMED, closed-cell silicone foam class value)
//     gives f_n ~ 180 Hz for 0.75 kg, i.e. transmissibility ~ 0.17 at the
//     ~470 Hz EDF shaft rate (bom_revS.csv FAR-CAGE-AV note) -- ~83 %
//     isolation, and far more at the 12x blade-pass.  Strap preload
//     compresses the pad ~1 mm, which stiffens it; keep the preload light.
//   * Mass: this part is ~34 cm^3 solid (~36 g as printed) against the 140 g
//     keel-rail tray it replaces (MA-6) -- a 100 g saving at the CG station.
//
// WHY INVERTED (hung from the roof, open below):
//   The roof band above the battery is the winch reservation and the hull
//   skin; the payload bay below it is open whenever the clamshell doors are
//   open.  Field exchange is therefore FROM BELOW: release the two cam
//   buckles, lower the pack out through the bay, push the fresh pack up
//   against the ceiling pad until the fore/aft stops seat, re-strap.  No
//   roof access, no winch removal, no tools (docs/BATTERY_MOUNT.md SS6).
//
// LOADS (statics-and-dynamics FBD: pack isolated, ceiling reaction +Z,
//   strap tension -Z, end stops +/-Y, rails +/-X):
//   * hanging (1 g): 7.36 N (1.65 lbf) shared by 2 straps -> 3.7 N each.
//   * hard landing 2.5 g (docs/structural_analysis.md SS6.2 case): 18.4 N
//     (4.14 lbf) -> 9.2 N/strap; strap rated 50 N (11.2 lbf, BATT-STRAP-CAM)
//     -> FOS 5.4 on the strap; ISO 4-strand cam buckle limit governs.
//   * 5 g crash (docs/BATTERY_MOUNT.md SS3.2 legacy case): 36.8 N -> two
//     straps 100 N -> FOS 2.7 (unchanged from Rev R; retention, not flight).
//   * ceiling plate as a 142 mm beam on 4 hangers at Y -50 / +80 (span 130):
//     w = 18.4 N over 142 mm -> M_max = w.L/8 ~ 0.30 N.m; plate 50 x 2.4 mm
//     -> Z = b.t^2/6 = 48 mm^3 -> sigma = 6.2 MPa vs 54 MPa PETG flexural
//     (REF-MAT-002) -> FOS 8.7 on plain PETG, higher on CF-PETG.  The two
//     side rails (30 mm deep) carry the rest; the plate number is the
//     conservative floor.
//   * hanger screws: 4 x M3 into heat-set inserts (~400 N pull-out, boss
//     note in cargo_sect_shell24.scad) against 18.4 N/4 -> FOS 87.
//
// FASTENERS: 4 x M3 x 8 SHCS up through the ceiling plate into the four
//   roof hanger bosses (merge_cargo_interior.py CRADLE_* positives), fitted
//   BEFORE the battery goes in (the pack covers the screw heads).
//
// PRINT ORIENTATION: ceiling plate DOWN on the bed (hull Z inverted); the
//   rails and end walls stand up -- no supports.  4 perimeters, 40 % gyroid,
//   CF-PETG (20 %) per FIL-CF-PETG.  The strap slots print as bridges
//   (4 mm) -- acceptable.
//
// Single-source numbers: cargo_layout_t5_params.scad (GENERATED by
//   tools/cargo_layout_fit.py --write-scad).
//
// Author: Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// AI note: Written by Claude (model: Claude Opus 5, Anthropic) under the
//   author's direction, 2026-09-15, per AGENTS.md SS3 AI attribution.
// License: CC BY 4.0 -- creativecommons.org/licenses/by/4.0
// ============================================================

include <cargo_layout_t5_params.scad>

$fn = 48;
EPS = 0.01;

RAIL_H        = 30.0;                 // side rail depth below the ceiling
END_H_FWD     = BATT_H + CRADLE_T;    // forward stop: full height
END_H_AFT     = 28.0;                 // aft wall: leaves the lead exit open below
LEAD_SLOT     = [14.0, 10.0];         // XT60 + balance lead exit, aft wall (X x Z)
STRAP_W       = 16.0;                 // BATT-STRAP-CAM silicone cam strap
STRAP_SLOT    = [4.0, STRAP_W + 4.0]; // through-slot in the ceiling (Y x X)
STRAP_Y       = [BATT_Y0 + BATT_L / 3, BATT_Y0 + 2 * BATT_L / 3];   // 1/3, 2/3
M3_CLR        = 3.4;
HANGER_PAD    = 10.0;                 // matches the shell hanger boss section
WINDOW        = [24.0, 30.0];         // rail lightening windows (Y x Z)
PAD_T         = 3.0;                  // silicone foam pad (BOM FOAM-SIL-3MM), bonded to the ceiling

X0 = BATT_X0 - CRADLE_T;  X1 = BATT_X1 + CRADLE_T;
Y0 = BATT_Y0 - CRADLE_T;  Y1 = BATT_Y1 + CRADLE_T;
ZC = BATT_Z1;             // ceiling underside = battery top (pad compresses into the 0 mm nominal)

module ceiling() {
    difference() {
        translate([X0, Y0, ZC]) cube([X1 - X0, Y1 - Y0, CRADLE_T]);
        // dorsal-notch relief: no ceiling over Y -20..+2 (roof dips to Z ~131)
        translate([X0 - 1, CRADLE_RELIEF_Y[0], CRADLE_RELIEF_Z])
            cube([X1 - X0 + 2, CRADLE_RELIEF_Y[1] - CRADLE_RELIEF_Y[0], CRADLE_T + 2]);
        // 4 x M3 hanger holes
        for (dx = [-CRADLE_BOSS_DX, CRADLE_BOSS_DX], y = [CRADLE_FWD_BOSS_Y, CRADLE_AFT_BOSS_Y])
            translate([CRADLE_XC + dx, y, ZC - 1]) cylinder(d = M3_CLR, h = CRADLE_T + 2);
        // strap slots: 2 straps x 2 slots, at the ceiling edges
        for (y = STRAP_Y, sx = [-1, 1])
            translate([CRADLE_XC + sx * (BATT_W / 2 - STRAP_SLOT[1] / 2 - 1.0) - STRAP_SLOT[1] / 2,
                       y - STRAP_SLOT[0] / 2, ZC - 1])
                cube([STRAP_SLOT[1], STRAP_SLOT[0], CRADLE_T + 2]);
    }
}

module rails() {
    for (sx = [0, 1]) {
        x = sx ? BATT_X1 : X0;
        difference() {
            translate([x, Y0, ZC - RAIL_H]) cube([CRADLE_T, Y1 - Y0, RAIL_H + CRADLE_T]);
            // step the rail top down through the notch relief
            translate([x - 1, CRADLE_RELIEF_Y[0], CRADLE_RELIEF_Z])
                cube([CRADLE_T + 2, CRADLE_RELIEF_Y[1] - CRADLE_RELIEF_Y[0], CRADLE_T + 3]);
            // lightening windows between the strap stations
            for (y = [Y0 + 14, STRAP_Y[0] + 12, STRAP_Y[1] + 12])
                translate([x - 1, y, ZC - RAIL_H + 4]) cube([CRADLE_T + 2, WINDOW[0], WINDOW[1] - 8]);
            // strap pass-through notches at the rail bottom edge
            for (y = STRAP_Y)
                translate([x - 1, y - STRAP_W / 2 - 1, ZC - RAIL_H - 1]) cube([CRADLE_T + 2, STRAP_W + 2, 4]);
        }
    }
}

module end_walls() {
    // forward positive stop (full height)
    translate([X0, Y0, ZC - END_H_FWD]) cube([X1 - X0, CRADLE_T, END_H_FWD + CRADLE_T]);
    // aft wall with the lead exit slot, plus 2 x 4 M3 holes for the saddles
    // of the two aft avionics nodes (N2 FC2 port / N4 FC3 stbd, Rev T5c --
    // tools/cargo_layout_fit.py N_AFT_*): the nodes sit 3 mm behind this
    // wall at Y 89.5..111.5, Z 87..124, each overlapping it by ~26 mm in X.
    difference() {
        translate([X0, BATT_Y1, ZC - END_H_AFT]) cube([X1 - X0, CRADLE_T, END_H_AFT + CRADLE_T]);
        translate([CRADLE_XC - LEAD_SLOT[0] / 2, BATT_Y1 - 1, ZC - END_H_AFT - 1])
            cube([LEAD_SLOT[0], CRADLE_T + 2, LEAD_SLOT[1] + 1]);
        for (x = [CRADLE_XC + 20, CRADLE_XC + 8, CRADLE_XC - 8, CRADLE_XC - 20], z = [ZC - 20, ZC - 6])
            translate([x, BATT_Y1 - 1, z]) rotate([-90, 0, 0]) cylinder(d = M3_CLR, h = CRADLE_T + 2);
    }
}

module hanger_pads() {
    // thickened pads around the 4 hanger holes (bearing area for the M3 head)
    for (dx = [-CRADLE_BOSS_DX, CRADLE_BOSS_DX], y = [CRADLE_FWD_BOSS_Y, CRADLE_AFT_BOSS_Y])
        difference() {
            translate([CRADLE_XC + dx - HANGER_PAD / 2, y - HANGER_PAD / 2, ZC - 2.0])
                cube([HANGER_PAD, HANGER_PAD, 2.0 + EPS]);
            translate([CRADLE_XC + dx, y, ZC - 3]) cylinder(d = M3_CLR, h = 6);
        }
}

union() {
    ceiling();
    rails();
    end_walls();
    hanger_pads();
}
