// cargo_door_hinge_params.scad -- GENERATED by generate_cargo_doors.py.
// Do not edit: change the shell/generator and re-run generate_cargo_doors.py
// to regenerate.  Hull frame, mm.  CARGO-HINGE-SYNC single source.
HINGE_X_PORT = -117.5322;
HINGE_Z_PORT = 3.0029;
HINGE_X_STBD = -222.6785;
HINGE_Z_STBD = 3.4898;
HINGE_BAY_Y_FWD = 2.0000;
HINGE_BAY_Y_AFT = 108.0000;
