// ===========================================================================
// HULL-FRAME COORDINATE STANDARD - Rev R1 (2026-06-11).  See AGENTS.md.
//   Hull frame (canonical for ALL design artifacts): X = +port (left),
//   Y = +aft (back), Z = +dorsal (up); origin = SerenityAssembly.FCStd
//   world origin.  MODELLED DIRECTLY IN HULL FRAME; the exported STL imports
//   into serenity_assembly.py at identity placement.
// ===========================================================================
// ============================================================
// gateway_door_tray.scad -- Rev T5f (2026-09-21)
// Card-edge tray for the cargo-door servo GATEWAY (GW-CARGO-DOOR: one
// SKIPPER-CAN-PERIPH-GW-PCB built at N_STACKS=1, 49.0 x 25.5 x 1.6 mm, no
// mounting holes -- see docs/CARGO_DOOR_GATEWAY_SPEC.md and
// avionics/kicad/CAN-PERIPH-GW-1/CAN-PERIPH-GW-1.md "Deployment" 4).
// Every station is from cargo_layout_t5_params.scad (GENERATED by
// tools/cargo_layout_fit.py --write-scad; PASS 2026-09-21).
//
// WHERE.  The board STANDS transverse (board plane normal to hull Y) on the
// solid 6.2 mm belly slab the sealed ramp fairing leaves under the chin
// shelf, X -196..-144, Y -17.25..-2, Z 10.2..44.1 -- i.e. right at the forward
// rim of the clamshell aperture (Y 2) where the door hinges' forward ends
// are, so the three servo pigtails are short (docs spec, section 6).  The
// component side faces AFT into the bay: J_FLEX, the two bus daisy-chain
// pairs and J_SWD are reachable through the open doors for service; the
// SOIC isolators on the back face the ramp fairing (the base slab is 2.75 mm
// off the floor-level wall at Y -20, the parts 2.5 mm off it above Z 18,
// more where the fairing leans forward above Z 15).  The chin
// shelf underside is 22 mm above the rail tops; the mission payload box
// (Y >= 4.7) clears the tallest front part (J_FLEX pins, Y -3.9) by 8.6 mm.
//
// WHAT IT IS.  A 5.4 mm CF-PETG base slab 52.2 x 15.25 mm (Y -17.25..-2)
// on four 7 x 7 mm slab bosses (M3 heat-set, RX-M3x5.7 -- 4 mm boss + 2 mm
// into the shell slab; M3 x 8 SHCS).  The rear screw row (Y -13) lies under
// the board's bottom edge, so its heads are counterbored O6.0 x 3.2 into
// the base top (1.25 mm walls) and COVERED by the board (cut the keeper
// tie, lift the board, and the screws are exposed); the front row (Y -6)
// sits forward of the rails with its heads exposed on the same top.  Two
// vertical side rails (1.6 mm outer wall + 1.2 mm fore/aft lips over 2 mm
// of the board's short edges, 2.2 mm slot = 1.6 board + 2 x 0.3) take the
// board from above; a fore/aft lip pair on the block top locates the bottom
// edge; a cable-tie keeper across the top edge runs through slots in both
// rail tops (the rails stand 3 mm above the board).  Two more tie slots in
// the forward apron take the servo pigtail bundle as strain relief.
// HOST CONSTRAINT carried to the board: no part within 2.5 mm of the two
// SHORT edges and the BOTTOM long edge on either face (the rail lips and
// block lips run there); the J_FLEX header may be anywhere else.
//
// LOADS.  Board + tray ~10 g (VERIFY: weigh the populated board; the BOM
//   carries an estimate) -> 0.25 N at the 2.5 g hard-landing case.  The
//   side rails are 1.6 x 4.6 mm columns 28.5 mm tall above the slab; as a
//   cantilever each sees M = 0.12 N x 0.03 m = 0.004 N.m against
//   Z = 4.6 x 1.6^2 / 6 = 2.0 mm^3 -> 2 MPa, FOS > 20 on a 45 MPa allowable.
//   The board is clamped on three edges, so its own first mode is set by the
//   49 mm free span between the rails: a 1.6 mm FR4 plate clamped on two
//   opposite edges (E ~ 20 GPa) is well above 1 kHz -- clear of the 470 Hz
//   EDF shaft rate and of every airframe mode.
//
// PRINT ORIENTATION: base slab flat on the bed, rails up (the rails print
//   as vertical walls -- 4 perimeters at 0.4 mm covers the 1.6 mm wall);
//   3 perimeters elsewhere, 30 % gyroid, CF-PETG (20 % CF), hardened nozzle.
//   No supports: the tie slots are horizontal through-slots <= 3.2 mm and
//   bridge; the rear counterbores are open from the top.  Est. 5 g (exported volume x 1.05 g/cm^3 -- see the BOM row
//   PRINT-GW-DOOR-TRAY).
//
// Author: Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// AI note: Written by Claude (model: Claude Opus 5, Anthropic) under the
//   author's direction, 2026-09-21, per AGENTS.md SS3 AI attribution.
// License: CC BY 4.0 -- creativecommons.org/licenses/by/4.0
// ============================================================

include <cargo_layout_t5_params.scad>

$fn = 48;
EPS = 0.01;

M3_CLR     = 3.4;                  // M3 clearance through the base
LIP_IN     = 2.0;                  // rail lip reach over the board's short edges (X)
LIP_H      = 1.2;                  // block-top lip height fore/aft of the bottom edge
TIE_SLOT   = [3.2, 1.6];           // cable-tie through-slot (long x short)
TIE_Z      = GW_PCB_Z1 + 0.6;      // keeper tie passes just over the board's top edge
APRON_TIE_Y = -3.5;                // strain-relief tie slots in the forward apron
APRON_TIE_X = [GW_XC - 10, GW_XC + 10];
BLOCK_Z1   = GW_Z0 + GW_BASE_T;    // 15.6: base slab top = board bottom edge
SLOT_Y     = [GW_PCB_Y0 - GW_RAIL_CLR, GW_PCB_Y1 + GW_RAIL_CLR];   // board slot in Y

// ---------------------------------------------------------------------------
// base: 5.4 mm slab Y -17.25..-2, four M3 holes (rear row counterbored from
// the slab top, under the board), two pigtail strain-relief slots forward
// ---------------------------------------------------------------------------
module base() {
    difference() {
        translate([GW_TRAY_X0, GW_BASE_Y0, GW_Z0])
            cube([GW_TRAY_X1 - GW_TRAY_X0, GW_BASE_Y1 - GW_BASE_Y0, GW_BASE_T]);
        for (b = GW_BOSS) {
            translate([GW_XC + b[0], b[1], GW_Z0 - 1]) cylinder(d = M3_CLR, h = GW_BASE_T + 2);
            if (b[1] < GW_TRAY_Y1)   // rear row: counterbore for the SHCS head under the board
                translate([GW_XC + b[0], b[1], BLOCK_Z1 - GW_CBORE_H])
                    cylinder(d = GW_CBORE_D, h = GW_CBORE_H + 1);
        }
        for (x = APRON_TIE_X)
            translate([x - TIE_SLOT[0] / 2, APRON_TIE_Y - TIE_SLOT[1] / 2, GW_Z0 - 1])
                cube([TIE_SLOT[0], TIE_SLOT[1], GW_BASE_T + 2]);
    }
}

// ---------------------------------------------------------------------------
// slab-top lips: two 1.2 mm ridges along X, fore and aft of the board slot,
// so the bottom edge is located in Y on the slab top (Z 15.6)
// ---------------------------------------------------------------------------
module base_lips() {
    for (y = [[GW_TRAY_Y0, SLOT_Y[0]], [SLOT_Y[1], GW_TRAY_Y1]])
        translate([GW_X0 - EPS, y[0], BLOCK_Z1 - EPS])
            cube([GW_X1 - GW_X0 + 2 * EPS, y[1] - y[0], LIP_H + EPS]);
}

// ---------------------------------------------------------------------------
// side rails: outer wall (1.6 in X, full rail depth 4.6 in Y) plus fore and
// aft lips (1.2 in Y) reaching LIP_IN over the board's short edge; the slot
// between the lips is GW_PCB_T + 2 x GW_RAIL_CLR.  A cable-tie slot through
// the outer wall just above the board's top edge takes the keeper tie.
// ---------------------------------------------------------------------------
module side_rail(sx) {
    xo = sx > 0 ? GW_X1 : GW_TRAY_X0;            // outer-wall X0
    xl = sx > 0 ? GW_X1 - LIP_IN : GW_X0;        // lip X0
    difference() {
        union() {
            translate([xo, GW_TRAY_Y0, BLOCK_Z1 - EPS])
                cube([GW_RAIL_T, GW_TRAY_Y1 - GW_TRAY_Y0, GW_TRAY_Z1 - BLOCK_Z1 + EPS]);
            for (y = [[GW_TRAY_Y0, SLOT_Y[0]], [SLOT_Y[1], GW_TRAY_Y1]])
                translate([xl, y[0], BLOCK_Z1 - EPS])
                    cube([LIP_IN + EPS, y[1] - y[0], GW_TRAY_Z1 - BLOCK_Z1 + EPS]);
        }
        // keeper-tie slot through the outer wall (long axis along Y)
        translate([xo - 1, (GW_PCB_Y0 + GW_PCB_Y1) / 2 - TIE_SLOT[0] / 2, TIE_Z - TIE_SLOT[1] / 2])
            cube([GW_RAIL_T + 2, TIE_SLOT[0], TIE_SLOT[1]]);
    }
}

union() {
    base();
    base_lips();
    side_rail(-1);
    side_rail(+1);
}
