// tilt_actuator_options_params.scad -- GENERATED by tools/tilt_actuator_options.py
// --write.  Per-option geometry for tilt_actuator_options.scad.  Do not edit.
// License: CC BY 4.0
OPT_MOTOR_D    = [0, 20.0, 25.0, 20.0, 20.0];
OPT_WORM_PD    = [0, 18.0, 24.0, 0.0, 26.0];
OPT_STARTS     = [0, 1, 4, 0, 6];
OPT_WHEEL_N    = [0, 40, 40, 38, 40];
OPT_MODULE     = [0, 1.00, 1.00, 0.80, 1.00];
OPT_C          = [0, 29.00, 32.00, 30.40, 33.00];
OPT_RATE_NL    = [0, 23.9, 168.0, 129.2, 143.6];
OPT_T_NAC      = [0, 1.83, 1.83, 1.34, 1.81];
OPT_MASS_PAIR  = [0, 130, 242, 188, 147];
OPT_T145       = [0, 6.09, 0.89, 1.15, 1.04];
OPT_T5         = [0, 0.24, 0.06, 0.07, 0.06];
OPT_LOCK       = [0, true, false, false, false];
OPT_NAME       = ["", "Single-start worm 40:1 + Pololu 20D 25:1 CB 6V", "Four-start worm 10:1 + Pololu 25D HP 6V 9.7:1 + brake", "Spur 1:1 (38T/38T m0.8) + DS3225 multi-turn (Rev T4)", "Six-start worm 6.67:1 + Pololu 20D 25:1 CB 6V + brake (Rev T5e, built)"];
