// ===========================================================================
// HULL-FRAME COORDINATE STANDARD - Rev R1 (2026-06-11).  See AGENTS.md.
//   X = +port (left), Y = +aft (back), Z = +dorsal (up).  Modelled directly
//   in hull frame; a VIEW model, not a printed part.
// ===========================================================================
// ============================================================
// tilt_actuator_options.scad -- Rev T5 trade view (2026-09-15)
// The three nacelle-tilt actuator options in the cargo bay, in context:
//   OPTION 1  single-start worm 40:1, Pololu 20D 25:1 (self-locking, 24 deg/s)
//   OPTION 2  four-start worm 10:1, Pololu 25D HP 9.7:1 (+brake, 168 deg/s)
//   OPTION 4  six-start worm 6.67:1, Pololu 20D 25:1 (+brake, 144 deg/s) --
//             the Rev T5e BUILT configuration (tilt_actuator_bracket.scad)
//   OPTION 3  Rev T4 spur 1:1 on the DS3225 standoff pads (129 deg/s, fouls
//             the battery cradle)
// Every dimension and every number printed on the canvas comes from
//   tilt_actuator_options_params.scad  (GENERATED by tools/tilt_actuator_options.py)
//   cargo_layout_t5_params.scad        (GENERATED by tools/cargo_layout_fit.py)
//   cargo_context_sections.scad        (hull ring sections from the published shell)
// Do not restate them here.
//
// What is drawn (port side, mirrored for starboard where the option is
// symmetric):
//   * hull skin ring sections at Y -10 / 20 / 46.6 / 80 (translucent grey)
//   * the wing drive shaft (O4, Y 46.6, Z 69.09) and the root flange keep-out
//   * the option's motor, fuselage-stage gears and bracket/pad envelope
//   * battery + cradle (Rev T5), mission payload at the door crown, bridle lines
//   * a red block wherever the option's motor envelope overlaps the cradle
//   * a text panel with rate / torque / time / hold / mass for the option
//
// Author: Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// AI note: Written by Claude (model: Claude Opus 5, Anthropic) under the
//   author's direction, 2026-09-15, per AGENTS.md SS3 AI attribution.
// License: CC BY 4.0 -- creativecommons.org/licenses/by/4.0
// ============================================================

include <cargo_layout_t5_params.scad>
include <tilt_actuator_options_params.scad>
include <cargo_context_sections.scad>

OPTION = 1;          // [1, 2, 3, 4]
SHOW_CONTEXT = true; // hull ring sections
SHOW_LABEL = true;

$fn = 48;

// ---------------------------------------------------------------------------
module ring_section(entry) {
    y = entry[0];
    translate([0, y, 0]) rotate([90, 0, 0])
        linear_extrude(height = 1.0, center = true)
            difference() {
                polygon(entry[1]);
                if (len(entry[2]) > 2) polygon(entry[2]);
            }
}

module context() {
    color("gray", 0.25) for (e = CARGO_SECTIONS) ring_section(e);
    // drive shaft + root flange keep-out (WA-R1b: Y -9..51, Z 27..107, 5 mm)
    color("black") for (s = [1, -1])
        translate([X_CL + s * (X_CL - (-86.33)) * -1 + 0, 0, 0]) {}
    color("dimgray") translate([-86.33, SHAFT_Y, SHAFT_Z]) rotate([0, -90, 0]) cylinder(d = 4, h = 40);
    color("dimgray") translate([2 * X_CL + 86.33, SHAFT_Y, SHAFT_Z]) rotate([0, 90, 0]) cylinder(d = 4, h = 40);
    color("sienna", 0.35) translate([-120.0, SHAFT_Y - 30, SHAFT_Z - 40]) cube([34, 60, 80]);
    color("sienna", 0.35) translate([2 * X_CL + 86.0, SHAFT_Y - 30, SHAFT_Z - 40]) cube([34, 60, 80]);
}

module battery_and_payload() {
    color("gold", 0.7) translate([BATT_X0, BATT_Y0, BATT_Z0]) cube([BATT_W, BATT_L, BATT_H]);
    color("orange", 0.35) translate([BATT_X0 - CRADLE_T, BATT_Y0 - CRADLE_T, BATT_Z0])
        cube([BATT_W + 2 * CRADLE_T, BATT_L + 2 * CRADLE_T, BATT_H + CRADLE_T]);
    color("green", 0.25) translate([BATT_XC - 76.2 / 2, HOIST_Y - 101.6 / 2, 8.72]) cube([76.2, 101.6, 76.2]);
    for (dx = [-HOIST_DX, HOIST_DX])
        color("black") translate([BATT_XC + dx, HOIST_Y, 85]) cylinder(d = 1, h = SPOOL_Z0 - 85 + 8);
}

// ---------------------------------------------------------------------------
// Option geometry, port side, in hull frame
// ---------------------------------------------------------------------------
module motor_cyl(d, l_body, l_enc, face_y, axis_x, axis_z) {
    translate([axis_x, 0, axis_z]) {
        color("dimgray") translate([0, face_y, 0]) rotate([90, 0, 0]) cylinder(d = d, h = l_body);
        color("darkslategray") translate([0, face_y - l_body, 0]) rotate([90, 0, 0]) cylinder(d = d, h = l_enc);
        color("silver") translate([0, face_y, 0]) rotate([-90, 0, 0]) cylinder(d = 4, h = 18);
    }
}

module worm_option(opt) {
    md = OPT_MOTOR_D[opt];
    wpd = OPT_WORM_PD[opt];
    C = OPT_C[opt];
    wz = SHAFT_Z + C;
    wx = GEAR_X_OUT - WHEEL_FACE / 2;
    // wheel on the shaft
    color("steelblue") translate([GEAR_X_OUT - WHEEL_FACE, SHAFT_Y, SHAFT_Z]) rotate([0, 90, 0])
        cylinder(d = OPT_WHEEL_N[opt] * OPT_MODULE[opt] + 2 * OPT_MODULE[opt], h = WHEEL_FACE);
    // worm
    color("goldenrod") translate([wx, SHAFT_Y - WORM_LEN / 2, wz]) rotate([-90, 0, 0])
        cylinder(d = wpd + 2 * OPT_MODULE[opt], h = WORM_LEN);
    // motor forward of the worm
    body = (opt == 1) ? MOTOR_BODY_L : 47.8;
    enc = (opt == 1) ? MOTOR_ENC_L : 12.0;
    motor_cyl(md, body, enc, MOTOR_FACE_Y, wx, wz);
    // bracket web + feet (outline)
    color("gray", 0.5) translate([GEAR_X_OUT + 3.0, 4, 72]) cube([2, 80, 61]);
    for (f = BRACKET_FEET)
        color("gray", 0.5) translate([GEAR_X_OUT + 5.0, f[0] - 6, f[1] - 6]) cube([26, 12, 12]);
    // brake (Opt 2): spring-applied friction brake on the worm shaft, aft of
    // the wheel -- envelope only, part not designed
    if (opt == 2)
        color("firebrick", 0.6) translate([wx, SHAFT_Y + WORM_LEN / 2 + 1, wz]) rotate([-90, 0, 0]) cylinder(d = 22, h = 10);
}

module spur_option() {
    // Rev T4: 38T/38T m0.8 spur, DS3225 body on the 18 mm standoff pad
    // (merge_cargo_interior.py NSVMT_*, Rev T1 numbers)
    gx0 = -111.0; gface = 6.0;           // gear plane, tenon +3
    cz = SHAFT_Z + 30.4;                 // actuator axis, C 30.40
    color("steelblue") translate([gx0 - gface, SHAFT_Y, SHAFT_Z]) rotate([0, 90, 0]) cylinder(d = 32, h = gface);
    color("goldenrod") translate([gx0 - gface, SHAFT_Y, cz]) rotate([0, 90, 0]) cylinder(d = 32, h = gface);
    // DS3225 body 40 (Y) x 20 (Z) x 40.5 (X inboard), shaft 24 mm from one end
    color("dimgray") translate([-158.5, SHAFT_Y - 24 + 4, cz - 10]) cube([40.5, 40, 20]);
    color("gray", 0.5) translate([-118.0, SHAFT_Y - 30.75, cz - 13.5]) cube([40, 61.5, 27]);   // pad to the skin
    // brake (needed, part TBD)
    color("firebrick", 0.6) translate([gx0 - gface - 11, SHAFT_Y, SHAFT_Z]) rotate([0, 90, 0]) cylinder(d = 22, h = 10);
    // overlap with the battery cradle, shown in red (explicit box: OpenCSG
    // preview mis-colours intersection() children)
    ox0 = max(-158.5, BATT_X0 - CRADLE_T);  ox1 = min(-118.0, BATT_X1 + CRADLE_T);
    oz0 = max(cz - 10, BATT_Z0);            oz1 = min(cz + 10, BATT_Z1 + CRADLE_T);
    if (ox1 > ox0 && oz1 > oz0)
        color("red") translate([ox0, SHAFT_Y - 20, oz0]) cube([ox1 - ox0, 40, oz1 - oz0]);
}

module mirror_x() { translate([2 * X_CL, 0, 0]) mirror([1, 0, 0]) children(); }

module option(opt) {
    if (opt == 3) { spur_option(); mirror_x() spur_option(); }
    else { worm_option(opt); mirror_x() worm_option(opt); }
}

module label(opt) {
    lines = [
        str("OPTION ", opt, ": ", OPT_NAME[opt]),
        str("nacelle rate ", OPT_RATE_NL[opt], " deg/s (no-load)   5 deg in ", OPT_T5[opt], " s   145 deg in ", OPT_T145[opt], " s"),
        str("torque limit at nacelle ", OPT_T_NAC[opt], " N.m   unpowered hold: ", OPT_LOCK[opt] ? "YES (self-locking)" : "brake required"),
        str("mass, both sides incl. shell delta: ", OPT_MASS_PAIR[opt], " g   (see docs/TILT_ACTUATOR_OPTIONS.md)")
    ];
    color("black") translate([-300, -120, 195]) rotate([90, 0, 0])
        for (i = [0 : len(lines) - 1])
            translate([0, -i * 8, 0]) text(lines[i], size = 4.5, halign = "left");
}

if (SHOW_CONTEXT) context();
battery_and_payload();
option(OPTION);
if (SHOW_LABEL) label(OPTION);
