"""cargo_door_hinge_params.py -- GENERATED by generate_cargo_doors.py.
Do not edit: change the shell/generator and re-run generate_cargo_doors.py to regenerate.
Hull frame, mm.  CARGO-HINGE-SYNC single source -- every other hinge-dependent
generator or SCAD file reads this, not a hand-copied constant.
"""

HINGE_X_PORT = -117.5322
HINGE_Z_PORT = 3.0029
HINGE_X_STBD = -222.6785
HINGE_Z_STBD = 3.4898
BAY_Y_FWD = 2.0000
BAY_Y_AFT = 108.0000
ROD_AXES = {
    "port": (HINGE_X_PORT, HINGE_Z_PORT),
    "stbd": (HINGE_X_STBD, HINGE_Z_STBD),
}
