// access_panels_24in.scad
// Serenity UAV Rev R — Hull Access Panels and Ventral Hatch Covers (24" build)
//
// Purpose:
//   Parametric library producing all removable hull access panels for the
//   24"-scaled Serenity.  Each cover's exterior face is generated by
//   intersection() with the local hull solid STL so that the printed part
//   sits flush with the curved hull outer-mold line (OML) when installed.
//
//   All geometry is constructed in hull-STL coordinate space and then
//   translated / rotated to a print-ready orientation for export.
//
//   NOTE: importing hull STLs for intersection is computationally intensive;
//   use the RENDER selector to export one part at a time.
//
// Eight parts across three categories:
//
//   (A) Avionics-bay Faraday covers (hull opening: 62 × 42 mm)
//       Shepherd — head section,  dorsal face (hull +Y normal)
//       Inara    — cargo section, dorsal face, GPS retention-ring clearance bore
//       River    — cargo section, dorsal face, GPS retention-ring clearance bore
//       Simon    — middle section, dorsal face
//
//   (B) Ventral hatch covers (middle section, hull −Y normal)
//       Battery  — 150 × 50 mm hull opening → 160 × 60 mm cover OD
//       Kaylee   — 105 × 90 mm hull opening → 115 × 100 mm cover OD
//
//   (C) Ventral hatch frames — bonded PETG frames for (B) covers
//       Battery frame, Kaylee frame
//       (flat rectangular rings; hull conformance not required for interior-bonded frames)
//
// Hull STL coordinate conventions (all hull sections):
//   X — lateral,      positive port (left)
//   Y — longitudinal, positive aft (back)
//   Z — vertical,     positive dorsal (up)
//
// Avionics-bay cover interface:
//   Opening:      62.0 × 42.0 mm  (AV_OPEN_X × AV_OPEN_Z)
//   Shoulder lip: 5.0 mm wide, 3.0 mm deep insertion; 1.5 mm positive-stop rebate
//   Cover OD:     72.0 × 52.0 mm  (AV_COVER_X × AV_COVER_Z)
//   Boss BC:      ±25.0 mm (X, fore–aft) × ±15.0 mm (Z, lateral) from bay centre
//   Fasteners:    4× M3 clearance bore (3.3 mm dia), shallow pan-head seat
//
// GPS retention-ring clearance (Inara + River only):
//   The GPS antenna body (35 mm OD, 6 mm deep) is flush-recessed into the hull
//   dorsal skin.  The cover shoulder (3 mm insertion depth) overlaps the GPS
//   body at the GPS mount locations.  A full-depth Ø42 mm bore in the shoulder
//   at the GPS centre position clears the body without penetrating the face plate.
//   GPS centre positions (cargo STL space):
//     Inara: Z = 104.70 mm  (GPS_INARA_DZ = −14.30 mm from Inara bay Z centre)
//     River: Z =  44.70 mm  (GPS_RIVER_DZ =  +0.70 mm from River bay Z centre)
//   Both GPS mounts are at X = CX (= −102.19 mm, cargo centroid X).
//
// Ventral hatch frame bonding:
//   West System 105/206 epoxy, frames flush with hull interior face.
//   Frame OD = hull opening; frame ID = opening + 2 × 0.5 mm insertion clearance.
//   Frame wall = 6.0 mm; pilot holes = 2.1 mm dia (M2.5 self-tapping in PETG).
//
// Print specification — all parts:
//   Material: CF-PETG (ventral frames: plain PETG acceptable)
//   Layers:   0.15 mm, 4 perimeters, 40 % gyroid infill
//   Orient:   exterior (hull-conforming) face UP on build plate for best surface
//
// Fabrication references:
//   CLAUDE.md §Fabrication: 2-wall contact annulus, positive-stop shoulder.
//   Ruthex RX-M3×5.7: boss bore 4.1 mm, OD 5.7 mm, length 5.7 mm.
//   ISO 14589: heat-set insert pullout in thermoplastics.
//
// Position constants derived from shell SCADs:
//   head_shell24.scad  (BOOK_* constants)
//   cargo_sect_shell24.scad  (AVINICS_*, INARA_*, RIVER_*, GPS_* constants)
//   middle_canonical_shell24.scad  (SIMON_*, BATT_*, KAYLEE_* constants)
//
// Author:  Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// License: CC BY 4.0  <https://creativecommons.org/licenses/by/4.0/>
// Date:    2026-06-11
// Rev:     R2 (2026-07-06): Corrected Inara/River covers to the cargo shell's
//   Rev R2 DORSAL (+Z-normal) frame.  The cargo shell now opens Inara/River on
//   the dorsal face as a lateral X-pair at one shared Y-station; the old covers
//   were built +Y-normal in a stale Z-stacked layout with mismatched M3 axes
//   (25/15 vs the shell's AVINICS_BOSS_DX/DY = 15/25) and an oversized GPS bore
//   (42 vs the shell's Ø38).  Added av_cover_dorsalZ(); re-derived all Inara/
//   River + GPS constants from cargo_sect_shell24.scad.  Shepherd/Simon left on
//   the legacy av_cover_dorsal until the head/middle bays get the same fix
//   (TODO.md §1.1.1 head/middle axis-bug items).  Resolves the two stale
//   GPS-clearance / M3-bore TODO items.
// Rev:     R1 (2026-06-11): Rewrite — hull-conforming exterior faces via STL
//   intersection; corrected M3 screw bore positions (was DX/2, now full ±DX);
//   GPS clearance bore extended to full shoulder depth (3 mm) to clear GPS body;
//   removed erroneous SCALE_24 re-application to pre-scaled middle hull STL.
//   R1 → R (2026-06-11): Updated hull STL paths — s_ prefix dropped per Rev R
//   repo-wide rename; paths migrated from archive/ to stls/fuselage/.
//   Original Rev R: flat-face version (2026-06-11, same session).

// ── Resolution ────────────────────────────────────────────────────────────────

$fn = 64;

// ── Hull STL references ───────────────────────────────────────────────────────
//
// SOLID hull STLs (before hollowing and sensor cuts) used for intersection().
// Paths are relative to airframe/openscad/fuselage/ (this file's directory).
// The middle section raw source requires SCALE_24 scaling (18" → 24").

// Paths follow the Rev R naming convention (no s_ prefix).
// head_shell24.stl and middle_canonical_shell24.stl are the solid canonical meshes
// exported to airframe/stls/fuselage/ by head_shell24.scad and
// middle_canonical_shell24.scad respectively.
// cargo_sect_shell24_repaired.stl is the solid repaired cargo mesh (copied from archive
// at the path already referenced by cargo_sect_shell24.scad).
HEAD_SOLID_STL    = "../../stls/fuselage/head_shell24.stl";
CARGO_SOLID_STL   = "../../stls/fuselage/cargo/cargo_sect_shell24_repaired.stl";
MIDDLE_SOLID_STL  = "../../stls/fuselage/middle_canonical_shell24.stl";

// ── Avionics-bay Faraday Cover Parameters ────────────────────────────────────

AV_OPEN_X      = 62.0;   // [mm] hull opening fore-aft (2.44 in)
AV_OPEN_Z      = 42.0;   // [mm] hull opening lateral  (1.65 in)
AV_SHOULDER    =  5.0;   // [mm] shoulder lip width each side (0.20 in)
AV_COVER_X     = AV_OPEN_X + 2 * AV_SHOULDER;   // = 72 mm (2.83 in)
AV_COVER_Z     = AV_OPEN_Z + 2 * AV_SHOULDER;   // = 52 mm (2.05 in)
AV_STEP_D      =  1.5;   // [mm] shoulder step rebate width (positive-stop)
AV_STEP_H      =  3.0;   // [mm] shoulder insertion depth into hull opening
AV_SLAB_T      = 10.0;   // [mm] intersection slab height — covers max hull curvature

// M3 fastener bores — Shepherd (head) + Simon (middle) covers ONLY.
// These two bays are still built in the legacy Y-as-dorsal-normal frame because
// their shells (head_shell24.scad BOOK_*, middle_canonical_shell24.scad SIMON_*)
// have NOT yet had the dorsal-axis correction the cargo shell received in Rev R2
// (TODO.md §1.1.1 head/middle axis-bug items — still open).  Inara/River (cargo)
// now use the corrected dorsal-Z constants + av_cover_dorsalZ() below instead.
AV_SCREW_DX    = 25.0;   // [mm] ±X offset (legacy Y-normal covers: BOOK/SIMON _BOSS_DX)
AV_SCREW_DZ    = 15.0;   // [mm] ±Z offset (legacy Y-normal covers: _BOSS_DZ)
AV_SCREW_D     =  3.3;   // [mm] M3 clearance bore diameter
AV_SCREW_CS    =  6.0;   // [mm] pan-head seat diameter (shallow pocket at exterior face)
AV_CS_DEPTH_Y  =  1.0;   // [mm] Y above interior face where wide bore begins (see note below)
                          //   Intersection with hull solid limits actual CS depth ≈ wall−1 mm.

// ── Cargo dorsal (Inara/River) — CORRECTED to Rev R2 dorsal (+Z) frame ────────
//   Re-derived 2026-07-06 from cargo_sect_shell24.scad current constants
//   (resolves the two stale GPS/M3 TODO items under MESH-01).  The corrected
//   cargo shell opens Inara/River on the DORSAL (+Z) face as a lateral X-pair at
//   ONE shared longitudinal (Y) station — not the pre-Rev-R2 Z-stacked, Y-normal
//   layout the legacy constants assumed.  Every value below equals the like-named
//   constant in cargo_sect_shell24.scad (single source of truth).
CARGO_WALL      =   2.0;      // = WALL_MM
CARGO_DORSAL_Z  = 163.2;      // = DORSAL_Z_EXT (exterior dorsal skin)
CARGO_CX        = -102.19;    // = CX (lateral centreline)
CARGO_STATION_Y = -328.63;    // = AVIONICS_STATION_Y = GPS_STATION_Y = CY
CARGO_BAY_SEP_X =  75.0;      // = BAY_SEP_X (Inara↔River centre-to-centre, X)
INARA_X         = CARGO_CX - CARGO_BAY_SEP_X / 2;  // = -139.69 (port half)
RIVER_X         = CARGO_CX + CARGO_BAY_SEP_X / 2;  // =  -64.69 (stbd half)
AVZ_OPEN_X      =  42.0;      // = AVINICS_PANEL_X (lateral opening; note X↔Y vs legacy)
AVZ_OPEN_Y      =  62.0;      // = AVINICS_PANEL_Y (longitudinal opening)
AVZ_SCREW_DX    =  15.0;      // = AVINICS_BOSS_DX (±X lateral M3 boss offset)
AVZ_SCREW_DY    =  25.0;      // = AVINICS_BOSS_DY (±Y longitudinal M3 boss offset)
AV_INSERT_CLR   =   0.5;      // [mm] shoulder slip-fit clearance per side into opening

// ── GPS Retention-Ring Clearance (cargo dorsal covers) ───────────────────────
GPS_CLEAR_OD   = 38.0;   // [mm] cover GPS clearance bore Ø — per the cargo shell's own
                          //   avinics_dorsal_panel_cut note ("access cover designed with
                          //   Ø38 mm clearance bore"); clears GPS body Ø36 (GPS_RECESS_D)
                          //   + fit.  (Was 42 mm in the stale side-wall frame.)
GPS_SEP        = CARGO_BAY_SEP_X / 2;  // [mm] = 37.5 = cargo_sect_shell24.scad GPS_SEP
                          //   (moved outboard 2026-07-06 to bay-centre so the Ø38 GPS
                          //   clearance bore stays fully enclosed in the ~46 mm-wide cover).
GPS_PORT_X     = CARGO_CX - GPS_SEP;   // = -139.69 (Inara GPS, centred under Inara cover)
GPS_STBD_X     = CARGO_CX + GPS_SEP;   // =  -64.69 (River GPS, centred under River cover)
GPS_XY_Y       = CARGO_STATION_Y;      // GPS shares the avionics Y station (Rev R2)

// ── Hull-Space Position Constants — Avionics Bays ─────────────────────────────
//
// Values sourced verbatim from the respective shell SCADs.
// All coordinates are in each hull section's local STL world space.
//
// Shepherd (head_shell24.scad: BOOK_* constants):
//   BOOK_X_CEN = CX = 161.33; BOOK_Z_CEN = CZ = 69.08
//   BOOK_DORSAL_Y = CY + 94.0 = -148.57 + 94 = -54.57 (interior dorsal face)
SHEP_X_CEN  = 161.33;   // mm, bay X centre (= CX = BOOK_X_CEN in head SCAD)
SHEP_Z_CEN  =  69.08;   // mm, bay Z centre (= CZ = BOOK_Z_CEN)
SHEP_Y_INT  = -54.57;   // mm, interior dorsal face Y (= BOOK_DORSAL_Y; VERIFY slicer)
//
// Inara (cargo_sect_shell24.scad: AVINICS_* + INARA_* constants):
//   AVINICS_X_CEN = CX = -102.19; INARA_Z_CEN = 119.0
//   AVINICS_DORSAL_Y = CY + 116 = -328.63 + 116 = -212.63 (interior dorsal face)
INARA_X_CEN = -102.19;  // mm, bay X centre (= AVINICS_X_CEN)
INARA_Z_CEN =  119.0;   // mm, bay Z centre (= INARA_Z_CEN in cargo SCAD)
INARA_Y_INT = -212.63;  // mm, interior dorsal face Y (= AVINICS_DORSAL_Y; VERIFY slicer)
//
// River (same cargo section; RIVER_Z_CEN = 44.0):
RIVER_X_CEN = -102.19;  // mm, bay X centre (same as Inara)
RIVER_Z_CEN =   44.0;   // mm, bay Z centre (= RIVER_Z_CEN in cargo SCAD)
RIVER_Y_INT = -212.63;  // mm, interior dorsal face Y (same as Inara)
//
// Simon (middle_canonical_shell24.scad: SIMON_* constants):
//   SIMON_X_CEN = CX = 180.95; SIMON_Z_CEN = MID_Z = CZ = 36.47
//   SIMON_DORSAL_Y = DORSAL_Y − WALL_MM = (CY+62) − 2.5 = (-67.28+62) − 2.5 = -7.78
SIMON_X_CEN = 180.95;  // mm, bay X centre
SIMON_Z_CEN =  36.47;  // mm, bay Z centre
SIMON_Y_INT =  -7.78;  // mm, interior dorsal face Y (= SIMON_DORSAL_Y; VERIFY slicer)

// ── Hull-Space Position Constants — Ventral Hatches ───────────────────────────
//
// Battery tray (middle_canonical_shell24.scad: BATT_* constants):
//   BATT_X_CEN = 94.0; BATT_Z_CEN = MID_Z = 36.47; BATT_HATCH_X/Z = 150/50
//   KAYLEE_VENTRAL_Y = VENTRAL_Y + WALL_MM = (CY-62) + 2.5 = -129.28 + 2.5 = -126.78
BATT_X_CEN  =  94.0;   // mm, battery tray X centre
BATT_Z_CEN  =  36.47;  // mm, battery tray Z centre
BATT_Y_INT  = -126.78; // mm, interior ventral face Y (= KAYLEE_VENTRAL_Y; VERIFY slicer)
BATT_OPEN_X = 150.0;   // mm, hull opening fore-aft (5.91 in)
BATT_OPEN_Z =  50.0;   // mm, hull opening lateral  (1.97 in)
BATT_COVER_X = BATT_OPEN_X + 2 * AV_SHOULDER;  // = 160 mm (6.30 in)
BATT_COVER_Z = BATT_OPEN_Z + 2 * AV_SHOULDER;  // =  60 mm (2.36 in)
//
// Kaylee PDB (middle_canonical_shell24.scad: KAYLEE_* constants):
//   KAYLEE_X_CEN = 29.0; KAYLEE_Z_CEN = MID_Z = 36.47; KAYLEE_HATCH_X/Z = 105/90
KLEE_X_CEN  =  29.0;   // mm, Kaylee tray X centre
KLEE_Z_CEN  =  36.47;  // mm, Kaylee tray Z centre
KLEE_Y_INT  = -126.78; // mm, interior ventral face Y (same as battery)
KLEE_OPEN_X = 105.0;   // mm, hull opening fore-aft (4.13 in)
KLEE_OPEN_Z =  90.0;   // mm, hull opening lateral  (3.54 in)
KLEE_COVER_X = KLEE_OPEN_X + 2 * AV_SHOULDER;  // = 115 mm (4.53 in)
KLEE_COVER_Z = KLEE_OPEN_Z + 2 * AV_SHOULDER;  // = 100 mm (3.94 in)

// ── Ventral Hatch Frame Parameters ────────────────────────────────────────────

H_STEP_H         =  3.0;   // [mm] cover shoulder insertion depth (same as AV_STEP_H)
H_STEP_D         =  1.5;   // [mm] shoulder step rebate (same as AV_STEP_D)
H_FRAME_T        =  6.0;   // [mm] frame wall thickness (0.24 in)
H_FRAME_H        =  4.5;   // [mm] frame height (set flush with hull interior face)
H_INSERT_CLEAR   =  0.5;   // [mm] cover shoulder insertion clearance per side
H_PILOT_D        =  2.1;   // [mm] M2.5 pilot bore (self-tapping in PETG)

// ── Module: av_cover_dorsal ───────────────────────────────────────────────────
//
// Hull-conforming avionics-bay cover for a DORSAL-face (+Y normal) bay.
// All geometry constructed in hull-STL coordinate space.
//
// Parameters:
//   stl      — hull solid STL path (string constant)
//   x_cen    — bay centre X in hull STL space [mm]
//   y_int    — interior dorsal face Y in hull STL space [mm]
//   z_cen    — bay centre Z in hull STL space [mm]
//   gps_z    — GPS clearance offset from z_cen in Z [mm]; 0 = no clearance bore
//   gps_x    — GPS clearance bore X in hull STL space [mm]; used only when gps_z ≠ 0
//
// Geometry:
//   Face plate: intersection of slab (from y_int to y_int+AV_SLAB_T) with hull solid.
//     Interior face: flat at y_int (hull interior face)
//     Exterior face: follows hull outer-mold line contour
//   Shoulder lip: flat box from y_int−AV_STEP_H to y_int (inserts into opening)
//   Step rebate: 1.5 mm groove at shoulder perimeter at y_int junction (positive stop)
//   Screw bores: 4× M3 clearance (3.3 mm) at ±AV_SCREW_DX (X) × ±AV_SCREW_DZ (Z)
//   GPS bore (optional): Ø42 mm × AV_STEP_H full-depth clearance in shoulder only
//
module av_cover_dorsal(stl, x_cen, y_int, z_cen, gps_z = 0, gps_x = 0) {
    difference() {
        union() {
            // ── Exterior face plate — hull-conforming ─────────────────────
            // Slab spans from interior face (y_int) outward (+ Y) by AV_SLAB_T.
            // Intersection trims the top surface to the hull OML curvature.
            // Interior face remains flat at y_int.
            intersection() {
                translate([x_cen - AV_COVER_X / 2,
                           y_int,
                           z_cen - AV_COVER_Z / 2])
                    cube([AV_COVER_X, AV_SLAB_T, AV_COVER_Z]);
                import(stl, convexity = 10);
            }

            // ── Shoulder insertion lip — flat rectangular block ────────────
            // Inserts into hull opening from exterior inward (−Y from y_int).
            translate([x_cen - AV_OPEN_X / 2,
                       y_int - AV_STEP_H,
                       z_cen - AV_OPEN_Z / 2])
                cube([AV_OPEN_X, AV_STEP_H, AV_OPEN_Z]);
        }

        // ── Shoulder step rebate (positive-stop shoulder) ─────────────────
        // Removes a STEP_D-wide × STEP_D-tall groove at the shoulder
        // perimeter at the face-plate junction (y = y_int).
        // The trimmed shoulder seats against the hull opening edge.
        translate([x_cen - AV_OPEN_X / 2 - AV_STEP_D,
                   y_int - AV_STEP_D,
                   z_cen - AV_OPEN_Z / 2 - AV_STEP_D])
            cube([AV_OPEN_X + 2 * AV_STEP_D,
                  AV_STEP_D + 0.01,
                  AV_OPEN_Z + 2 * AV_STEP_D]);

        // ── M3 screw clearance bores (4×) ─────────────────────────────────
        // Through-bore: from shoulder bottom to above face plate (+Y).
        // Boss positions: ±AV_SCREW_DX (X) × ±AV_SCREW_DZ (Z) from centre.
        // Shallow large-dia pocket begins AV_CS_DEPTH_Y above y_int;
        // intersection with face plate limits actual seat depth to ≈ wall − 1 mm.
        for (dx = [-AV_SCREW_DX, AV_SCREW_DX])
        for (dz = [-AV_SCREW_DZ, AV_SCREW_DZ]) {
            // 3.3 mm clearance bore — full height (shoulder bottom to above face)
            translate([x_cen + dx, y_int - AV_STEP_H - 0.1, z_cen + dz])
                rotate([-90, 0, 0])
                    cylinder(h = AV_STEP_H + AV_SLAB_T + 0.2, d = AV_SCREW_D);
            // Pan-head seat — wide bore starting AV_CS_DEPTH_Y above y_int
            translate([x_cen + dx, y_int + AV_CS_DEPTH_Y, z_cen + dz])
                rotate([-90, 0, 0])
                    cylinder(h = AV_SLAB_T, d = AV_SCREW_CS);
        }

        // ── GPS retention-ring clearance bore (optional) ──────────────────
        // Full-depth Ø42 mm bore through shoulder only — does NOT penetrate
        // the face plate above y_int, preserving EMI integrity.
        // Applied only when gps_z ≠ 0.
        if (gps_z != 0) {
            translate([gps_x, y_int - AV_STEP_H - 0.1, z_cen + gps_z])
                rotate([-90, 0, 0])
                    cylinder(h = AV_STEP_H + 0.2, d = GPS_CLEAR_OD);
        }
    }
}

// ── Module: av_cover_dorsalZ ──────────────────────────────────────────────────
//
// Hull-conforming avionics-bay cover for a TRUE dorsal (+Z-normal) bay — the
// corrected cargo Inara/River geometry (Rev R2, 2026-07-03).  Distinct from
// av_cover_dorsal above, which extrudes along +Y (the legacy head/middle
// "Y-as-dorsal" frame that the cargo shell no longer uses).
//
// All geometry constructed in cargo-STL local space (X lateral, Y longitudinal,
// Z dorsal/up).  The face plate's top follows the dorsal OML; the shoulder plugs
// the AVINICS_PANEL_X × AVINICS_PANEL_Y opening downward (−Z).
//
// Parameters:
//   stl   — cargo solid STL path (OML intersection)
//   x_cen — bay centre X (lateral)                 [mm]
//   y_cen — bay centre Y (longitudinal)            [mm]
//   z_ext — dorsal exterior skin Z (= CARGO_DORSAL_Z) [mm]
//   gps_x — GPS clearance-bore centre X            [mm]  (0 ⇒ no bore)
//   gps_y — GPS clearance-bore centre Y            [mm]
//
// Screw bores: 4× M3 clearance (Ø AV_SCREW_D) along Z at ±AVZ_SCREW_DX (X) ×
//   ±AVZ_SCREW_DY (Y) — matching the shell's AVINICS_BOSS_DX/DY exactly.
// GPS bore: full-depth Ø GPS_CLEAR_OD along Z at (gps_x, gps_y) so the cover
//   clears the recessed GPS antenna + retention ring it overlaps.
//
module av_cover_dorsalZ(stl, x_cen, y_cen, z_ext, gps_x = 0, gps_y = 0) {
    cover_x = AVZ_OPEN_X + 2 * AV_SHOULDER;         // 52 mm (lateral)
    cover_y = AVZ_OPEN_Y + 2 * AV_SHOULDER;         // 72 mm (longitudinal)
    z_int   = z_ext - CARGO_WALL;                   // interior dorsal skin face
    // Shoulder is undersized by AV_INSERT_CLR per side for slip-fit into the
    // AVINICS_PANEL opening; the face-plate overhang (AV_SHOULDER = 5 mm all
    // round) is itself the positive stop — it seats on the hull exterior around
    // the opening.  (No full-width rebate groove — that would sever the plate
    // from the shoulder, since the shoulder is narrower than such a groove.)
    sh_x = AVZ_OPEN_X - 2 * AV_INSERT_CLR;
    sh_y = AVZ_OPEN_Y - 2 * AV_INSERT_CLR;

    difference() {
        union() {
            // ── Exterior face plate — hull-conforming (dorsal OML top) ─────
            // Slab from interior face (z_int) outward (+Z) by AV_SLAB_T;
            // intersection trims the top to the hull outer-mold line.
            intersection() {
                translate([x_cen - cover_x / 2, y_cen - cover_y / 2, z_int])
                    cube([cover_x, cover_y, AV_SLAB_T]);
                import(stl, convexity = 10);
            }

            // ── Shoulder insertion lip — plugs opening downward (−Z) ───────
            // Overlaps the plate by 0.2 mm in Z (z_int+0.2) so the union is a
            // single solid; slip-fit clearance AV_INSERT_CLR per side.
            translate([x_cen - sh_x / 2,
                       y_cen - sh_y / 2,
                       z_int - AV_STEP_H])
                cube([sh_x, sh_y, AV_STEP_H + 0.2]);
        }

        // ── M3 screw clearance bores (4×), along +Z ────────────────────────
        // Positions ±AVZ_SCREW_DX (X) × ±AVZ_SCREW_DY (Y) — match shell bosses.
        for (dx = [-AVZ_SCREW_DX, AVZ_SCREW_DX])
        for (dy = [-AVZ_SCREW_DY, AVZ_SCREW_DY]) {
            translate([x_cen + dx, y_cen + dy, z_int - AV_STEP_H - 0.1])
                cylinder(h = AV_STEP_H + AV_SLAB_T + 0.2, d = AV_SCREW_D);
            translate([x_cen + dx, y_cen + dy, z_int + AV_CS_DEPTH_Y])
                cylinder(h = AV_SLAB_T, d = AV_SCREW_CS);
        }

        // ── GPS retention-ring clearance bore (full depth along Z) ─────────
        // The GPS antenna sits under the cover offset from centre; a full-depth
        // Ø GPS_CLEAR_OD bore lets the recessed antenna + ring pass through.
        if (gps_x != 0) {
            translate([gps_x, gps_y, z_int - AV_STEP_H - 0.1])
                cylinder(h = AV_STEP_H + AV_SLAB_T + 0.2, d = GPS_CLEAR_OD);
        }
    }
}

// ── Module: av_cover_ventral ──────────────────────────────────────────────────
//
// Hull-conforming ventral hatch cover for a VENTRAL-face (−Y normal) bay.
// Uses MIDDLE_SOLID_STL which is already at 24" scale — no additional scaling applied.
//
// Geometry:
//   Face plate: intersection of slab (from y_int−AV_SLAB_T to y_int) with
//               SCALE_24-scaled middle hull solid.
//     Interior face: flat at y_int (hull interior ventral face)
//     Exterior face: follows hull belly OML curvature below y_int
//   Shoulder lip: flat box from y_int to y_int+H_STEP_H (inserts into opening upward)
//   Step rebate: groove at shoulder base at y_int junction
//   Pilot bores: M2.5 clearance (2.1 mm) at calculated positions
//
// Parameters:
//   x_cen, y_int, z_cen — bay centre coords in middle hull STL space [mm]
//   open_x, open_z      — hull opening dimensions [mm]
//
module av_cover_ventral(x_cen, y_int, z_cen, open_x, open_z) {
    cover_x = open_x + 2 * AV_SHOULDER;
    cover_z = open_z + 2 * AV_SHOULDER;

    // Pilot positions: pairs evenly spaced on long edges, singles on short edges
    long_px = (open_x > 120) ? [-open_x / 3, open_x / 3] : [-open_x / 4, open_x / 4];
    short_pz = (open_z > 80)  ? [-open_z / 3, open_z / 3] : [0];

    difference() {
        union() {
            // ── Exterior belly face — hull-conforming ─────────────────────
            // Slab spans from y_int−AV_SLAB_T to y_int (capturing hull belly material).
            // Intersection trims lower surface to hull belly OML curvature.
            // Interior face remains flat at y_int.
            intersection() {
                translate([x_cen - cover_x / 2,
                           y_int - AV_SLAB_T,
                           z_cen - cover_z / 2])
                    cube([cover_x, AV_SLAB_T, cover_z]);
                import(MIDDLE_SOLID_STL, convexity = 10);
            }

            // ── Shoulder lip — inserts upward (+Y) from interior face ──────
            translate([x_cen - open_x / 2,
                       y_int,
                       z_cen - open_z / 2])
                cube([open_x, H_STEP_H, open_z]);
        }

        // ── Shoulder step rebate ───────────────────────────────────────────
        translate([x_cen - open_x / 2 - H_STEP_D,
                   y_int,
                   z_cen - open_z / 2 - H_STEP_D])
            cube([open_x + 2 * H_STEP_D, H_STEP_D + 0.01, open_z + 2 * H_STEP_D]);

        // ── M2.5 pilot bores — long edges (±Z sides) ──────────────────────
        for (px = long_px) {
            for (zs = [-1, 1]) {
                translate([x_cen + px,
                           y_int + H_STEP_H - H_FRAME_H - 0.1,
                           z_cen + zs * (open_z / 2 + AV_SHOULDER / 2)])
                    rotate([-90, 0, 0])
                        cylinder(h = H_FRAME_H + AV_SLAB_T + 0.2, d = H_PILOT_D);
            }
        }
        // ── M2.5 pilot bores — short edges (±X sides) ─────────────────────
        for (pz = short_pz) {
            for (xs = [-1, 1]) {
                translate([x_cen + xs * (open_x / 2 + AV_SHOULDER / 2),
                           y_int + H_STEP_H - H_FRAME_H - 0.1,
                           z_cen + pz])
                    rotate([-90, 0, 0])
                        cylinder(h = H_FRAME_H + AV_SLAB_T + 0.2, d = H_PILOT_D);
            }
        }
    }
}

// ── Module: hatch_frame ───────────────────────────────────────────────────────
//
// Flat bonded PETG ventral hatch frame.
// OD = hull opening; ID = hull opening + 2 × H_INSERT_CLEAR (cover shoulder clearance).
// Frame is oriented with Y = frame height direction, printed flat on build plate.
//
// Parameters:
//   open_x, open_z — hull opening dimensions [mm]
//
module hatch_frame(open_x, open_z) {
    // Pilot positions matching hatch_cover
    long_px  = (open_x > 120) ? [-open_x / 3, open_x / 3] : [-open_x / 4, open_x / 4];
    short_pz = (open_z > 80)  ? [-open_z / 3, open_z / 3] : [0];

    difference() {
        // Frame OD block
        translate([-open_x / 2, 0, -open_z / 2])
            cube([open_x, H_FRAME_H, open_z]);

        // Frame interior cavity (cover shoulder clearance 0.5 mm per side)
        translate([-(open_x / 2 + H_INSERT_CLEAR),
                   -0.1,
                   -(open_z / 2 + H_INSERT_CLEAR)])
            cube([open_x + 2 * H_INSERT_CLEAR, H_FRAME_H + 0.2, open_z + 2 * H_INSERT_CLEAR]);

        // M2.5 pilot bores — long edges
        for (px = long_px) {
            for (zs = [-1, 1]) {
                translate([px, -0.1, zs * (open_z / 2 + H_FRAME_T / 2)])
                    rotate([-90, 0, 0])
                        cylinder(h = H_FRAME_H + 0.2, d = H_PILOT_D);
            }
        }
        // M2.5 pilot bores — short edges
        for (pz = short_pz) {
            for (xs = [-1, 1]) {
                translate([xs * (open_x / 2 + H_FRAME_T / 2), -0.1, pz])
                    rotate([-90, 0, 0])
                        cylinder(h = H_FRAME_H + 0.2, d = H_PILOT_D);
            }
        }
    }
}

// ── Print Orientation Helpers ─────────────────────────────────────────────────
//
// Each hull-space module is wrapped with a translation + rotation that places
// the part ready for FDM printing:
//   Dorsal covers: shoulder bottom at Z=0 on build plate; exterior face is up.
//     rotate([-90,0,0]) maps hull +Y (dorsal, outward) → print +Z (up).
//     translate([-x_cen, -(y_int − AV_STEP_H), −z_cen]) centres at origin.
//
//   Ventral covers: shoulder top at Z=0 on build plate; exterior (belly) face up.
//     rotate([90,0,0]) maps hull -Y (ventral, outward) → print +Z (up).
//     translate([-x_cen, -(y_int + H_STEP_H), −z_cen]) centres at origin.

// ── Named Part Modules (print-oriented) ───────────────────────────────────────

// Shepherd cover — head section, dorsal face, no GPS bore.
// NOTE: Shepherd (head) + Simon (middle) still use the legacy Y-normal
// av_cover_dorsal because their shells' avionics bays have NOT yet had the
// dorsal-axis correction the cargo shell got in Rev R2 (TODO.md §1.1.1
// head/middle axis-bug items — still open).  Re-derive these to av_cover_dorsalZ
// once head_shell24.scad BOOK_* / middle SIMON_* are moved to the dorsal frame.
module shepherd_cover() {
    rotate([-90, 0, 0])
    translate([-SHEP_X_CEN, -(SHEP_Y_INT - AV_STEP_H), -SHEP_Z_CEN])
        av_cover_dorsal(HEAD_SOLID_STL, SHEP_X_CEN, SHEP_Y_INT, SHEP_Z_CEN);
}

// Inara cover — cargo section, DORSAL (+Z) face, GPS_PORT clearance bore.
// Corrected 2026-07-06 to the Rev R2 dorsal-Z frame (av_cover_dorsalZ): bay at
// (INARA_X, CARGO_STATION_Y) opening on the dorsal skin (Z = CARGO_DORSAL_Z);
// GPS_PORT sits under the cover at (GPS_PORT_X, GPS_XY_Y).  Print orientation:
// exterior (+Z) face up, shoulder bottom on the build plate.
module inara_cover() {
    translate([-INARA_X, -CARGO_STATION_Y,
               -(CARGO_DORSAL_Z - CARGO_WALL - AV_STEP_H)])
        av_cover_dorsalZ(CARGO_SOLID_STL, INARA_X, CARGO_STATION_Y, CARGO_DORSAL_Z,
                         gps_x = GPS_PORT_X, gps_y = GPS_XY_Y);
}

// River cover — cargo section, DORSAL (+Z) face, GPS_STBD clearance bore.
// Corrected 2026-07-06 to the Rev R2 dorsal-Z frame (see inara_cover).
module river_cover() {
    translate([-RIVER_X, -CARGO_STATION_Y,
               -(CARGO_DORSAL_Z - CARGO_WALL - AV_STEP_H)])
        av_cover_dorsalZ(CARGO_SOLID_STL, RIVER_X, CARGO_STATION_Y, CARGO_DORSAL_Z,
                         gps_x = GPS_STBD_X, gps_y = GPS_XY_Y);
}

// Simon cover — middle section, dorsal face, no GPS bore
module simon_cover() {
    rotate([-90, 0, 0])
    translate([-SIMON_X_CEN, -(SIMON_Y_INT - AV_STEP_H), -SIMON_Z_CEN])
        av_cover_dorsal(MIDDLE_SOLID_STL, SIMON_X_CEN, SIMON_Y_INT, SIMON_Z_CEN);
    // NOTE: middle hull STL uses SCALE_24 in middle_canonical_shell24.scad
    // but the solid archive STL (s_middle_shell24.stl) is already 24"-scaled.
}

// Battery cover — middle section, ventral face
module battery_cover() {
    rotate([90, 0, 0])
    translate([-BATT_X_CEN, -(BATT_Y_INT + H_STEP_H), -BATT_Z_CEN])
        av_cover_ventral(BATT_X_CEN, BATT_Y_INT, BATT_Z_CEN, BATT_OPEN_X, BATT_OPEN_Z);
}

// Battery frame — bonded PETG frame for battery hatch
module battery_frame() {
    hatch_frame(BATT_OPEN_X, BATT_OPEN_Z);
}

// Kaylee cover — middle section, ventral face
module kaylee_cover() {
    rotate([90, 0, 0])
    translate([-KLEE_X_CEN, -(KLEE_Y_INT + H_STEP_H), -KLEE_Z_CEN])
        av_cover_ventral(KLEE_X_CEN, KLEE_Y_INT, KLEE_Z_CEN, KLEE_OPEN_X, KLEE_OPEN_Z);
}

// Kaylee frame — bonded PETG frame for Kaylee hatch
module kaylee_frame() {
    hatch_frame(KLEE_OPEN_X, KLEE_OPEN_Z);
}

// ── Render Selector ───────────────────────────────────────────────────────────
//
// Set RENDER to the part name for STL export, or "layout" for a visual overview.
// Single-part renders are faster (only one hull STL is loaded).
//
// Part names:
//   "shepherd"   Shepherd Faraday cover  (head section, dorsal)
//   "inara"      Inara Faraday cover     (cargo section, dorsal, GPS recess)
//   "river"      River Faraday cover     (cargo section, dorsal, GPS recess)
//   "simon"      Simon Faraday cover     (middle section, dorsal)
//   "battery"    Battery ventral cover   (middle section, ventral)
//   "battery_f"  Battery ventral frame
//   "kaylee"     Kaylee ventral cover    (middle section, ventral)
//   "kaylee_f"   Kaylee ventral frame
//   "layout"     All 8 parts arranged on build plate (slow — 3 hull STL imports)

RENDER = "layout";   // ← change to part name for single-part STL export

if (RENDER == "shepherd")  shepherd_cover();
if (RENDER == "inara")     inara_cover();
if (RENDER == "river")     river_cover();
if (RENDER == "simon")     simon_cover();
if (RENDER == "battery")   battery_cover();
if (RENDER == "battery_f") battery_frame();
if (RENDER == "kaylee")    kaylee_cover();
if (RENDER == "kaylee_f")  kaylee_frame();

if (RENDER == "layout") {
    // ── Row 1: four Faraday-bay covers (72 × 52 mm footprint) ────────────
    // Spaced 10 mm apart in X.  All printed face-up (exterior face = +Z).
    _gap = 10;
    _pitch = AV_COVER_X + _gap;

    translate([-_pitch * 1.5, 0, 0]) shepherd_cover();
    translate([-_pitch * 0.5, 0, 0]) inara_cover();
    translate([ _pitch * 0.5, 0, 0]) river_cover();
    translate([ _pitch * 1.5, 0, 0]) simon_cover();

    // ── Row 2: battery cover + frame, Kaylee cover + frame ───────────────
    _row2_y = AV_COVER_Z + 30;

    translate([-(BATT_COVER_X + _gap) / 2 - (KLEE_COVER_X + _gap) / 2,
               _row2_y, 0])
        battery_cover();
    translate([-(BATT_COVER_X + _gap) / 2 - (KLEE_COVER_X + _gap) / 2,
               _row2_y + BATT_COVER_X + 20, 0])
        battery_frame();

    translate([(KLEE_COVER_X + _gap) / 2,
               _row2_y, 0])
        kaylee_cover();
    translate([(KLEE_COVER_X + _gap) / 2,
               _row2_y + KLEE_COVER_X + 20, 0])
        kaylee_frame();
}
