// ===========================================================================
// HULL-FRAME COORDINATE STANDARD - Rev R1 (2026-06-11).  See AGENTS.md.
//   Hull frame (canonical for ALL design artifacts): X = +port (left),
//   Y = +aft (back), Z = +dorsal (up); origin = SerenityAssembly.FCStd
//   world origin.  MODELLED DIRECTLY IN HULL FRAME; the exported STL imports
//   into serenity_assembly.py at identity placement.
// ===========================================================================
// ============================================================
// simon_node_saddle.scad -- Rev T6 (2026-09-17)
// Saddle for Simon's med bay: the aft flight-control / comms node pair
// CN4 (XO cape, low) + FC4 (Pilot cape, high), each a PB2I + cape stack in a
// Faraday pouch (58 x 37 x 22, cargo_layout_fit.NODE_*), STANDING transverse
// and STACKED in the middle section's inner neck at Y 178..200, aft of the
// Flight Engineer can.  Every station is from middle_layout_t6_params.scad
// (GENERATED by tools/middle_layout_fit.py --write-scad; PASS 2026-09-17).
//
// WHY HERE.  The neck is a ~O125 bore 71 mm long between two bonded 2 mm
// splice-collar sleeves; the Flight Engineer unit takes Y 140..176 and the
// only remaining depth is aft of it.  Two pouches side by side (126 mm) do
// not fit the bore; stacked (68 x 77 incl. the port cable zone) they clear
// it by > 10 mm at every corner.  The rear cone (Y > 203.6) is reserved for
// the Phase 11 aft EDF and nothing here reaches it (SIMON_Y1 = 200).
//
// WHAT IT IS.  A CF-PETG block that stands on the neck floor (its underside
// is the bore cylinder, trimmed to the actual skin by merge_middle_interior
// .py) and presents two open-topped slots the pouches drop into from above
// (the upper one) or slide into from forward (both slots are open to -Y; the
// lower one is a drawer under the 3 mm bridge).  Each pouch is held in Y and
// Z by two 16 mm cam straps (BATT-STRAP-CAM, the same part as every other
// node) that pass down through the floor slots, along the pocket under the
// floor, up the other slot and over the pouch -- there is no forward lip, so
// the strap IS the fore-aft retention.  4 x M3 into
// heat-set floor bosses fused by merge_middle_interior.py (SADDLE_BOSS).
//
// SERVICE.  Simon is serviced through the Flight Engineer hatch: lower the
// Flight Engineer unit on its harness, release its two straps, slide the pouch forward out of its slot and down
// through the opening.  Pouch connector edges face PORT into the cable zone
// (X -140.85..-130.85) where the Simon trunk arrives from the Flight
// Engineer plate.
//
// LOADS.  2 x ~58 g + straps: 1.2 N at 1 g, 2.9 N at the 2.5 g hard-landing
//   case, on a block 66 wide x 26 long standing on the floor -- bearing is
//   trivial (< 0.01 MPa).  The upper bridge (3 mm CF-PETG, 62 mm span, 26 mm
//   wide) under 1.5 N: M = 1.5 x 0.062 / 8 = 0.012 N.m, Z = 26 x 3^2 / 6 =
//   39 mm^3 -> 0.3 MPa.  Nothing.  Vibration: the pouches are strapped to a
//   stiff block; the 3 mm silicone foam in each pouch is the isolator, as in
//   the cargo section (docs/CARGO_SECTION_LAYOUT.md SS3a).
//
// PRINT ORIENTATION: slots up (as modelled, +Z up), on the curved underside
//   with support; or print upside down on the flat bridge and add a brim.
//   3 perimeters, 30 % gyroid, CF-PETG.  Mass: solid-CAD volume x 1.27 g/cm^3
//   upper bound is reported by the export (~22 g); the pocketed underside
//   stands on 3 mm walls and four O10 screw pillars.
//
// Author: Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// AI note: Written by Claude (model: Claude Opus 5, Anthropic) under the
//   author's direction, 2026-09-17, per AGENTS.md SS3 AI attribution.
// License: CC BY 4.0 -- creativecommons.org/licenses/by/4.0
// ============================================================

include <middle_layout_t6_params.scad>

$fn = 64;
EPS = 0.01;

WALL_T     = 2.4;                 // slot walls and floor lips
BRIDGE_T   = SIMON_STACK_GAP;     // 3.0: upper pouch sits on this bridge
POUCH_CLR  = 0.6;                 // per side, pouch-in-slot
M3_CLR     = 3.4;
M3_HEAD    = 6.4;                 // socket-head counterbore
STRAP_SLOT = [4.0, 20.0];         // Y x X through-slots for the 16 mm cam straps
LIP_H      = 6.0;                 // height of the slot walls above each pouch bottom
AFT_NECK_ZC = SIMON_ZC;           // aft-neck bore centre (Z 80.5, measured)
AFT_NECK_R  = 60.5;               // aft-neck bore radius (O121, measured at Y 198)

SX0 = SIMON_X0 - WALL_T;  SX1 = SIMON_X1 + WALL_T;   // block X extent (66.8)
SY0 = SIMON_Y0;           SY1 = SIMON_Y1 + WALL_T;   // block Y extent: pouch depth + aft wall
ZB  = CN4_Z0;                                        // lower pouch bottom (42.0)

module bore_cylinder(r) {
    // the neck bore as a Y-axis cylinder, used to trim the underside
    translate([SIMON_XC, SY0 - 1, AFT_NECK_ZC]) rotate([-90, 0, 0])
        cylinder(h = SY1 - SY0 + 2, r = r);
}

module pouch_void(z0) {
    // slot for one pouch, open forward (-Y) above FWD_CUT_H (the lower slot is
    // a drawer under the bridge; the upper one is open-topped)
    translate([SIMON_X0 - POUCH_CLR, SY0 - 1, z0])
        cube([NODE_L + 2 * POUCH_CLR, NODE_T + 1 + POUCH_CLR, NODE_H + POUCH_CLR]);
}

module strap_slots(z0) {
    for (x = [SIMON_XC - 18, SIMON_XC + 18])
        translate([x - STRAP_SLOT[1] / 2, SY0 + NODE_T / 2 - STRAP_SLOT[0] / 2, z0 - BRIDGE_T - 1])
            cube([STRAP_SLOT[1], STRAP_SLOT[0], BRIDGE_T + 2]);
}

module saddle_body() {
    difference() {
        // solid block from below the floor up to the top of the lower slot lip
        // one block, full height: side and aft walls run continuously past the
        // lower slot, under the bridge and up to the upper slot's lip
        translate([SX0, SY0, 5]) cube([SX1 - SX0, SY1 - SY0, FC4_Z0 + LIP_H - 5]);
        pouch_void(ZB);
        pouch_void(FC4_Z0);
        // strap slots through the lower floor and the bridge
        strap_slots(ZB);
        strap_slots(FC4_Z0);
        // M3 counterbored holes down through the floor into the shell bosses
        for (b = SADDLE_BOSS) translate([b[0], b[1], 0]) {
            cylinder(h = 200, d = M3_CLR);
            translate([0, 0, ZB - 4]) cylinder(h = 200, d = M3_HEAD);
        }
        // lightening pocket under the lower slot floor: 3 mm perimeter walls and
        // four O10 screw pillars stand on the skin; the rest is open downward
        difference() {
            translate([SX0 + 3, SY0 + 3, -1]) cube([SX1 - SX0 - 6, SY1 - SY0 - 6, ZB - 4 + 1]);
            for (b = SADDLE_BOSS) translate([b[0], b[1], -2]) cylinder(h = ZB, d = 10);
        }
        // underside follows the bore; merge_middle_interior.py trims to the real skin
        difference() {
            translate([SX0 - 1, SY0 - 2, -1]) cube([SX1 - SX0 + 2, SY1 - SY0 + 4, ZB]);
            bore_cylinder(AFT_NECK_R - EPS);
        }
    }
}

saddle_body();
