##
## uxrclient.cmake — vendored Micro XRCE-DDS Client + Micro-CDR
##
## Author:  Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
## Drafted by: Claude Opus 5 (Anthropic), 2026-07-28
## License: CC BY 4.0 — creativecommons.org/licenses/by/4.0
##
## Upstream (both eProsima, Apache-2.0):
##   Micro-XRCE-DDS-Client v3.0.1  9e2941051bb9fb2fb47bd6e801013506c0d2688d
##   Micro-CDR             v2.0.2  be22d10102447fb2ab6e701fee453ca0b2b0ccf6
##
## Upstream sources are compiled directly into one static library here rather
## than through eProsima's own CMake project.  Three reasons, all of which
## matter for a 128 KB bare-metal target:
##
##   1. The upstream project's superbuild resolves Micro-CDR through
##      find_package, which needs an install prefix that does not exist in a
##      cross build.
##   2. Compiling the sources directly lets the file list be exactly the
##      profiles this firmware uses — no UDP, TCP, serial, discovery or
##      logging code linked in and then garbage-collected.
##   3. The two generated config headers are written here, so the embedded
##      configuration is visible in this repository instead of buried in a
##      cache variable.
##
## Nothing in the eProsima tree is patched.  The pins are commit hashes, not
## tags, so a retagged upstream cannot silently change what was verified.
##

include(FetchContent)

## SOURCE_SUBDIR names a directory that does not exist, which makes
## FetchContent download the sources without running upstream's CMakeLists.
FetchContent_Declare(microcdr
    GIT_REPOSITORY https://github.com/eProsima/Micro-CDR.git
    GIT_TAG        be22d10102447fb2ab6e701fee453ca0b2b0ccf6
    SOURCE_SUBDIR  no-cmake-here)
FetchContent_Declare(uxrclient
    GIT_REPOSITORY https://github.com/eProsima/Micro-XRCE-DDS-Client.git
    GIT_TAG        9e2941051bb9fb2fb47bd6e801013506c0d2688d
    SOURCE_SUBDIR  no-cmake-here)
FetchContent_MakeAvailable(microcdr uxrclient)

set(UXR_GEN "${CMAKE_CURRENT_BINARY_DIR}/uxr_generated")
file(MAKE_DIRECTORY "${UXR_GEN}/ucdr" "${UXR_GEN}/uxr/client")

## ---------------------------------------------------------------------------
## ucdr/config.h
##
## UCDR_MACHINE_ENDIANNESS 0 is little-endian, which is what Cortex-M0+ runs
## and what every host this builds on runs.
## ---------------------------------------------------------------------------
file(WRITE "${UXR_GEN}/ucdr/config.h"
"/* Generated by cmake/uxrclient.cmake — do not edit. */\n"
"#ifndef _MICROCDR_CONFIG_H_\n"
"#define _MICROCDR_CONFIG_H_\n"
"#define MICROCDR_VERSION_MAJOR 2\n"
"#define MICROCDR_VERSION_MINOR 0\n"
"#define MICROCDR_VERSION_MICRO 2\n"
"#define MICROCDR_VERSION_STR \"2.0.2\"\n"
"#define UCDR_MACHINE_ENDIANNESS 0\n"
"#endif\n")

## ---------------------------------------------------------------------------
## uxr/client/config.h
##
## Only the custom transport and stream framing are enabled.  The custom
## transport MTU is the CAN-FD ceiling (64-byte data field less the one-byte
## length prefix) so that one MTU serves every bearer and failover needs no
## reconfiguration — see template/include/serenity/link.h.
## ---------------------------------------------------------------------------
file(WRITE "${UXR_GEN}/uxr/client/config.h"
"/* Generated by cmake/uxrclient.cmake — do not edit. */\n"
"#ifndef _UXR_CLIENT_CONFIG_H_\n"
"#define _UXR_CLIENT_CONFIG_H_\n"
"#define UXR_CLIENT_VERSION_MAJOR 3\n"
"#define UXR_CLIENT_VERSION_MINOR 0\n"
"#define UXR_CLIENT_VERSION_MICRO 1\n"
"#define UXR_CLIENT_VERSION_STR \"3.0.1\"\n"
"#define UCLIENT_PROFILE_CUSTOM_TRANSPORT\n"
"#define UCLIENT_PROFILE_STREAM_FRAMING\n"
"#define UCLIENT_TWEAK_XRCE_WRITE_LIMIT\n"
"#define UXR_CONFIG_CUSTOM_TRANSPORT_MTU ${SERENITY_UXR_MTU}\n"
"#define UXR_CONFIG_MAX_OUTPUT_BEST_EFFORT_STREAMS 1\n"
"#define UXR_CONFIG_MAX_OUTPUT_RELIABLE_STREAMS 1\n"
"#define UXR_CONFIG_MAX_INPUT_BEST_EFFORT_STREAMS 1\n"
"#define UXR_CONFIG_MAX_INPUT_RELIABLE_STREAMS 1\n"
"#define UXR_CONFIG_MAX_SESSION_CONNECTION_ATTEMPTS 10\n"
"#define UXR_CONFIG_MIN_SESSION_CONNECTION_INTERVAL 1000\n"
"#define UXR_CONFIG_MIN_HEARTBEAT_TIME_INTERVAL 100\n"
"#endif\n")

add_library(uxrclient STATIC
    ${microcdr_SOURCE_DIR}/src/c/common.c
    ${microcdr_SOURCE_DIR}/src/c/types/basic.c
    ${microcdr_SOURCE_DIR}/src/c/types/string.c
    ${microcdr_SOURCE_DIR}/src/c/types/array.c
    ${microcdr_SOURCE_DIR}/src/c/types/sequence.c

    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/input_best_effort_stream.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/input_reliable_stream.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/output_best_effort_stream.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/output_reliable_stream.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/stream_storage.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/stream_id.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/stream/seq_num.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/session.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/session_info.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/submessage.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/object_id.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/common_create_entities.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/create_entities_ref.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/create_entities_xml.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/create_entities_bin.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/read_access.c
    ${uxrclient_SOURCE_DIR}/src/c/core/session/write_access.c
    ${uxrclient_SOURCE_DIR}/src/c/core/serialization/xrce_types.c
    ${uxrclient_SOURCE_DIR}/src/c/core/serialization/xrce_header.c
    ${uxrclient_SOURCE_DIR}/src/c/core/serialization/xrce_subheader.c
    ${uxrclient_SOURCE_DIR}/src/c/util/time.c
    ${uxrclient_SOURCE_DIR}/src/c/util/ping.c
    ${uxrclient_SOURCE_DIR}/src/c/profile/transport/custom/custom_transport.c
    ${uxrclient_SOURCE_DIR}/src/c/profile/transport/stream_framing/stream_framing_protocol.c
)

target_include_directories(uxrclient SYSTEM PUBLIC
    "${UXR_GEN}"
    "${uxrclient_SOURCE_DIR}/include"
    "${microcdr_SOURCE_DIR}/include"
)
target_include_directories(uxrclient PRIVATE
    "${uxrclient_SOURCE_DIR}/src/c"
)

## Third-party code is held to its own standards, not this project's; its
## warnings must not fail our build.
target_compile_options(uxrclient PRIVATE -w)
set_target_properties(uxrclient PROPERTIES C_STANDARD 99)

## upstream `util/time.c` calls clock_gettime(CLOCK_REALTIME, ...) with only
## <time.h> included, which C99's strict mode hides.  The macro that exposes
## the declaration differs by C library, and getting it wrong is silent: the
## call compiles as an implicit int-returning function and the session clock
## reads garbage.  glibc wants _POSIX_C_SOURCE; newlib (arm-none-eabi) gates
## it on _POSIX_TIMERS instead, and defining _POSIX_C_SOURCE there actually
## *hides* it again.  Verified on both toolchains rather than assumed.
##
## The symbol itself is supplied by hal/mspm0/syscalls.c on bare metal,
## backed by ser_hal_time_ns().  Either way upstream stays unpatched.
if(CMAKE_SYSTEM_NAME STREQUAL "Generic")
    target_compile_definitions(uxrclient PRIVATE _POSIX_TIMERS=1)
else()
    target_compile_definitions(uxrclient PRIVATE _POSIX_C_SOURCE=200809L)
endif()
