"""
blender_shells_v3_2mm.py  —  run with:
    blender --background --python blender_shells_v3_2mm.py

Generates 2.0 mm wall hollow shells for the Serenity UAV fuselage sections
that will be foam-filled (2 lb/cf low-density closed-cell foam).

Structural analysis (2026-05-26) established that 2.0 mm CF-PETG with foam
fill is adequate for skin-only panels:
  - Panel deflection at 28 m/s cruise: 0.054 mm (foam-supported, vs 1.08 mm
    without foam) — well within the 0.5 mm target.
  - Boss walls and section joint zones retain 2.5 mm walls via SCAD union
    bosses; these are NOT generated by this script.
  - Reference: structural_analysis.py log, Serenity UAV project, 2026-05-26.

Scope: fuselage hull sections only (head, cargo, rear, middle, wings).
Nacelle shells remain at 2.5 mm (blender_shells_v3_50mm.py) because the
interior bore cavity between EDF housing and nacelle wall is only ~4 mm —
reducing further would risk CGAL merge during voxel-remesh repair.

Changes from blender_shells_v3_50mm.py (v3):
  - WALL_MM: 2.5 → 2.0  (foam-fill skin thickness)
  - SCALE unchanged at 2.9294 × (24" target; NO 1.25× nacelle multiplier)
  - HOLLOW_PARTS: fuselage sections only (no nacelles)
  - SCALE_ONLY_PARTS: not processed (articulation parts unchanged)
  - Output suffix: _shell24_2mm.stl (distinct from existing _shell24.stl)

Minimum-dimension check:
    s_head:       min_dim ≈  88 mm → 4 × 2.0 = 8 mm threshold → hollow ✓
    s_cargo_sect: min_dim ≈ 102 mm → hollow ✓
    s_rear:       min_dim ≈  76 mm → hollow ✓
    s_middle:     min_dim ≈  60 mm → hollow ✓
    s_wings_both: min_dim ≈  19 mm → 4 × 2.0 = 8 mm → hollow (19 > 8) ✓
    (Wings min_dim 19 mm gives 9.5 mm interior at 2.0 mm walls — adequate for foam fill)

Author:  Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
License: CC BY 4.0  <https://creativecommons.org/licenses/by/4.0/>
Date:    2026-05-26

References:
    blender_shells_v3_50mm.py — parent script (2.5 mm, with nacelle 1.25× scale)
    blender_shells_v3.py      — grandparent (2.5 mm, 24" scale only)
    Structural adequacy analysis: UAV structural_analysis log 2026-05-26.
"""

import bpy
import os

WALL_MM   = 2.0        # [mm] foam-fill skin wall thickness
TARGET_IN = 24.0       # [in] target build size
SCALE_X   = 2.9294     # uniform 24" scale from 18" native Thingiverse model
SCALE_Y   = 2.9294
SCALE_Z   = 2.9294

BASE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(BASE, "files")
OUT  = os.path.join(BASE, "files-hollowed-18in")
os.makedirs(OUT, exist_ok=True)

# Fuselage hull sections to hollow at 2.0 mm.
# Nacelles omitted — see docstring.
HOLLOW_PARTS = [
    "s_head.stl",
    "s_cargo_sect.stl",
    "s_rear.stl",
    "s_middle.stl",
    "s_wings_both.stl",
]


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()


def import_stl(path):
    bpy.ops.wm.stl_import(filepath=path)
    return bpy.context.selected_objects[0]


def export_stl(obj, path):
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.wm.stl_export(filepath=path, export_selected_objects=True)


def process_hollow(fname):
    """
    Scale, hollow (outer shell + inner shell with flipped normals), join, export.

    Uses centroid-inset scaling identical to blender_shells_v3.py / v3_50mm.py.
    Output suffix is _shell24_2mm.stl to distinguish from existing _shell24.stl.
    """
    src  = os.path.join(SRC, fname)
    stem = fname.replace(".stl", "")
    out  = os.path.join(OUT, stem + "_shell24_2mm.stl")

    if not os.path.isfile(src):
        print(f"  SKIP — not found: {src}")
        return

    print(f"\n=== Processing {fname} ===")

    clear_scene()
    outer = import_stl(src)
    outer.name = "outer"

    # Uniform scale to 24" target
    outer.scale = (SCALE_X, SCALE_Y, SCALE_Z)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    dx, dy, dz = outer.dimensions
    min_dim = min(dx, dy, dz)
    print(f"  Dimensions after scale: {dx:.1f} × {dy:.1f} × {dz:.1f} mm  "
          f"(min={min_dim:.1f} mm)")

    if min_dim < 4 * WALL_MM:
        # Part is too thin to hollow — export solid
        print(f"  min_dim {min_dim:.1f} mm < {4*WALL_MM:.1f} mm threshold — exporting solid")
        export_stl(outer, out)
        sz = os.path.getsize(out) / 1024
        print(f"  → {os.path.basename(out)}  ({sz:.0f} KB, solid)")
        return

    # Centroid-inset scale factors for uniform 2.0 mm wall
    sx  = max(0.001, (dx - 2 * WALL_MM) / dx)
    sy  = max(0.001, (dy - 2 * WALL_MM) / dy)
    sz_ = max(0.001, (dz - 2 * WALL_MM) / dz)
    print(f"  Inner scale factors: sx={sx:.6f}  sy={sy:.6f}  sz={sz_:.6f}")

    # Bounding-box centroid (object space)
    bmin = [outer.bound_box[0][i] for i in range(3)]
    bmax = [outer.bound_box[6][i] for i in range(3)]
    cx = (bmin[0] + bmax[0]) / 2
    cy = (bmin[1] + bmax[1]) / 2
    cz = (bmin[2] + bmax[2]) / 2

    # Duplicate to make inner shell
    bpy.ops.object.select_all(action="DESELECT")
    outer.select_set(True)
    bpy.context.view_layer.objects.active = outer
    bpy.ops.object.duplicate()
    inner = bpy.context.selected_objects[0]
    inner.name = "inner"

    # Translate to centroid → scale inward → translate back
    inner.location = (inner.location.x - cx,
                      inner.location.y - cy,
                      inner.location.z - cz)
    bpy.ops.object.transform_apply(location=True)
    inner.scale = (sx, sy, sz_)
    bpy.ops.object.transform_apply(scale=True)
    inner.location = (cx, cy, cz)
    bpy.ops.object.transform_apply(location=True)

    # Flip normals on inner shell so it faces inward
    bpy.context.view_layer.objects.active = inner
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.mesh.flip_normals()
    bpy.ops.object.mode_set(mode="OBJECT")

    # Join outer + inner into one object
    outer.select_set(True)
    inner.select_set(True)
    bpy.context.view_layer.objects.active = outer
    bpy.ops.object.join()
    joined = bpy.context.active_object

    export_stl(joined, out)
    sz = os.path.getsize(out) / 1024
    print(f"  → {os.path.basename(out)}  ({sz:.0f} KB)")


print(f"\nScale: {SCALE_X:.4f}×  Wall: {WALL_MM} mm  Target: {TARGET_IN}\"\n")
print("=== Hollow fuselage sections at 2.0 mm wall ===")
for f in HOLLOW_PARTS:
    if os.path.exists(os.path.join(SRC, f)):
        process_hollow(f)
    else:
        print(f"  SKIP — source not found: {f}")

print(f"\nDone.  Output files in {OUT}")
print("Next step: run repair_shells_for_scad.py to voxel-remesh the *_2mm.stl files.")
print("Then update serenity/stl/*.scad to import the *_2mm_repaired.stl versions.")
