#!/usr/bin/env python3
"""sync_wash_pcb_nets.py — Push verified nets from the schematic onto Wash.kicad_pcb.

The schematic-first rebuild (``kicads/Wash.kicad_sch``, generated by
``gen_wash_sch.py``) is authoritative.  This script copies its (ref, pad) -> net
map onto the board **without touching footprint placement**, which is the user's
manual packing (root ``AGENTS.md`` / ``avionics/AGENTS.md``).

Only footprints whose pad set matches the schematic symbol's pin set exactly are
synced.  Refs still carrying the wrong land pattern are listed in
``BLOCKED_WRONG_FOOTPRINT`` and are skipped, because writing a 20-pin part's nets
onto a 16-pad land would silently mis-assign every pad.  They are synced once the
footprint is replaced.

What this fixes on the board (all verified against the OEM datasheets in
``avionics/datasheets/``):
  * SRF2012 common-mode chokes had the SAME net on both ends of each winding and
    the pair swapped across the package, i.e. the choke SHORTED CAN_H to CAN_L
    (and RS485_A to RS485_B).  Datasheet SRF2012A.pdf gives windings 1-2 / 4-3.
  * FB1 ferrite bead had +5V on both pads — the bead was shorted out.  Now
    PWR-IN -> +5V_IN -> FB1 -> +5V per Wash.md §6.
  * The RS-485 transceiver's bus pins (Y/Z/B/A) carried no net at all while
    signals sat on GNDIO/VDD/GND2.
  * The 1553 driver had M1553_TX_N on its VCC pin and host PRU signals on driver
    outputs.
  * The IMU's SPI map was scrambled (MOSI on the SDO output, MISO on VDDIO).

Usage:  python3 sync_wash_pcb_nets.py [--dry-run]

Author: Claude (Opus 5), 2026-07-28.  License: CC BY 4.0.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCH = HERE.parent / "kicads" / "Wash.kicad_sch"
PCB = HERE.parent / "kicads" / "Wash.kicad_pcb"

# Refs whose PCB land pattern does not match the real part (WBS.md §1.2a).
# Footprint replacement + re-placement is a user action; skip until then.
BLOCKED_WRONG_FOOTPRINT = {
    "CAN-TR",      # ISOW1044BDFMR is 20-pin DFM; board has 16-pad SOIC-16W
    "ETH1-PHY",    # ADIN1300BCPZ is 40-LFCSP CP-40-26; board has QFN-48
    "ETH2-PHY",
    "BARO",        # BMP388 is 10-pin LGA 2.0x2.0; board has 8-pad LGA
    "GPS",         # board has a 2-pad placeholder blob
    "1553-XFM",    # board has a 2-pad placeholder blob; SM1553 is 8-pin
    "T-ETH",       # Wuerth 749010012A is 12-pin; board has 8-pad land
    "T-ETH2",
}

# Removed from the design: RMII galvanic isolation now lives in the Ethernet
# magnetics, not in digital isolators on the 50 MHz RMII bus (see the
# adin1300() docstring in gen_wash_sch.py and WBS.md §1.2a).
OBSOLETE_REFS = {"U-ISO-TX", "U-ISO-RX"}


def sexp_block(src: str, start: int) -> str:
    """Return the balanced-paren block beginning at ``start``."""
    depth = 0
    i = start
    instr = False
    while i < len(src):
        c = src[i]
        if instr:
            if c == "\\":
                i += 2
                continue
            if c == '"':
                instr = False
        elif c == '"':
            instr = True
        elif c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return src[start : i + 1]
        i += 1
    raise ValueError("unbalanced s-expression")


def schematic_netmap() -> dict[tuple[str, str], str]:
    """(ref, pad) -> net name, exported from the authoritative schematic."""
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "wash.xml"
        subprocess.run(
            ["kicad-cli", "sch", "export", "netlist", "-o", str(out),
             "--format", "kicadxml", str(SCH)],
            check=True, capture_output=True,
        )
        root = ET.parse(out).getroot()
    netmap: dict[tuple[str, str], str] = {}
    for net in root.iter("net"):
        name = net.get("name") or ""
        if not name:
            continue
        for node in net.findall("node"):
            netmap[(node.get("ref"), node.get("pin"))] = name
    return netmap


def main() -> int:
    dry = "--dry-run" in sys.argv
    src = PCB.read_text()
    netmap = schematic_netmap()

    # --- collect the net table currently on the board --------------------
    name_to_num: dict[str, int] = {}
    for m in re.finditer(r'\(net (\d+) "([^"]*)"\)', src):
        num, name = int(m.group(1)), m.group(2)
        if name and name not in name_to_num:
            name_to_num[name] = num
    next_num = max([int(m.group(1)) for m in re.finditer(r'\(net (\d+) "', src)] or [0]) + 1

    for name in sorted({n for n in netmap.values()}):
        if name not in name_to_num:
            name_to_num[name] = next_num
            next_num += 1

    # --- walk footprints, rewriting pad nets -----------------------------
    out = []
    pos = 0
    synced: dict[str, int] = {}
    skipped: list[str] = []
    removed: list[str] = []

    for fm in re.finditer(r"\(footprint ", src):
        if fm.start() < pos:
            continue
        block = sexp_block(src, fm.start())
        refm = re.search(r'\(property "Reference" "([^"]+)"', block)
        ref = refm.group(1) if refm else None
        out.append(src[pos : fm.start()])
        pos = fm.start() + len(block)

        if ref in OBSOLETE_REFS:
            removed.append(ref)
            continue  # drop the footprint entirely
        if ref is None or ref in BLOCKED_WRONG_FOOTPRINT or ref not in {r for r, _ in netmap}:
            if ref in BLOCKED_WRONG_FOOTPRINT:
                skipped.append(ref)
            out.append(block)
            continue

        count = 0

        def fix_pad(pm: re.Match) -> str:
            nonlocal count
            padblock = sexp_block(block, pm.start())
            pnum = re.match(r'\(pad "([^"]*)"', padblock).group(1)
            if not pnum.strip():
                return padblock
            net = netmap.get((ref, pnum))
            new_net = (
                f'(net {name_to_num[net]} "{net}")' if net else None
            )
            if re.search(r'\(net \d+ "[^"]*"\)', padblock):
                if new_net:
                    padblock = re.sub(r'\(net \d+ "[^"]*"\)', new_net, padblock, count=1)
                else:
                    padblock = re.sub(r'\s*\(net \d+ "[^"]*"\)', "", padblock, count=1)
                count += 1
            elif new_net:
                padblock = padblock[:-1].rstrip() + f"\n\t\t\t{new_net}\n\t\t)"
                count += 1
            return padblock

        newblock, ppos, chunks = block, 0, []
        for pm in re.finditer(r"\(pad ", block):
            if pm.start() < ppos:
                continue
            padblock = sexp_block(block, pm.start())
            chunks.append(block[ppos : pm.start()])
            chunks.append(fix_pad(pm))
            ppos = pm.start() + len(padblock)
        chunks.append(block[ppos:])
        out.append("".join(chunks))
        synced[ref] = count

    out.append(src[pos:])
    result = "".join(out)

    # --- rewrite the board-level net table -------------------------------
    # Line-based: find the contiguous run of top-level `(net N "...")`
    # declarations and replace it wholesale.  (A regex with a repeated group
    # here silently matches zero repetitions and duplicates the table.)
    lines = result.split("\n")
    net_line = re.compile(r'^\t\(net \d+ "[^"]*"\)$')
    first = last = None
    for i, ln in enumerate(lines):
        if net_line.match(ln):
            if first is None:
                first = i
            last = i
        elif first is not None:
            break
    if first is None:
        raise SystemExit("could not locate the board net table")
    table = [
        f'\t(net {num} "{name}")'
        for name, num in sorted(name_to_num.items(), key=lambda kv: kv[1])
    ]
    if not any(n == 0 for n in name_to_num.values()):
        table.insert(0, '\t(net 0 "")')
    lines[first : last + 1] = table
    result = "\n".join(lines)

    print(f"synced {len(synced)} footprints, {sum(synced.values())} pads")
    if removed:
        print(f"removed obsolete footprints: {sorted(removed)}")
    print(f"skipped (wrong land, awaiting footprint replacement): {sorted(set(skipped))}")
    if dry:
        print("--dry-run: no file written")
        return 0
    PCB.write_text(result)
    print(f"wrote {PCB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
