# OBD2 DTC code database — SAE J2012 generic codes
# decode_dtc(b1, b2) → (code_str, description)
# Covers P0/P2, B0/B1, C0, U0 generic ranges.

_CODES = {
    # ── Camshaft / VVT ────────────────────────────────────────────────────────
    "P0010":"Intake Camshaft Position Actuator Circuit Open (Bank 1)",
    "P0011":"Intake Camshaft Timing Over-Advanced/System Performance (Bank 1)",
    "P0012":"Intake Camshaft Timing Over-Retarded (Bank 1)",
    "P0013":"Exhaust Camshaft Position Actuator Circuit Open (Bank 1)",
    "P0014":"Exhaust Camshaft Timing Over-Advanced/System Performance (Bank 1)",
    "P0015":"Exhaust Camshaft Timing Over-Retarded (Bank 1)",
    "P0016":"Crank/Cam Position Correlation Bank 1 Sensor A",
    "P0017":"Crank/Cam Position Correlation Bank 1 Sensor B",
    "P0018":"Crank/Cam Position Correlation Bank 2 Sensor A",
    "P0019":"Crank/Cam Position Correlation Bank 2 Sensor B",
    "P0020":"Intake Camshaft Position Actuator Circuit Open (Bank 2)",
    "P0021":"Intake Camshaft Timing Over-Advanced/System Performance (Bank 2)",
    "P0022":"Intake Camshaft Timing Over-Retarded (Bank 2)",
    "P0023":"Exhaust Camshaft Position Actuator Circuit Open (Bank 2)",
    "P0024":"Exhaust Camshaft Timing Over-Advanced/System Performance (Bank 2)",
    "P0025":"Exhaust Camshaft Timing Over-Retarded (Bank 2)",
    # ── O2 Heaters ───────────────────────────────────────────────────────────
    "P0030":"HO2S Heater Control Circuit (Bank 1 Sensor 1)",
    "P0031":"HO2S Heater Control Circuit Low (Bank 1 Sensor 1)",
    "P0032":"HO2S Heater Control Circuit High (Bank 1 Sensor 1)",
    "P0036":"HO2S Heater Control Circuit (Bank 1 Sensor 2)",
    "P0037":"HO2S Heater Control Circuit Low (Bank 1 Sensor 2)",
    "P0038":"HO2S Heater Control Circuit High (Bank 1 Sensor 2)",
    "P0050":"HO2S Heater Control Circuit (Bank 2 Sensor 1)",
    "P0051":"HO2S Heater Control Circuit Low (Bank 2 Sensor 1)",
    "P0052":"HO2S Heater Control Circuit High (Bank 2 Sensor 1)",
    "P0053":"HO2S Heater Resistance (Bank 1 Sensor 1)",
    "P0054":"HO2S Heater Resistance (Bank 1 Sensor 2)",
    "P0056":"HO2S Heater Control Circuit (Bank 2 Sensor 2)",
    "P0057":"HO2S Heater Control Circuit Low (Bank 2 Sensor 2)",
    "P0058":"HO2S Heater Control Circuit High (Bank 2 Sensor 2)",
    "P0068":"MAP/MAF — Throttle Position Correlation",
    # ── Fuel System ───────────────────────────────────────────────────────────
    "P0087":"Fuel Rail/System Pressure Too Low",
    "P0088":"Fuel Rail/System Pressure Too High",
    "P0089":"Fuel Pressure Regulator 1 Performance",
    "P0093":"Fuel System Leak Detected — Large Leak",
    "P0094":"Fuel System Leak Detected — Small Leak",
    # ── Air Flow / MAP ────────────────────────────────────────────────────────
    "P0100":"Mass/Volume Air Flow Circuit Malfunction",
    "P0101":"Mass/Volume Air Flow Circuit Range/Performance",
    "P0102":"Mass/Volume Air Flow Circuit Low",
    "P0103":"Mass/Volume Air Flow Circuit High",
    "P0104":"Mass/Volume Air Flow Circuit Intermittent",
    "P0105":"MAP/Barometric Pressure Circuit Malfunction",
    "P0106":"MAP/Barometric Pressure Circuit Range/Performance",
    "P0107":"MAP/Barometric Pressure Circuit Low",
    "P0108":"MAP/Barometric Pressure Circuit High",
    # ── Intake Air Temperature ────────────────────────────────────────────────
    "P0110":"Intake Air Temperature Circuit Malfunction",
    "P0112":"Intake Air Temperature Circuit Low",
    "P0113":"Intake Air Temperature Circuit High",
    # ── Engine Coolant Temperature ────────────────────────────────────────────
    "P0115":"Engine Coolant Temperature Circuit Malfunction",
    "P0116":"Engine Coolant Temperature Circuit Range/Performance",
    "P0117":"Engine Coolant Temperature Circuit Low",
    "P0118":"Engine Coolant Temperature Circuit High",
    "P0125":"Insufficient Coolant Temperature for Closed Loop Fuel Control",
    "P0128":"Coolant Temperature Below Thermostat Regulating Temperature",
    # ── Throttle Position ─────────────────────────────────────────────────────
    "P0120":"Throttle/Pedal Position Sensor A Circuit Malfunction",
    "P0121":"Throttle/Pedal Position Sensor A Range/Performance",
    "P0122":"Throttle/Pedal Position Sensor A Circuit Low",
    "P0123":"Throttle/Pedal Position Sensor A Circuit High",
    "P0220":"Throttle/Pedal Position Sensor B Circuit Malfunction",
    "P0221":"Throttle/Pedal Position Sensor B Range/Performance",
    "P0222":"Throttle/Pedal Position Sensor B Circuit Low",
    "P0223":"Throttle/Pedal Position Sensor B Circuit High",
    # ── Oxygen Sensors ────────────────────────────────────────────────────────
    "P0130":"O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)",
    "P0131":"O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)",
    "P0132":"O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)",
    "P0133":"O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)",
    "P0134":"O2 Sensor Circuit No Activity (Bank 1 Sensor 1)",
    "P0135":"O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)",
    "P0136":"O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)",
    "P0137":"O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)",
    "P0138":"O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)",
    "P0139":"O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)",
    "P0140":"O2 Sensor Circuit No Activity (Bank 1 Sensor 2)",
    "P0141":"O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)",
    "P0150":"O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)",
    "P0151":"O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)",
    "P0152":"O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)",
    "P0153":"O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)",
    "P0154":"O2 Sensor Circuit No Activity (Bank 2 Sensor 1)",
    "P0155":"O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)",
    "P0156":"O2 Sensor Circuit Malfunction (Bank 2 Sensor 2)",
    "P0157":"O2 Sensor Circuit Low Voltage (Bank 2 Sensor 2)",
    "P0158":"O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)",
    "P0159":"O2 Sensor Circuit Slow Response (Bank 2 Sensor 2)",
    "P0160":"O2 Sensor Circuit No Activity (Bank 2 Sensor 2)",
    "P0161":"O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)",
    # ── Fuel Trim ─────────────────────────────────────────────────────────────
    "P0170":"Fuel Trim Malfunction (Bank 1)",
    "P0171":"System Too Lean (Bank 1)",
    "P0172":"System Too Rich (Bank 1)",
    "P0173":"Fuel Trim Malfunction (Bank 2)",
    "P0174":"System Too Lean (Bank 2)",
    "P0175":"System Too Rich (Bank 2)",
    # ── Fuel Rail ─────────────────────────────────────────────────────────────
    "P0191":"Fuel Rail Pressure Sensor Circuit Range/Performance",
    "P0192":"Fuel Rail Pressure Sensor Circuit Low",
    "P0193":"Fuel Rail Pressure Sensor Circuit High",
    "P0195":"Engine Oil Temperature Sensor Malfunction",
    "P0197":"Engine Oil Temperature Sensor Low",
    "P0198":"Engine Oil Temperature Sensor High",
    # ── Injectors ─────────────────────────────────────────────────────────────
    "P0200":"Injector Circuit Malfunction",
    "P0201":"Injector Circuit Malfunction — Cylinder 1",
    "P0202":"Injector Circuit Malfunction — Cylinder 2",
    "P0203":"Injector Circuit Malfunction — Cylinder 3",
    "P0204":"Injector Circuit Malfunction — Cylinder 4",
    "P0205":"Injector Circuit Malfunction — Cylinder 5",
    "P0206":"Injector Circuit Malfunction — Cylinder 6",
    "P0207":"Injector Circuit Malfunction — Cylinder 7",
    "P0208":"Injector Circuit Malfunction — Cylinder 8",
    "P0217":"Engine Overtemperature Condition",
    "P0218":"Transmission Over Temperature Condition",
    "P0219":"Engine Overspeed Condition",
    # ── Fuel Pump ─────────────────────────────────────────────────────────────
    "P0230":"Fuel Pump Primary Circuit Malfunction",
    "P0231":"Fuel Pump Secondary Circuit Low",
    "P0232":"Fuel Pump Secondary Circuit High",
    # ── Turbo ─────────────────────────────────────────────────────────────────
    "P0234":"Turbocharger/Supercharger Overboost Condition",
    "P0235":"Turbocharger Boost Sensor A Circuit Malfunction",
    "P0236":"Turbocharger Boost Sensor A Circuit Range/Performance",
    "P0237":"Turbocharger Boost Sensor A Circuit Low",
    "P0238":"Turbocharger Boost Sensor A Circuit High",
    "P0243":"Turbocharger Wastegate Solenoid A Malfunction",
    # ── Misfires ──────────────────────────────────────────────────────────────
    "P0300":"Random/Multiple Cylinder Misfire Detected",
    "P0301":"Cylinder 1 Misfire Detected",
    "P0302":"Cylinder 2 Misfire Detected",
    "P0303":"Cylinder 3 Misfire Detected",
    "P0304":"Cylinder 4 Misfire Detected",
    "P0305":"Cylinder 5 Misfire Detected",
    "P0306":"Cylinder 6 Misfire Detected",
    "P0307":"Cylinder 7 Misfire Detected",
    "P0308":"Cylinder 8 Misfire Detected",
    "P0316":"Misfire Detected on Startup (First 1000 Revolutions)",
    # ── Knock ─────────────────────────────────────────────────────────────────
    "P0324":"Knock Control System Error",
    "P0325":"Knock Sensor 1 Circuit Malfunction (Bank 1)",
    "P0326":"Knock Sensor 1 Circuit Range/Performance (Bank 1)",
    "P0327":"Knock Sensor 1 Circuit Low (Bank 1)",
    "P0328":"Knock Sensor 1 Circuit High (Bank 1)",
    "P0330":"Knock Sensor 2 Circuit Malfunction (Bank 2)",
    "P0332":"Knock Sensor 2 Circuit Low (Bank 2)",
    "P0333":"Knock Sensor 2 Circuit High (Bank 2)",
    # ── Crank / Cam Sensors ───────────────────────────────────────────────────
    "P0335":"Crankshaft Position Sensor A Circuit Malfunction",
    "P0336":"Crankshaft Position Sensor A Circuit Range/Performance",
    "P0337":"Crankshaft Position Sensor A Circuit Low",
    "P0338":"Crankshaft Position Sensor A Circuit High",
    "P0339":"Crankshaft Position Sensor A Circuit Intermittent",
    "P0340":"Camshaft Position Sensor A Circuit Malfunction (Bank 1)",
    "P0341":"Camshaft Position Sensor A Circuit Range/Performance (Bank 1)",
    "P0342":"Camshaft Position Sensor A Circuit Low (Bank 1)",
    "P0343":"Camshaft Position Sensor A Circuit High (Bank 1)",
    "P0344":"Camshaft Position Sensor A Circuit Intermittent (Bank 1)",
    "P0345":"Camshaft Position Sensor A Circuit Malfunction (Bank 2)",
    # ── Ignition Coils ────────────────────────────────────────────────────────
    "P0350":"Ignition Coil Primary/Secondary Circuit Malfunction",
    "P0351":"Ignition Coil A Primary/Secondary Circuit Malfunction",
    "P0352":"Ignition Coil B Primary/Secondary Circuit Malfunction",
    "P0353":"Ignition Coil C Primary/Secondary Circuit Malfunction",
    "P0354":"Ignition Coil D Primary/Secondary Circuit Malfunction",
    "P0355":"Ignition Coil E Primary/Secondary Circuit Malfunction",
    "P0356":"Ignition Coil F Primary/Secondary Circuit Malfunction",
    "P0357":"Ignition Coil G Primary/Secondary Circuit Malfunction",
    "P0358":"Ignition Coil H Primary/Secondary Circuit Malfunction",
    # ── EGR ───────────────────────────────────────────────────────────────────
    "P0400":"EGR Flow Malfunction",
    "P0401":"EGR Flow Insufficient Detected",
    "P0402":"EGR Flow Excessive Detected",
    "P0403":"EGR Circuit Malfunction",
    "P0404":"EGR Circuit Range/Performance",
    "P0405":"EGR Sensor A Circuit Low",
    "P0406":"EGR Sensor A Circuit High",
    # ── Catalytic Converter ───────────────────────────────────────────────────
    "P0420":"Catalyst System Efficiency Below Threshold (Bank 1)",
    "P0421":"Warm-Up Catalyst Efficiency Below Threshold (Bank 1)",
    "P0422":"Main Catalyst Efficiency Below Threshold (Bank 1)",
    "P0430":"Catalyst System Efficiency Below Threshold (Bank 2)",
    "P0431":"Warm-Up Catalyst Efficiency Below Threshold (Bank 2)",
    "P0432":"Main Catalyst Efficiency Below Threshold (Bank 2)",
    # ── EVAP ──────────────────────────────────────────────────────────────────
    "P0440":"EVAP System Malfunction",
    "P0441":"EVAP System Incorrect Purge Flow",
    "P0442":"EVAP System Leak Detected (Small Leak)",
    "P0443":"EVAP Purge Control Valve Circuit Malfunction",
    "P0444":"EVAP Purge Control Valve Circuit Open",
    "P0445":"EVAP Purge Control Valve Circuit Shorted",
    "P0446":"EVAP Vent Control Circuit Malfunction",
    "P0450":"EVAP System Pressure Sensor Malfunction",
    "P0452":"EVAP System Pressure Sensor Low",
    "P0453":"EVAP System Pressure Sensor High",
    "P0455":"EVAP System Leak Detected (Gross Leak)",
    "P0456":"EVAP System Leak Detected (Very Small Leak)",
    "P0457":"EVAP System Leak Detected (Fuel Cap Loose/Off)",
    # ── Fuel Level ────────────────────────────────────────────────────────────
    "P0460":"Fuel Level Sensor Circuit Malfunction",
    "P0461":"Fuel Level Sensor Circuit Range/Performance",
    "P0462":"Fuel Level Sensor Circuit Low",
    "P0463":"Fuel Level Sensor Circuit High",
    # ── Cooling Fan ───────────────────────────────────────────────────────────
    "P0480":"Cooling Fan 1 Control Circuit Malfunction",
    "P0481":"Cooling Fan 2 Control Circuit Malfunction",
    # ── Vehicle Speed ─────────────────────────────────────────────────────────
    "P0500":"Vehicle Speed Sensor Malfunction",
    "P0501":"Vehicle Speed Sensor Range/Performance",
    "P0502":"Vehicle Speed Sensor Low",
    "P0503":"Vehicle Speed Sensor Intermittent/Erratic/High",
    # ── Idle Control ──────────────────────────────────────────────────────────
    "P0505":"Idle Control System Malfunction",
    "P0506":"Idle Control System RPM Lower Than Expected",
    "P0507":"Idle Control System RPM Higher Than Expected",
    # ── Oil Pressure ──────────────────────────────────────────────────────────
    "P0520":"Engine Oil Pressure Sensor/Switch Circuit Malfunction",
    "P0522":"Engine Oil Pressure Sensor/Switch Circuit Low",
    "P0523":"Engine Oil Pressure Sensor/Switch Circuit High",
    "P0524":"Engine Oil Pressure Too Low",
    # ── System Voltage ────────────────────────────────────────────────────────
    "P0562":"System Voltage Low",
    "P0563":"System Voltage High",
    # ── PCM/ECM ───────────────────────────────────────────────────────────────
    "P0600":"Serial Communication Link Malfunction",
    "P0601":"Internal Control Module Memory Checksum Error",
    "P0602":"Control Module Programming Error",
    "P0603":"Internal Control Module KAM Error",
    "P0604":"Internal Control Module RAM Error",
    "P0605":"Internal Control Module ROM Error",
    "P0606":"PCM Processor Fault",
    "P0607":"Control Module Performance",
    "P0627":"Fuel Pump Control Circuit Open",
    "P0628":"Fuel Pump Control Circuit Low",
    "P0629":"Fuel Pump Control Circuit High",
    "P0630":"VIN Not Programmed or Incompatible PCM/ECM",
    "P0638":"Throttle Actuator Control Range/Performance (Bank 1)",
    "P0641":"Sensor Reference Voltage A Circuit Open",
    "P0642":"Sensor Reference Voltage A Circuit Low",
    "P0643":"Sensor Reference Voltage A Circuit High",
    "P0650":"MIL Control Circuit Malfunction",
    "P0651":"Sensor Reference Voltage B Circuit Open",
    "P0652":"Sensor Reference Voltage B Circuit Low",
    "P0653":"Sensor Reference Voltage B Circuit High",
    # ── Transmission ──────────────────────────────────────────────────────────
    "P0700":"Transmission Control System Malfunction",
    "P0705":"Transmission Range Sensor Circuit Malfunction (PRNDL)",
    "P0706":"Transmission Range Sensor Circuit Range/Performance",
    "P0707":"Transmission Range Sensor Circuit Low",
    "P0708":"Transmission Range Sensor Circuit High",
    "P0710":"Transmission Fluid Temperature Sensor Circuit Malfunction",
    "P0712":"Transmission Fluid Temperature Sensor Circuit Low",
    "P0713":"Transmission Fluid Temperature Sensor Circuit High",
    "P0715":"Input/Turbine Speed Sensor Circuit Malfunction",
    "P0717":"Input/Turbine Speed Sensor Circuit No Signal",
    "P0720":"Output Speed Sensor Circuit Malfunction",
    "P0722":"Output Speed Sensor Circuit No Signal",
    "P0730":"Incorrect Gear Ratio",
    "P0731":"Gear 1 Incorrect Ratio",  "P0732":"Gear 2 Incorrect Ratio",
    "P0733":"Gear 3 Incorrect Ratio",  "P0734":"Gear 4 Incorrect Ratio",
    "P0735":"Gear 5 Incorrect Ratio",
    "P0740":"Torque Converter Clutch Circuit Malfunction",
    "P0741":"Torque Converter Clutch Circuit Stuck Off",
    "P0742":"Torque Converter Clutch Circuit Stuck On",
    "P0748":"Pressure Control Solenoid A Electrical",
    "P0750":"Shift Solenoid A Malfunction",
    "P0751":"Shift Solenoid A Performance or Stuck Off",
    "P0752":"Shift Solenoid A Stuck On",
    "P0753":"Shift Solenoid A Electrical",
    "P0755":"Shift Solenoid B Malfunction",
    "P0756":"Shift Solenoid B Performance or Stuck Off",
    "P0757":"Shift Solenoid B Stuck On",
    "P0758":"Shift Solenoid B Electrical",
    "P0760":"Shift Solenoid C Malfunction",
    "P0763":"Shift Solenoid C Electrical",
    "P0765":"Shift Solenoid D Malfunction",
    "P0770":"Shift Solenoid E Malfunction",
    "P0780":"Shift Malfunction",
    "P0781":"1-2 Shift Malfunction",   "P0782":"2-3 Shift Malfunction",
    "P0783":"3-4 Shift Malfunction",   "P0784":"4-5 Shift Malfunction",
    # ── P2xxx — Second-gen SAE codes ──────────────────────────────────────────
    "P2096":"Post-Catalyst Fuel Trim Too Lean (Bank 1)",
    "P2097":"Post-Catalyst Fuel Trim Too Rich (Bank 1)",
    "P2098":"Post-Catalyst Fuel Trim Too Lean (Bank 2)",
    "P2099":"Post-Catalyst Fuel Trim Too Rich (Bank 2)",
    "P2100":"Throttle Actuator Control Motor Circuit Open",
    "P2101":"Throttle Actuator Control Motor Circuit Range/Performance",
    "P2104":"Throttle Actuator Control System Forced Idle",
    "P2105":"Throttle Actuator Control System Forced Engine Shutdown",
    "P2106":"Throttle Actuator Control System Forced Limited Power",
    "P2107":"Throttle Actuator Control Module Processor Error",
    "P2111":"Throttle Actuator Control System Stuck Open",
    "P2112":"Throttle Actuator Control System Stuck Closed",
    "P2122":"Throttle/Pedal Position Sensor D Circuit Low",
    "P2123":"Throttle/Pedal Position Sensor D Circuit High",
    "P2127":"Throttle/Pedal Position Sensor E Circuit Low",
    "P2128":"Throttle/Pedal Position Sensor E Circuit High",
    "P2135":"Throttle/Pedal Position Sensor A/B Voltage Correlation",
    "P2138":"Throttle/Pedal Position Sensor D/E Voltage Correlation",
    "P2176":"Throttle Actuator Control System Idle Position Not Learned",
    "P2177":"System Too Lean Off Idle (Bank 1)",
    "P2178":"System Too Rich Off Idle (Bank 1)",
    "P2187":"System Too Lean at Idle (Bank 1)",
    "P2188":"System Too Rich at Idle (Bank 1)",
    "P2195":"O2 Sensor Signal Biased/Stuck Lean (Bank 1 Sensor 1)",
    "P2196":"O2 Sensor Signal Biased/Stuck Rich (Bank 1 Sensor 1)",
    "P2270":"O2 Sensor Signal Stuck Lean (Bank 1 Sensor 2)",
    "P2271":"O2 Sensor Signal Stuck Rich (Bank 1 Sensor 2)",
    "P2279":"Intake Air System Leak",
    "P2290":"Injector Control Pressure Too Low",
    "P2503":"Charging System Voltage Low",
    "P2504":"Charging System Voltage High",
    "P2563":"Turbocharger Boost Control Position Sensor Range/Performance",
    "P2564":"Turbocharger Boost Control Position Sensor Low",
    "P2565":"Turbocharger Boost Control Position Sensor High",
    # ── B — Body (SAE generic) ────────────────────────────────────────────────
    "B0001":"Driver Frontal Stage 1 Deployment Control",
    "B0010":"Passenger Frontal Stage 1 Deployment Control",
    "B0051":"Frontal Crash Sensor 1 Assembly",
    "B0056":"Frontal Crash Sensor 2 Assembly",
    "B0071":"Left Front Side Crash Sensor Assembly",
    "B0076":"Right Front Side Crash Sensor Assembly",
    "B0081":"Seat Track Position Sensor Switch (Driver)",
    "B0085":"Seat Weight Sensor Circuit (Passenger)",
    "B1213":"Anti-Theft Number of Attempts Exceeded",
    "B1318":"Battery Voltage Low",
    "B1319":"Battery Voltage High",
    "B1321":"Fuel Pump Relay Circuit",
    "B1352":"Ignition Key-In Circuit",
    "B1470":"Lamp Turn Signal LH Circuit",
    "B1471":"Lamp Turn Signal RH Circuit",
    "B1480":"Heated Backlight Relay Circuit",
    "B1485":"Heated Seat Switch Circuit",
    # ── C — Chassis (SAE generic) ─────────────────────────────────────────────
    "C0031":"Right Front Wheel Speed Sensor Circuit",
    "C0035":"Left Front Wheel Speed Sensor Circuit Malfunction",
    "C0036":"Left Front Wheel Speed Sensor Circuit Range/Performance",
    "C0050":"Right Rear Wheel Speed Sensor Circuit",
    "C0055":"Left Rear Wheel Speed Sensor Circuit",
    "C0110":"ABS Pump Motor Circuit Malfunction",
    "C0121":"ABS Valve Relay Circuit Malfunction",
    "C0128":"Low Brake Fluid Level Switch Circuit",
    "C0161":"ABS/TCS Brake Switch Circuit Malfunction",
    "C0175":"EBCM System Voltage High",
    "C0176":"EBCM System Voltage Low",
    "C0186":"Lateral Acceleration Sensor Circuit",
    "C0196":"Yaw Rate Sensor Circuit",
    "C0265":"EBCM Relay Circuit",
    "C0271":"EBCM Malfunction",
    "C0281":"Brake Switch Circuit Malfunction",
    "C0283":"Traction Control Switch Circuit",
    "C0291":"Lost Communication with PCM (ABS Module)",
    "C0450":"Steering Position Sensor Circuit",
    "C0550":"Electronic Control Unit Performance",
    "C0558":"Calibration Data Not Programmed",
    "C0561":"System Disabled — Low Voltage",
    "C0660":"Rear Height Sensor Circuit",
    "C0665":"Front Height Sensor Circuit",
    "C0680":"Compressor Output Circuit",
    # ── U — Network (SAE generic) ─────────────────────────────────────────────
    "U0001":"High Speed CAN Communication Bus",
    "U0002":"High Speed CAN Communication Bus Performance",
    "U0003":"High Speed CAN Communication Bus Open",
    "U0004":"High Speed CAN Communication Bus Short to Battery",
    "U0005":"High Speed CAN Communication Bus Short to Ground",
    "U0006":"Medium Speed CAN Communication Bus",
    "U0020":"Low Speed CAN Communication Bus",
    "U0073":"Control Module Communication Bus Off",
    "U0100":"Lost Communication With ECM/PCM A",
    "U0101":"Lost Communication With TCM",
    "U0102":"Lost Communication With Transfer Case Control Module",
    "U0121":"Lost Communication With ABS Control Module",
    "U0122":"Lost Communication With Vehicle Dynamics Control Module",
    "U0123":"Lost Communication With Yaw Rate Sensor Module",
    "U0126":"Lost Communication With Steering Angle Sensor Module",
    "U0127":"Lost Communication With Tire Pressure Monitor Module",
    "U0129":"Lost Communication With Brake System Control Module",
    "U0131":"Lost Communication With Power Steering Control Module",
    "U0140":"Lost Communication With Body Control Module",
    "U0146":"Lost Communication With Gateway A",
    "U0151":"Lost Communication With Restraints Control Module",
    "U0155":"Lost Communication With Instrument Panel Cluster",
    "U0159":"Lost Communication With Parking Assist Control Module",
    "U0161":"Lost Communication With Radio",
    "U0164":"Lost Communication With HVAC Control Module",
    "U0167":"Lost Communication With Vehicle Theft Deterrent Module",
    "U0184":"Lost Communication With RF Receiver Module",
    "U0197":"Lost Communication With Telephone Control Module",
    "U0198":"Lost Communication With Telematics Control Module",
    "U0212":"Lost Communication With Steering Column Control Module",
    "U0235":"Lost Communication With Cruise Control Distance Sensor",
    "U0300":"Internal Control Module Software Incompatibility",
    "U0301":"Software Incompatibility with ECM/PCM",
    "U0401":"Invalid Data Received From ECM/PCM",
    "U0402":"Invalid Data Received From TCM",
    "U0415":"Invalid Data Received From ABS Control Module",
    "U0422":"Invalid Data Received From Body Control Module",
    "U0423":"Invalid Data Received From Instrument Panel Cluster",
    "U0424":"Invalid Data Received From HVAC Control Module",
    "U0428":"Invalid Data Received From Steering Angle Sensor Module",
}

_CAT = ('P', 'C', 'B', 'U')

_GENERIC = {
    'P':{'0':"Generic Powertrain",'1':"Manufacturer-Specific Powertrain",
         '2':"SAE-Defined Powertrain",'3':"Joint SAE/Manufacturer Powertrain"},
    'C':{'0':"Generic Chassis",'1':"Manufacturer-Specific Chassis"},
    'B':{'0':"Generic Body",'1':"Manufacturer-Specific Body"},
    'U':{'0':"Generic Network",'1':"Manufacturer-Specific Network"},
}


def decode_dtc(byte1, byte2):
    """
    Decode two DTC bytes from an OBD2 Mode 03/07/0A response frame.
    Returns (code_str, description).
    """
    cat = (byte1 >> 6) & 0x03
    sub = (byte1 >> 4) & 0x03
    d2  = byte1 & 0x0F
    d3  = (byte2 >> 4) & 0x0F
    d4  = byte2 & 0x0F
    code = f"{_CAT[cat]}{sub}{d2:X}{d3:X}{d4:X}"
    if code in _CODES:
        return (code, _CODES[code])
    prefix = _GENERIC.get(_CAT[cat], {}).get(str(sub), "Unknown")
    return (code, f"{prefix} — Code {code} (see SAE J2012 / OEM docs)")


def lookup(code_str):
    """Look up a code string such as 'P0300'. Returns description or None."""
    return _CODES.get(code_str.upper())
