// ============================================================
// s_rear_neck_intake_shell24.scad
// Rear fuselage shell for Serenity Rev N 24" hull (s_rear.stl).
// Includes 4 radial neck scoop windows AND dual aft-facing ToF sensor mounts.
//
// Rev Q (2026-05-26): Updated to 2.0 mm foam-fill skin thickness.
//   - WALL_T reduced 4.0 → 3.5 mm (nominal 2.0 mm + 1.5 mm cutter overlap).
//   - 6x M3 boss posts at fore joint face (X = -105 mm, rear-to-cargo junction).
//   - No aft bosses: stern face is the engine bell / nozzle opening; the scoop
//     window cutters and nozzle assembly occupy that perimeter.
//   - Foam fill (2 lb/cf) carries distributed panel load; bosses handle point
//     loads at section joint fasteners.
//   Ref: structural_analysis.py log, Serenity UAV project, 2026-05-26.
//
// Rev R (2026-05-30): Shell hollowing moved from Blender to OpenSCAD.
//   - Root cause: blender_shells_v3_2mm.py boolean-diff produced STLs with
//     T-junction edges (3+ faces per edge) that blocked CGAL Nef Polyhedron
//     conversion in OpenSCAD ("given mesh is not closed" error).
//   - Fix: import the voxel-remeshed solid shell (s_rear_shell24_repaired.stl,
//     generated by repair_shells_for_scad.py, manifold) and subtract a
//     centroid-inset scaled copy inside OpenSCAD's own CGAL boolean engine.
//   - hollow_shell() module replaces the direct import of the broken hollow STL.
//   - Inner scale factors recomputed from solid STL bounding box (same dims as
//     blender outer-remesh output: 140.5 × 157.5 × 180.7 mm).
//   Ref: blender_shells_v3_2mm.py Rev R note; T-junction analysis 2026-05-30.
//
// Mounts (flush with outer mold line -- zero external protrusion):
//   S2A -- VL53L5CX aft ToF sensor, Array A (FC3 primary)
//   S2B -- VL53L5CX aft ToF sensor, Array B (FC2 primary)
//
// Flush-mount design:
//   Sensor apertures are cut flush through the hull wall.  PMMA window discs
//   sit in a 0.5 mm x 14 mm OD registration ring recess on the exterior face,
//   retained by UV adhesive and 4x M1.6 countersunk flathead screws (DIN 7991).
//   Carrier board pocket (14x14x3 mm) is on the interior face.
//
// Author: Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
// License: CC BY 4.0 -- creativecommons.org/licenses/by/4.0
//
// Scoop locations: 90 deg spacing (dorsal, port, ventral, starboard).
// Neck station: approx X = -129 mm in 24"-scaled STL space (sta 413 mm from nose).
// Hull ellipse at neck (24"): half-width approx 63 mm, half-height approx 50 mm.
// Each scoop window: 65 mm wide x 38 mm axial x 21 mm deep.
//
// Shell derivation:
//   18" centroid: (-131.8437, -81.8939, 51.4144)
//   24" centroid = x 1.33333:
//     CX = -175.79 mm
//     CY = -109.19 mm
//     CZ =   68.55 mm
//   Inner scale factors from blender_shells_v3_2mm.py (2.0 mm foam-fill wall):
//     INNER_SX = 0.971620  (dim = 140.9 mm, wall = 2.0 mm)
//     INNER_SY = 0.974683  (dim = 158.0 mm)
//     INNER_SZ = 0.977981  (dim = 181.7 mm)
//
// Coordinate system (24"-scaled STL world space):
//   X -- longitudinal, positive toward nose
//   Y -- vertical,    positive toward dorsal (up)   NOTE: Y is up, not Z
//   Z -- lateral,     positive toward port  (left)
//
// STL bounds (voxel-remesh repair): X=-246..-105, Y=-193..-35, Z=0..182.
// Fore joint face at X = -105 mm (rear → cargo junction).
// Aft/stern face at X = -246 mm (engine bell opening; no boss posts here).
//
// Aft sensor position notes:
//   Rear section estimated span: neck (X = -129) to stern (X approx -246 mm).
//   Sensors offset from engine bell centreline (approx Y = CY, Z = CZ) to give
//   unobstructed aft FoV and to serve as distinct Array A / Array B viewpoints.
//   VERIFY all positions by measuring rendered mesh in slicer.
//
// M3 boss reference:
//   M3 heat-set insert (Ruthex RX-M3x5.7 or equiv): 4.0 mm bore, 5.7 mm OD.
//   Boss OD 8.0 mm gives 2-wall annulus per CLAUDE.md fabrication requirements.
//   Ref: Ruthex data sheet, ISO 14589, CLAUDE.md fabrication standards.
//
// IMPORTANT: Verify scoop, sensor, and boss positions by measuring mesh
// cross-sections in a slicer after rendering before printing.
// ============================================================

SCALE_24  = 2.9294;   // 24" hull scale factor

// Rear shell centroid in 24"-scaled STL world coordinates
CX = -175.79;   // mm
CY = -109.19;   // mm -- dorsal/ventral axis (positive = up)
CZ =   68.55;   // mm -- lateral axis (positive = port)

// Hollow-shell parameters (Rev R: computed from solid STL bounding box)
// Bounding box of s_rear_shell24_repaired.stl after voxel-remesh (1.5 mm pitch):
//   X = -246.0 .. -105.6  → DX = 140.5 mm
//   Y = -192.9 ..  -35.4  → DY = 157.5 mm
//   Z =    0.0 ..  180.7  → DZ = 180.7 mm
// Inner scale factors: S = (D - 2 × WALL_MM) / D (centroid-inset approximation).
WALL_MM  = 2.0;         // [mm] nominal foam-fill skin thickness
DX = 140.5;             // [mm] solid STL bounding-box X dimension
DY = 157.5;             // [mm] solid STL bounding-box Y dimension
DZ = 180.7;             // [mm] solid STL bounding-box Z dimension
INNER_SX = (DX - 2 * WALL_MM) / DX;   // = 0.97153
INNER_SY = (DY - 2 * WALL_MM) / DY;   // = 0.97460
INNER_SZ = (DZ - 2 * WALL_MM) / DZ;   // = 0.97786

// Conservative wall thickness for cutter overlap (nominal 2.0 mm + 1.5 mm clearance)
WALL_T = 3.5;   // mm

// M3 heat-set insert boss dimensions
//   Boss OD 8.0 mm gives minimum 2-wall annulus outside insert per CLAUDE.md.
//   Ref: Ruthex RX-M3x5.7 data sheet; ISO 14589.
BOSS_OD     = 8.0;   // mm -- boss outer diameter
BOSS_H      = 6.0;   // mm -- boss height from interior face (>= insert length 5.7 mm)
BOSS_BORE_D = 4.1;   // mm -- M3 heat-set insert bore (4.0 mm nominal + 0.1 mm clearance)

// Neck scoop geometry
NECK_X   = -129;    // mm -- neck station; VERIFY after rendering
HULL_W2  =   63;    // mm -- port/stbd half-width at neck
HULL_H2  =   50;    // mm -- dorsal/ventral half-height at neck
SCOOP_W  =   65;    // mm -- circumferential width of each window
SCOOP_D  =   20;    // mm -- cutter depth (through hull + margin)
SCOOP_AX =   38;    // mm -- axial extent of window

// VL53L5CX flush mount dimensions
//   Exterior: 11 mm PMMA bore + 0.5 mm x 14 mm OD seat ring + 4x M1.6 c/s.
//   Interior: 14x14x3 mm carrier-board recess.
//   Ref: ST UM2884 DocID032910 Rev 1, 2021.
VAPER_D   = 11.0;   // mm -- PMMA window aperture bore
VRING_OD  = 14.0;   // mm -- seat ring OD (hull-flush registration)
VRING_DEP =  0.5;   // mm -- seat ring recess depth
VM16_D    =  1.7;   // mm -- M1.6 clearance hole
VM16_R    =  7.0;   // mm -- M1.6 bolt circle radius
VCSK16_OD =  3.5;   // mm -- M1.6 flathead c/s OD (DIN 7991, 90 deg)
VCSK16_D  =  1.0;   // mm -- M1.6 c/s depth
VRECESS_W = 14.0;   // mm -- carrier board pocket (square)
VRECESS_D =  3.0;   // mm -- carrier board pocket depth

$fn = 64;

// Orientation rotation vectors
//   STL axes: X=forward, Y=dorsal (+up), Z=port (+left).
//   Ry(-90 deg) maps +Z -> -X (aft): rotate([ 0, -90, 0 ])
AFT_ROT = [ 0, -90, 0 ];   // aperture faces -X (toward stern)

// Aft sensor positions -- near stern face, offset from engine bell centreline
//   Engine bell on hull axis at approx (CY, CZ); offset to give clear aft FoV.
//   VERIFY both positions by measuring stern face geometry in slicer.

// Array A aft sensor (FC3 primary) -- upper-port quadrant of stern face
S2A_POS = [ -222, CY + 25, CZ + 15 ];   // VERIFY

// Array B aft sensor (FC2 primary) -- lower-stbd quadrant, distinct bearing from S2A
S2B_POS = [ -215, CY - 20, CZ - 12 ];   // VERIFY

// M3 boss positions at fore joint face (X = -105 mm, rear → cargo junction).
//   Bosses extend from fore face into interior (-X direction = toward stern).
//   BOSS_FORE_ROT: rotate([0,-90,0]) aligns cylinder axis along -X (into interior).
//   Bounds at fore face: Y=-193..-35, Z=0..182; centroid CY=-109, CZ=69.
//   All positions VERIFY in slicer -- boss must sit fully inside hull skin.
BOSS_FORE_ROT = [ 0, -90, 0 ];

BOSS_FORE_1 = [ -105, CY + 72,  CZ      ];  // VERIFY: dorsal face, Y near -37
BOSS_FORE_2 = [ -105, CY + 36,  CZ + 68 ];  // VERIFY: dorsal-port, Z near 137
BOSS_FORE_3 = [ -105, CY - 36,  CZ + 68 ];  // VERIFY: ventral-port
BOSS_FORE_4 = [ -105, CY - 72,  CZ      ];  // VERIFY: ventral, Y near -181
BOSS_FORE_5 = [ -105, CY - 36,  CZ - 55 ];  // VERIFY: ventral-stbd, Z near 14
BOSS_FORE_6 = [ -105, CY + 36,  CZ - 55 ];  // VERIFY: dorsal-stbd

// ----------------------------------------------------------------------------
// Module: scoop_cutter
//   One rectangular neck scoop window before rotation.
//   Four instances at 0/90/180/270 deg around X give full radial coverage.
// ----------------------------------------------------------------------------
module scoop_cutter() {
    translate([NECK_X, HULL_H2 - 1, 0])
    rotate([90, 0, 0])
    linear_extrude(height = SCOOP_D + 1)
    square([SCOOP_W, SCOOP_AX], center = true);
}

// ----------------------------------------------------------------------------
// Module: vlsensor_cut
//   Flush-mount cutter for VL53L5CX.  Zero protrusion above hull surface.
//   Aperture bore + 0.5 mm PMMA seat ring + 4x M1.6 c/s holes + board pocket.
// ----------------------------------------------------------------------------
module vlsensor_cut(pos, rot) {
    translate(pos)
    rotate(rot)
    translate([0, 0, -(WALL_T + 1)]) {
        // PMMA aperture bore
        cylinder(h = WALL_T + 2, d = VAPER_D);

        // PMMA disc seat ring (0.5 mm recess at exterior face, 14 mm OD)
        translate([0, 0, WALL_T + 1 - VRING_DEP])
        cylinder(h = VRING_DEP + 1, d = VRING_OD);

        // 4x M1.6 countersunk through-holes at 45 deg diagonal
        for (a = [45, 135, 225, 315])
            rotate([0, 0, a])
            translate([VM16_R, 0, 0]) {
                cylinder(h = WALL_T + 2, d = VM16_D);
                translate([0, 0, WALL_T + 1 - VCSK16_D])
                cylinder(h = VCSK16_D + 1, d1 = VM16_D, d2 = VCSK16_OD);
            }

        // Carrier board recess on interior face
        translate([-VRECESS_W / 2, -VRECESS_W / 2, 0])
        cube([VRECESS_W, VRECESS_W, VRECESS_D + 1]);
    }
}

// ----------------------------------------------------------------------------
// Module: m3_boss
//   Interior M3 heat-set insert boss post.  Solid ring with bore for insert.
//   Added to union() as positive material inside hull skin.
//   Ref: Ruthex RX-M3x5.7; ISO 14589; CLAUDE.md min 2-wall annulus.
// ----------------------------------------------------------------------------
module m3_boss(pos, rot) {
    translate(pos)
    rotate(rot)
    difference() {
        // Boss post: 8 mm OD x 6 mm tall
        cylinder(h = BOSS_H, d = BOSS_OD);
        // Heat-set insert bore: 4.1 mm dia, through height + 0.1 mm clearance
        cylinder(h = BOSS_H + 0.1, d = BOSS_BORE_D);
    }
}

// ============================================================
// Module: hollow_shell (Rev R)
// ============================================================
// Produces the 2.0 mm foam-fill rear shell by boolean DIFFERENCE inside
// OpenSCAD's own CGAL boolean engine.
//
// Source STL: s_rear_shell24_repaired.stl — manifold solid shell generated by
//   repair_shells_for_scad.py (blender voxel-remesh, 1.5 mm pitch, 0 NM edges).
//   STL bounds: X=-246..-105.6, Y=-192.9..-35.4, Z=0..180.7 mm.
//
// Why not use the pre-hollowed s_rear_shell24_2mm_repaired.stl?
//   That file (from blender_shells_v3_2mm.py) carries T-junction edges (multi-
//   edges shared by 3+ faces) caused by float32 precision loss at the Blender
//   boolean cut boundary.  OpenSCAD's CGAL converter rejects it with
//   "The given mesh is not closed!" and produces no geometry.
//   By doing the subtraction inside OpenSCAD on two manifold solid imports, the
//   CGAL result is a properly closed hollow shell.
//   Ref: T-junction analysis 2026-05-30; blender_shells_v3_2mm.py Rev R note.
module hollow_shell() {
    difference() {
        import("../../thingverse-serenity/files-hollowed-18in/s_rear_shell24_repaired.stl");
        translate([CX, CY, CZ])
            scale([INNER_SX, INNER_SY, INNER_SZ])
            translate([-CX, -CY, -CZ])
                import("../../thingverse-serenity/files-hollowed-18in/s_rear_shell24_repaired.stl");
    }
}

// ============================================================
// Main geometry
// ============================================================
//
union() {
    difference() {
        // 2.0 mm foam-fill rear shell — hollowed in SCAD (see hollow_shell above)
        hollow_shell();

        // Four radial neck scoop windows
        //   Rotation axis = X; 0 deg = dorsal (+Y), 90 deg = port (+Z).
        for (rot = [0, 90, 180, 270])
            rotate([rot, 0, 0])
            scoop_cutter();

        // Aft sensor flush apertures
        vlsensor_cut(S2A_POS, AFT_ROT);
        vlsensor_cut(S2B_POS, AFT_ROT);
    }

    // 6x M3 boss posts at fore joint face (X = -105 mm, rear → cargo junction)
    //   Bosses extend into interior (-X) from fore joint face.
    //   No aft bosses: stern opening occupied by scoop windows and nozzle assembly.
    //   VERIFY all boss positions inside hull skin before printing.
    m3_boss(BOSS_FORE_1, BOSS_FORE_ROT);
    m3_boss(BOSS_FORE_2, BOSS_FORE_ROT);
    m3_boss(BOSS_FORE_3, BOSS_FORE_ROT);
    m3_boss(BOSS_FORE_4, BOSS_FORE_ROT);
    m3_boss(BOSS_FORE_5, BOSS_FORE_ROT);
    m3_boss(BOSS_FORE_6, BOSS_FORE_ROT);
}
