#!/usr/bin/env python3
"""Regenerate CLAUDE-MEMORY.md from Claude's autogenerated memory directory.

The root `AGENTS.md` / user standing instruction requires every AI agent to keep
a current mirror of its memory files in the repository root, so the memory an
agent is acting on is auditable by a human reading the repo alone.  That mirror
had been maintained by hand and drifted: it claimed 33 files when the directory
held 42.

This makes it build output, the same treatment `PROJECT_INDEX.md` gets --
regenerate it, never hand-edit it.

Source of truth is machine-local: Claude stores memory outside the repo, under
`~/.claude/projects/<slugified-project-path>/memory/`.  The slug replaces both
`/` and `.` with `-`.  A git worktree mirrors the MAIN working tree's slug, not
its own path, so the main tree is resolved via `git rev-parse --git-common-dir`.

Exits 0 with a notice (not an error) when the memory directory does not exist,
so a checkout on another machine or in CI does not fail this check.

Author  : Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
AI note : Authored by Claude (model: Claude Opus 5, Anthropic) under the
          author's direction, 2026-08-16, per AGENTS.md AI attribution.
License : CC BY-SA 4.0  <https://creativecommons.org/licenses/by-sa/4.0/>

Run: python3 tools/mirror_claude_memory.py [--check] [--memory-dir DIR]
"""

import argparse
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
MIRROR = os.path.join(REPO_ROOT, "CLAUDE-MEMORY.md")

HEADER = """# CLAUDE-MEMORY.md

Audit mirror of Claude's autogenerated project memory, per the repository-wide
instruction that every AI agent keep a current mirror of its memory files in the
repo root. Source of truth is Claude's memory directory; this file is a copy.

**Generated by `tools/mirror_claude_memory.py` — do not hand-edit.** Edit the
memory files themselves, then re-run the tool.

Mirrored: {n} memory files plus the index.

---

## Index (MEMORY.md)

---

{index}

---
"""


def main_worktree_root():
    """Absolute path of the MAIN working tree, even when run from a worktree."""
    try:
        common = subprocess.run(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return REPO_ROOT
    # <main>/.git  ->  <main>
    return os.path.dirname(common) if common.endswith(".git") else REPO_ROOT


def default_memory_dir():
    root = main_worktree_root()
    slug = root.replace("/", "-").replace(".", "-")
    return os.path.join(os.path.expanduser("~"), ".claude", "projects", slug,
                        "memory")


def build(memory_dir):
    """Return the mirror text, or None when there is nothing to mirror."""
    index_path = os.path.join(memory_dir, "MEMORY.md")
    if not os.path.isfile(index_path):
        return None
    names = sorted(f for f in os.listdir(memory_dir)
                   if f.endswith(".md") and f != "MEMORY.md")
    parts = [HEADER.format(n=len(names),
                           index=open(index_path).read().strip())]
    for name in names:
        body = open(os.path.join(memory_dir, name)).read().strip()
        parts.append(f"\n## `{name}`\n\n---\n\n{body}\n\n---\n")
    return "".join(parts)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--memory-dir", default=None,
                    help="override the memory directory location")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the mirror is stale; write nothing")
    args = ap.parse_args()

    memory_dir = args.memory_dir or default_memory_dir()
    if not os.path.isdir(memory_dir):
        print(f"no memory directory at {memory_dir} — nothing to mirror")
        return 0

    text = build(memory_dir)
    if text is None:
        print(f"no MEMORY.md index in {memory_dir} — nothing to mirror")
        return 0

    current = open(MIRROR).read() if os.path.exists(MIRROR) else None
    n = text.count("\n## `")
    if current == text:
        print(f"CLAUDE-MEMORY.md up to date ({n} memory files)")
        return 0
    if args.check:
        print(f"CLAUDE-MEMORY.md is STALE — re-run {os.path.basename(__file__)}")
        return 1
    with open(MIRROR, "w") as fh:
        fh.write(text)
    print(f"CLAUDE-MEMORY.md regenerated from {memory_dir} "
          f"({n} memory files plus the index)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
