#!/usr/bin/env python3
"""2D RANS comparison of S1223 thickening strategies, via OpenFOAM.  **WIP.**

STATUS 2026-08-16 -- DOES NOT PRODUCE RESULTS YET.  READ THIS FIRST.
--------------------------------------------------------------------
The OpenFOAM side is finished and correct: v1912 sources and runs, the case is
written (simpleFoam / k-omega SST, freestream far field, forceCoeffs, correct
SI scaling), and every variant is generated from the SCAD.  What does NOT work
is the mesh generator in `build_rings()`.  It gets an O-grid down to **2-4
inverted quads out of 48 000** and plateaus there; blockMesh rejects the mesh,
so no Cl/Cd has ever come out of this tool.

It is committed anyway so the next session inherits the dead ends instead of
rediscovering them.  Every item below was tried and measured -- do not retry
them expecting a different answer:

  1. One-block-per-quadrant O-grid, straight radial interpolation.
     -> 634 negative-volume cells, skewness 5866.  blockMesh interpolates
        LINEARLY between a block's inner and outer edges, and straight lines
        from a thin cambered section to a circle cross near the TE.
  2. Far ring mapped by ANGLE about quarter-chord (0.25, 0).
     -> rays fold: S1223's lower surface rises above the chord line aft of
        ~8 % chord, so that point is not inside the section.
  3. Far ring mapped by angle about the polygon CENTROID.
     -> still non-monotonic; the section is too thin and cambered.
  4. Initial blend + global Laplacian relaxation of interior rings.
     -> equalises radial spacing, so the boundary-layer clustering washes out
        and near-wall rings tangle ("inward-pointing faces"; layer grading
        comes out < 1, i.e. contracting outward).
  5. Uniform arclength REDISTRIBUTION of each marched ring.
     -> shears the radial correspondence; made it worse, 7630 inverted.
  6. Parameter search over normal smoothing (12-160), TE bluntness
     (0.0015-0.008 t/c), blend power (0.5-2.0), first-cell height
     (9e-6 - 1e-3 m), circumferential count (160-400), and a local untangling
     pass over the inverted quads only.
     -> best combination reaches 2-4 inverted; it never reaches 0.

  What DID help, and is kept in the code: ray-projecting the MARCHED ring onto
  the far circle rather than using a fixed arclength->angle map (7126 -> 41
  inverted), 100 circumferential blocks so a block's straight corner edge does
  not sag deeper than the first layer is thick, and relaxing the near-wall
  spacing to wall-function scale.

  The remaining 2-4 are structural, not a tuning problem.  Fixing this needs a
  different generator -- elliptic grid generation with orthogonality control,
  or a C-grid topology (which suits the cusped TE far better than an O-grid) --
  or a different mesher.  snappyHexMesh is installed, but a 2D case needs a
  `refineMesh`-based workflow so refinement does not split the empty direction.

  NOTE the design decision this was built to settle does NOT depend on it: the
  camber comparison in `tools/wing_airfoil_variants.py` is decisive on its own
  (uniform scaling drives camber 8.12 % -> 11.75 % for exactly the same spar
  fit).  This tool would only quantify the penalty.

Purpose
-------
The Rev R1b spar move to 35 % root chord forces the wing TIP section to be
thickened (`tools/wing_airfoil_variants.py`).  Two strategies fit the spar
identically but treat the camber line very differently, so the choice is
aerodynamic, not geometric.  This driver settles it by running each candidate
section at the cruise design point and reporting Cl, Cd and Cl/Cd.

Design point (docs/flight_envelope.md SS1, airframe/openscad/wings/…):
    tip chord   0.093 m
    V           34.1 m/s  (66.3 kt V_min at 0 deg tilt -- the speed the wing
                           must actually fly, not the 40 kt reference)
    Re          ~214,000

Method (as designed; blocked on the mesh, see STATUS)
-----------------------------------------------------
Steady incompressible RANS (`simpleFoam`, k-omega SST) on an O-grid emitted as
nested `blockMesh` layers between rings pre-computed by `build_rings()`, so the
grid follows a marched/blended solution rather than a straight interpolation.
The far field is 20 chords out with `freestream` conditions, so one mesh serves
every angle of attack -- the angle is applied by rotating the freestream
vector, never by re-meshing, which keeps the comparison free of mesh-to-mesh
differences.

Every variant is run on a mesh generated by the same code at the same
resolution, so the DIFFERENCES between variants are meaningful even where the
absolute values carry the caveat below.

Caveat -- read before quoting absolute numbers
----------------------------------------------
k-omega SST is a fully-turbulent model.  At Re ~2e5 a real S1223 carries a
laminar separation bubble, so absolute Cd is over-predicted and Cl_max is not
trustworthy near stall.  This study is used ONLY to rank candidate sections
against each other at the same conditions and modest angles, which is what the
design decision needs.  Do not lift these Cd values into a range calculation
without wind-tunnel or transition-model backing.

Author  : Steve Griffing, PE(CSE), CISSP-ISSEP, CPP
AI note : Authored by Claude (model: Claude Opus 5, Anthropic) under the
          author's direction, 2026-08-16, per AGENTS.md AI attribution.
License : CC BY-SA 4.0  <https://creativecommons.org/licenses/by-sa/4.0/>

Run: /usr/bin/python3 tools/wing_cfd_openfoam.py --alpha 0 4 8
     (currently stops in build_rings() with an inverted-quad RuntimeError --
      that guard is deliberate: it fails loudly here rather than handing
      blockMesh a mesh it will reject with a tiny negative pyramid volume,
      which is far slower to diagnose.)
"""

import argparse
import math
import os
import re
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np  # noqa: E402

from wing_airfoil_variants import variant  # noqa: E402
from wing_spar_station_fit import (  # noqa: E402
    WING_SCAD, scad_points, scad_scalar,
)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
FOAM_BASHRC = "/usr/share/openfoam/etc/bashrc"

# Design point -- see module docstring.
CHORD_M = 0.093
U_INF = 34.1
NU_AIR = 1.48e-5          # m^2/s at 15 C
RHO_AIR = 1.225           # kg/m^3
# 2D extrusion depth, in CHORDS.  The dict is written normalised (chord = 1)
# and scaled to metres by `scale CHORD_M`, so nu and U stay SI.
Z_THICK = 0.1

# Mesh resolution.  N_CIRC must be divisible by 4 (one quarter per block).
N_CIRC = 400
N_RAD = 120
R_FAR = 20.0              # far field, in chords
N_LAYER = 12              # radial block layers (N_RAD must divide by this)
# Circumferential blocks.  blockMesh validates a block from its 8 CORNER
# vertices, not from its polyLine edges, so a block spanning a large arc of a
# curved aerofoil is judged on a chord that cuts through the section and is
# rejected as inside-out.  Keeping each block short makes the corner quad a
# good stand-in for the real curve (verified 2026-08-16: 4 blocks fail, 20 pass).
# It must also be large enough that a block's straight corner edge does not
# sag further into the section than the first layer is thick: sagitta ~ arc^2/8R,
# so a 0.1-chord arc sags ~1.2e-3 while layer 0 is only ~1.5e-3 thick -- nearly
# degenerate.  100 blocks (4 points each) sag ~5e-5, comfortably clear.
N_CBLK = 100              # N_CIRC must divide by this
# Near-wall spacing.  9e-6 m targets y+ ~1 (wall-resolved) but gives a cell
# aspect ratio near 1000 against the ~0.1-chord circumferential spacing, which
# is what makes the marching ill-conditioned: it tangled 9-47 quads.  3e-4 m is
# wall-function scale (y+ ~30) and is the best-conditioned value found, at 2-3
# inverted.  Left at the wall-function value so the next attempt starts from
# the best known state; revisit once the generator itself is replaced.
FIRST_CELL = 3.0e-4       # m


def foam(cmd, cwd):
    """Run one OpenFOAM command in a case directory with the env sourced."""
    full = f". {FOAM_BASHRC} >/dev/null 2>&1 && {cmd}"
    return subprocess.run(["bash", "-c", full], cwd=cwd,
                          capture_output=True, text=True)


def head(path, txt, cls, obj):
    """Write an OpenFOAM dictionary with the standard header."""
    with open(path, "w") as fh:
        fh.write("FoamFile\n{\n    version 2.0;\n    format ascii;\n"
                 f"    class {cls};\n    object {obj};\n}}\n\n")
        fh.write(txt)


def resample_closed(x, yu, yl, n):
    """Airfoil as one closed loop of n points, TE -> upper -> LE -> lower -> TE.

    S1223's trailing edge is cusped-thin.  A perfectly sharp TE makes the
    O-grid's outward normals collapse there, so the TE is opened to a small
    blunt face.  The SAME blunt face is applied to every variant, so it cannot
    bias the comparison.
    """
    # t/c; ~0.74 mm at 93 mm chord.  Bluntness is what keeps the marched
    # normals from the two surfaces crossing just ahead of the cusp.
    te_half = 0.008
    yu = yu.copy()
    yl = yl.copy()
    # taper the blunting in over the last 15% chord so the surface stays smooth
    w = np.clip((x - 0.85) / 0.15, 0.0, 1.0)
    yu += w * te_half
    yl -= w * te_half
    up = np.stack([x, yu], axis=1)[::-1]     # TE -> LE
    lo = np.stack([x, yl], axis=1)[1:]       # LE -> TE
    # blockMesh hex ordering: with the block's local x along the loop and
    # local y radially outward, the loop must run COUNTER-CLOCKWISE for the
    # block to come out right-handed.  Emitting it clockwise makes blockMesh
    # reject every block as "inside-out" (verified 2026-08-16).
    loop = np.vstack([up, lo])
    # arc-length resample to n points so cells are evenly sized around the loop
    d = np.r_[0.0, np.cumsum(np.linalg.norm(np.diff(loop, axis=0), axis=1))]
    s = np.linspace(0.0, d[-1], n, endpoint=False)
    return np.stack([np.interp(s, d, loop[:, 0]),
                     np.interp(s, d, loop[:, 1])], axis=1)


def build_rings(loop, n_rad, normal_smooth=160, blend_pow=1.25,
                untangle_iters=400):
    """Return n_rad+1 nested rings from the aerofoil out to the far field.

    A one-block O-grid cannot be used here.  blockMesh interpolates linearly
    between a block's inner and outer edges, and straight lines from a thin,
    strongly cambered section to a circle CROSS near the trailing edge -- 634
    negative-volume cells and skewness 5866 when tried (2026-08-16).

    Plain Laplacian relaxation of an initial blend does not fix it either: it
    equalises radial spacing, so the boundary-layer clustering washes out and
    the near-wall rings tangle (blockMesh then reports "inward-pointing
    faces", and the layer grading comes out below 1).

    What works is HYPERBOLIC MARCHING with a blend to the far field:

      * near the wall each ring is the previous ring pushed out along its own
        smoothed outward normal, which keeps rings parallel to the surface and
        preserves the geometric radial spacing exactly;
      * as the rings move out they are progressively blended toward the
        far-field circle, so by the outer boundary the grid is clean and
        circular regardless of what the aerofoil did.

    Normals are smoothed circumferentially before marching; that is what stops
    concave stretches (the S1223 lower surface) from folding the offset.
    """
    n = len(loop)
    cen = loop.mean(axis=0)
    # geometric radial distribution, first cell FIRST_CELL (in chords)
    t0 = FIRST_CELL / CHORD_M / R_FAR
    lo, hi = 1.0001, 1.5
    for _ in range(200):
        r = (lo + hi) / 2.0
        if t0 * (r ** n_rad - 1.0) / (r - 1.0) < 1.0:
            lo = r
        else:
            hi = r
    t = np.r_[0.0, np.cumsum(t0 * hi ** np.arange(n_rad))]
    t = np.clip(t / t[-1], 0.0, 1.0)

    def outward_normals(ring):
        """Smoothed outward unit normals of a CCW ring."""
        nxt = np.roll(ring, -1, axis=0)
        prv = np.roll(ring, 1, axis=0)
        tan = nxt - prv
        nrm = np.stack([tan[:, 1], -tan[:, 0]], axis=1)   # CCW -> outward
        for _ in range(normal_smooth):
            nrm = (np.roll(nrm, 1, axis=0) + 2.0 * nrm
                   + np.roll(nrm, -1, axis=0)) / 4.0
        ln = np.linalg.norm(nrm, axis=1, keepdims=True)
        return nrm / np.maximum(ln, 1e-15)

    rings = np.empty((n_rad + 1, n, 2))
    rings[0] = loop
    for j in range(n_rad):
        step = (t[j + 1] - t[j]) * R_FAR
        marched = rings[j] + outward_normals(rings[j]) * step
        # Project the MARCHED ring onto the circle along its own rays.  Using
        # a fixed arclength->angle map instead makes the target's point
        # correspondence disagree with the marched shape, which inverted ~7100
        # of 48000 quads; ray-projecting the marched ring drops that to ~40.
        d = marched - cen
        rad = np.linalg.norm(d, axis=1, keepdims=True)
        target = cen + (t[j + 1] * R_FAR) * (d / np.maximum(rad, 1e-15))
        w = t[j + 1] ** blend_pow
        rings[j + 1] = (1.0 - w) * marched + w * target

    def quad_areas(rr):
        a_, b_ = rr[:-1], rr[1:]
        a2_, b2_ = np.roll(a_, -1, axis=1), np.roll(b_, -1, axis=1)
        return 0.5 * (
            (a_[..., 0] * b_[..., 1] - b_[..., 0] * a_[..., 1])
            + (b_[..., 0] * b2_[..., 1] - b2_[..., 0] * b_[..., 1])
            + (b2_[..., 0] * a2_[..., 1] - a2_[..., 0] * b2_[..., 1])
            + (a2_[..., 0] * a_[..., 1] - a_[..., 0] * a2_[..., 1]))

    # Local untangling: relax only the points touching an inverted quad.  A
    # global smoothing pass would flatten the boundary-layer clustering, so the
    # repair is kept strictly local and stops as soon as the grid is clean.
    # This is what makes the generator work for every aerofoil variant instead
    # of only the one the parameters were tuned on.
    for _ in range(untangle_iters):
        bad = quad_areas(rings) <= 0.0
        if not bad.any():
            break
        touch = np.zeros(rings.shape[:2], dtype=bool)
        jj, kk = np.where(bad)
        for dj in (0, 1):
            for dk in (0, 1):
                touch[np.clip(jj + dj, 0, len(rings) - 1),
                      (kk + dk) % rings.shape[1]] = True
        touch[0] = False          # never move the aerofoil surface
        touch[-1] = False         # never move the far field
        lap = 0.25 * (np.roll(rings, 1, axis=1) + np.roll(rings, -1, axis=1)
                      + np.r_[rings[:1], rings[:-1]]
                      + np.r_[rings[1:], rings[-1:]])
        rings = np.where(touch[..., None], 0.5 * rings + 0.5 * lap, rings)

    # Self-check: every quad between consecutive rings must stay positively
    # oriented.  blockMesh would otherwise reject the block as "inside-out"
    # with a tiny negative volume, which is slow to diagnose from its message.
    a, b = rings[:-1], rings[1:]
    a2, b2 = np.roll(a, -1, axis=1), np.roll(b, -1, axis=1)
    area = 0.5 * ((a[..., 0] * b[..., 1] - b[..., 0] * a[..., 1])
                  + (b[..., 0] * b2[..., 1] - b2[..., 0] * b[..., 1])
                  + (b2[..., 0] * a2[..., 1] - a2[..., 0] * b2[..., 1])
                  + (a2[..., 0] * a[..., 1] - a[..., 0] * a2[..., 1]))
    if (area <= 0).any():
        raise RuntimeError(
            f"{int((area <= 0).sum())} of {area.size} grid quads are inverted; "
            "the O-grid would be rejected by blockMesh")
    return rings


def write_blockmesh(case, loop):
    """O-grid emitted as nested block layers between pre-smoothed rings.

    Each layer is thin enough that blockMesh's linear interpolation inside it
    cannot fold, while the shape of every layer boundary comes from
    build_rings() -- so the grid follows the smoothed elliptic solution rather
    than a straight blend from aerofoil to circle.
    """
    n = len(loop)
    q = n // N_CBLK
    cpl = N_RAD // N_LAYER
    rings = build_rings(loop, N_RAD)
    lev = [rings[L * cpl] for L in range(N_LAYER)] + [rings[N_RAD]]
    nlv = len(lev)

    def vid(level, k, z):
        return z * (nlv * n) + level * n + (k % n)

    verts = []
    for z, zc in enumerate((0.0, Z_THICK)):
        for level in range(nlv):
            for pt in lev[level]:
                verts.append((pt[0], pt[1], zc))
        del z
    vtxt = "\n".join(f"    ({v[0]:.8f} {v[1]:.8f} {v[2]:.8f})" for v in verts)

    # radial expansion inside each layer, taken from the ring spacing actually
    # generated, so the boundary-layer clustering survives the layer split
    def layer_ratio(L):
        a, b = L * cpl, (L + 1) * cpl
        first = np.linalg.norm(rings[a + 1] - rings[a], axis=1).mean()
        last = np.linalg.norm(rings[b] - rings[b - 1], axis=1).mean()
        return max(last / max(first, 1e-12), 1e-3)

    blocks, edges = [], []
    for L in range(N_LAYER):
        for b in range(N_CBLK):
            k0, k1 = b * q, (b + 1) * q
            blocks.append(
                f"    hex ({vid(L, k0, 0)} {vid(L + 1, k0, 0)} "
                f"{vid(L + 1, k1, 0)} {vid(L, k1, 0)} "
                f"{vid(L, k0, 1)} {vid(L + 1, k0, 1)} "
                f"{vid(L + 1, k1, 1)} {vid(L, k1, 1)}) "
                f"({cpl} {q} 1) simpleGrading ({layer_ratio(L):.6g} 1 1)")

    for level in range(nlv):
        for b in range(N_CBLK):
            k0, k1 = b * q, (b + 1) * q
            for z, zc in enumerate((0.0, Z_THICK)):
                pts = " ".join(
                    f"({lev[level][k % n][0]:.8f} {lev[level][k % n][1]:.8f} "
                    f"{zc:.6f})" for k in range(k0 + 1, k1))
                edges.append(f"    polyLine {vid(level, k0, z)} "
                             f"{vid(level, k1, z)} ({pts})")

    aero_faces, far_faces = [], []
    for b in range(N_CBLK):
        k0, k1 = b * q, (b + 1) * q
        aero_faces.append(f"            ({vid(0, k1, 0)} {vid(0, k0, 0)} "
                          f"{vid(0, k0, 1)} {vid(0, k1, 1)})")
        far_faces.append(f"            ({vid(nlv - 1, k0, 0)} "
                         f"{vid(nlv - 1, k1, 0)} {vid(nlv - 1, k1, 1)} "
                         f"{vid(nlv - 1, k0, 1)})")

    txt = (f"scale {CHORD_M};\n\nvertices\n(\n{vtxt}\n);\n\n"
           "blocks\n(\n" + "\n".join(blocks) + "\n);\n\n"
           "edges\n(\n" + "\n".join(edges) + "\n);\n\n"
           "defaultPatch\n{\n    name frontAndBack;\n    type empty;\n}\n\n"
           "boundary\n(\n"
           "    aerofoil { type wall; faces (\n"
           + "\n".join(aero_faces) + "\n    ); }\n"
           "    farField { type patch; faces (\n"
           + "\n".join(far_faces) + "\n    ); }\n"
           ");\n\nmergePatchPairs ();\n")
    head(os.path.join(case, "system", "blockMeshDict"), txt,
         "dictionary", "blockMeshDict")


def write_case(case, alpha_deg):
    """Write system/ and 0/ for one angle of attack."""
    for d in ("system", "constant", "0"):
        os.makedirs(os.path.join(case, d), exist_ok=True)

    a = math.radians(alpha_deg)
    ux, uy = U_INF * math.cos(a), U_INF * math.sin(a)
    lift = (-math.sin(a), math.cos(a), 0.0)
    drag = (math.cos(a), math.sin(a), 0.0)

    head(os.path.join(case, "system", "controlDict"), f"""
application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         3000;
deltaT          1;
writeControl    timeStep;
writeInterval   3000;
purgeWrite      1;
writeFormat     ascii;
writePrecision  8;
runTimeModifiable false;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   1;
        patches         (aerofoil);
        rho             rhoInf;
        rhoInf          {RHO_AIR};
        liftDir         ({lift[0]:.8f} {lift[1]:.8f} 0);
        dragDir         ({drag[0]:.8f} {drag[1]:.8f} 0);
        CofR            (0.25 0 0);
        pitchAxis       (0 0 1);
        magUInf         {U_INF};
        lRef            {CHORD_M};
        Aref            {CHORD_M * Z_THICK * CHORD_M:.10f};
    }}
    residuals
    {{
        type            solverInfo;
        libs            ("libutilityFunctionObjects.so");
        fields          (U p);
        writeControl    timeStep;
    }}
}}
""", "dictionary", "controlDict")

    head(os.path.join(case, "system", "fvSchemes"), """
ddtSchemes      { default steadyState; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes   { default corrected; }
wallDist        { method meshWave; }
""", "dictionary", "fvSchemes")

    head(os.path.join(case, "system", "fvSolution"), """
solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-8;
        relTol          0.01;
        smoother        GaussSeidel;
    }
    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-9;
        relTol          0.01;
    }
}
SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl { p 1e-6; U 1e-7; "(k|omega)" 1e-7; }
}
relaxationFactors { equations { ".*" 0.9; } }
""", "dictionary", "fvSolution")

    head(os.path.join(case, "constant", "transportProperties"),
         f"transportModel Newtonian;\nnu {NU_AIR};\n",
         "dictionary", "transportProperties")
    head(os.path.join(case, "constant", "turbulenceProperties"),
         "simulationType RAS;\nRAS { RASModel kOmegaSST; turbulence on; "
         "printCoeffs on; }\n", "dictionary", "turbulenceProperties")

    # Freestream turbulence: 0.1% intensity, eddy viscosity ratio 10.
    ti, ratio = 0.001, 10.0
    k = 1.5 * (U_INF * ti) ** 2
    omega = k / (ratio * NU_AIR)

    head(os.path.join(case, "0", "U"), f"""
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform ({ux:.6f} {uy:.6f} 0);
boundaryField
{{
    aerofoil      {{ type noSlip; }}
    farField      {{ type freestreamVelocity;
                    freestreamValue uniform ({ux:.6f} {uy:.6f} 0); }}
    frontAndBack  {{ type empty; }}
}}
""", "volVectorField", "U")

    head(os.path.join(case, "0", "p"), """
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    aerofoil      { type zeroGradient; }
    farField      { type freestreamPressure; freestreamValue uniform 0; }
    frontAndBack  { type empty; }
}
""", "volScalarField", "p")

    head(os.path.join(case, "0", "k"), f"""
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform {k:.8g};
boundaryField
{{
    aerofoil      {{ type kLowReWallFunction; value uniform {k:.8g}; }}
    farField      {{ type freestream; freestreamValue uniform {k:.8g}; }}
    frontAndBack  {{ type empty; }}
}}
""", "volScalarField", "k")

    head(os.path.join(case, "0", "omega"), f"""
dimensions      [0 0 -1 0 0 0 0];
internalField   uniform {omega:.8g};
boundaryField
{{
    aerofoil      {{ type omegaWallFunction; value uniform {omega:.8g}; }}
    farField      {{ type freestream; freestreamValue uniform {omega:.8g}; }}
    frontAndBack  {{ type empty; }}
}}
""", "volScalarField", "omega")

    head(os.path.join(case, "0", "nut"), """
dimensions      [0 2 -1 0 0 0 0];
internalField   uniform 0;
boundaryField
{
    aerofoil      { type nutLowReWallFunction; value uniform 0; }
    farField      { type calculated; value uniform 0; }
    frontAndBack  { type empty; }
}
""", "volScalarField", "nut")


def read_coeffs(case):
    """Last (Cl, Cd) from the forceCoeffs output."""
    base = os.path.join(case, "postProcessing", "forceCoeffs")
    if not os.path.isdir(base):
        return None
    times = sorted(os.listdir(base), key=lambda t: float(t))
    dat = os.path.join(base, times[-1], "coefficient.dat")
    if not os.path.exists(dat):
        dat = os.path.join(base, times[-1], "forceCoeffs.dat")
    if not os.path.exists(dat):
        return None
    cols, last = None, None
    for line in open(dat):
        if line.startswith("#"):
            if "Time" in line:
                cols = line.lstrip("#").split()
            continue
        if line.strip():
            last = line.split()
    if last is None or cols is None:
        return None
    try:
        return (float(last[cols.index("Cl")]), float(last[cols.index("Cd")]))
    except (ValueError, IndexError):
        return None


def run_variant(name, x, yu, yl, alphas, workdir, keep):
    """Mesh once, then solve at each angle.  Returns {alpha: (Cl, Cd)}."""
    loop = resample_closed(x, yu, yl, N_CIRC)
    results = {}
    for alpha in alphas:
        case = os.path.join(workdir, f"{name}_a{alpha:g}")
        if os.path.exists(case):
            shutil.rmtree(case)
        os.makedirs(case)
        write_case(case, alpha)
        write_blockmesh(case, loop)

        r = foam("blockMesh", case)
        if r.returncode != 0:
            print(f"    a={alpha:>4g}  blockMesh FAILED")
            tail = (r.stdout + r.stderr).strip().splitlines()[-4:]
            for t in tail:
                print(f"        {t}")
            return results
        chk = foam("checkMesh -constant", case)
        nonortho = re.search(r"Max non-orthogonality = ([\d.]+)", chk.stdout)
        r = foam("simpleFoam", case)
        got = read_coeffs(case)
        conv = "converged" if "SIMPLE solution converged" in r.stdout else "endTime"
        if got is None:
            print(f"    a={alpha:>4g}  no coefficients ({conv})")
        else:
            cl, cd = got
            results[alpha] = got
            print(f"    a={alpha:>4g}  Cl {cl:+7.4f}  Cd {cd:7.5f}  "
                  f"L/D {cl / cd:8.2f}  [{conv}"
                  + (f", nonOrtho {nonortho.group(1)}" if nonortho else "")
                  + "]")
        if not keep:
            shutil.rmtree(case, ignore_errors=True)
    return results


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--alpha", type=float, nargs="+", default=[0.0, 4.0, 8.0],
                    help="angles of attack, degrees")
    ap.add_argument("--station", type=float, default=45.15)
    ap.add_argument("--workdir", default=os.path.join(
        os.environ.get("TMPDIR", "/tmp"), "serenity_wing_cfd"))
    ap.add_argument("--keep", action="store_true",
                    help="keep the OpenFOAM case directories")
    args = ap.parse_args()

    if not os.path.exists(FOAM_BASHRC):
        sys.exit(f"OpenFOAM env not found at {FOAM_BASHRC}")

    src = open(WING_SCAD).read()
    upper = scad_points(src, "S1223_UPPER")
    lower = scad_points(src, "S1223_LOWER")
    c_tip = scad_scalar(src, "WING_CHORD_TIP")
    ts_tip = scad_scalar(src, "THICKNESS_SCALE_TIP")
    bore = scad_scalar(src, "SPAR_BORE_OD")

    from wing_airfoil_variants import camber_thickness
    from wing_spar_station_fit import MIN_WALL_MM
    _cam, thk0 = camber_thickness(upper, lower, args.station / c_tip)
    need = (bore + 2.0 * MIN_WALL_MM) / (thk0 * c_tip)

    print("S1223 tip-section CFD -- OpenFOAM v1912, simpleFoam / k-omega SST")
    print(f"  chord {CHORD_M} m, U {U_INF} m/s, Re "
          f"{U_INF * CHORD_M / NU_AIR:,.0f}")
    print(f"  mesh {N_CIRC} x {N_RAD} O-grid, far field {R_FAR:g} chords")
    print(f"  spar station {args.station:.2f} mm -> thickness scale "
          f"{need:.3f} needed\n")

    cases = [
        ("baseline", 1.0, "uniform"),
        ("asbuilt_uniform_1p25", ts_tip, "uniform"),
        ("uniform_needed", need, "uniform"),
        ("thickness_only", need, "thickness"),
    ]
    os.makedirs(args.workdir, exist_ok=True)
    table = {}
    for name, sc, mode in cases:
        print(f"  {name}  (scale {sc:.3f}, {mode})")
        x, yu, yl = variant(upper, lower, sc, mode)
        table[name] = run_variant(name, x, yu, yl, args.alpha,
                                  args.workdir, args.keep)

    print("\n  summary (Cl / L-over-D)")
    hdr = "  " + "variant".ljust(24) + "".join(
        f"a={a:g}".rjust(18) for a in args.alpha)
    print(hdr)
    for name, _sc, _m in cases:
        row = "  " + name.ljust(24)
        for a in args.alpha:
            got = table[name].get(a)
            row += (f"{got[0]:+.3f}/{got[0] / got[1]:.1f}".rjust(18)
                    if got else "--".rjust(18))
        print(row)


if __name__ == "__main__":
    main()
