// =============================================================================
// nacelle_nozzle_servo_64mm.scad — 64 mm nozzle servo drive in the dorsal spine
// =============================================================================
// WBS NAC-64-SERVO-01.  Owner decisions 2026-10-04: servo inside the canonical
// dorsal spine; the spine blended aft over the nozzle housing (QMx side view,
// REF-CAD-003); a bellcrank so the drive stays inside canon; the spine
// extension FIXED on the pod so the nozzle is a field-swap module (forward-open
// notch, 2 captive screws, no linkage part handled).
//
// All kinematics come from nozzle_servo_linkage_64_params.scad, GENERATED by
// tools/nozzle_servo_linkage_64.py (never hand-edit): servo BMS-101DMG
// [REF-ACT-004] flat in the spine, shaft tangential, 4 mm horn, +/-45 deg ->
// link -> bellcrank on a radial Ø2 pin (input 4.5 / output 14 mm) -> 18.7 mm
// rod -> the ring's open ball cup at r 39.  Starboard frame; port = mirror x.
//
// Used by nacelle_pod_64mm_tandem.scad:
//   nsv_pod_cuts()  — Zone B: servo pocket, horn/link/bellcrank/rod sweeps,
//                     cover opening + ledge, pin bore, cover-screw inserts
//   nsv_pod_adds()  — Zone C: spine extension over the housing (with the two
//                     captive nozzle-screw counterbores)
// Own parts (NSV_PART): "cover" (print), "bellcrank" (print), "asm" (preview).
//
// COTS: M2 threaded rod + 2 x M2 ball links (rod and link), Ø2 x 12 steel
// dowel (pivot), 3 x M2 captive screws + inserts (cover), 2 x M3 captive
// screws (nozzle).  FORCE MARGIN IS THIN: ear holding 2.6 N vs spring 2.0 N
// (tool output) — if the U8 flap load exceeds ~0.6 N, fit a higher-torque
// servo in the same pocket (WBS NAC-64-SERVO-01).
//
// Author: Claude (Claude Opus 5.5, Anthropic) under the direction of
// Stab-Rabbit-coding, per AGENTS.md AI attribution.  License: CERN-OHL-W-2.0 — see LICENSES/CERN-OHL-W 2.0 (SPDX-License-Identifier: CERN-OHL-W-2.0)
// =============================================================================

include <nacelle_64_scale.scad>   // P64_K / P64_A / P64_Z_NOZ (single source)
include <nozzle_servo_linkage_64_params.scad>
include <nacelle_dorsal_shroud_64_gen.scad>   // resized canonical dorsal shroud (generated)

NSV_PART  = "asm";
NSV_SIDE  = 1;              // +1 stbd, -1 port (mirror)
NSV_SHELL = "../../stls/nacelles/eng_right_shell24_50mm_repaired.stl";
NSV_CLR   = 0.6;            // [mm] pocket running clearance
NSV_COVER_T = 1.6;          // [mm] cover skin thickness (>= 1.5)
// 2026-10-05 x1.06 enlargement: the drive moves aft RIGIDLY with the nozzle
// ring (its lengths and angles are unchanged), so every drive station below is
// its as-designed value + NSV_DZ.  The linkage params file is regenerated by
// tools/nozzle_servo_linkage_64.py from the same P64_Z_NOZ.
NSV_Z_NOZ0  = 187.86;                  // nozzle ring Z the drive was designed at
NSV_DZ      = P64_Z_NOZ - NSV_Z_NOZ0;  // = 11.27 mm at x1.06
NSV_SPINE_Z = [124.0 + NSV_DZ, 187.0 + NSV_DZ];   // cover / opening axial span (servo body from ~Z 124)
NSV_SPINE_AZ = [250.0, 292.0];  // cover / opening azimuth span (stbd)
NSV_FLOOR_R = 36.4;         // bore wall (34.7) + 1.7

// Side: the pod passes its PYLON_SIDE as $nsv_side (a 'use'd file keeps its
// own NSV_SIDE default otherwise).
function nsv_side() = is_undef($nsv_side) ? NSV_SIDE : $nsv_side;
function nsv_er(az) = [cos(az), sin(az), 0];
function nsv_et(az) = [-sin(az), cos(az), 0];
function nsv_arm(phi, L) = NSL_C + L * (cos(phi) * NSL_U + sin(phi) * NSL_V);
function nsv_ball(psi) = [NSL_B_R * cos(psi), NSL_B_R * sin(psi), NSL_B_Z];
function nsv_horn(th) = NSL_SHAFT + NSL_HORN * (cos(th) * nsv_er(NSL_SHAFT_AZ) + sin(th) * [0, 0, 1]);
// Bellcrank angle phi interpolated linearly in psi (the solved map is near-
// linear over this 24 deg stroke; the tool owns the exact one).
function nsv_phi(f) = NSL_PHI_CLOSED + f * (NSL_PHI_OPEN - NSL_PHI_CLOSED);
function nsv_th(f)  = NSL_TH_CLOSED  + f * (NSL_TH_OPEN  - NSL_TH_CLOSED);
function nsv_psi(f) = NSL_PSI_CLOSED + f * (NSL_PSI_OPEN - NSL_PSI_CLOSED);

module nsv_seg(p, q, d) { hull() { translate(p) sphere(d = d, $fn = 16); translate(q) sphere(d = d, $fn = 16); } }

// Servo body: L along z, W radial (centred on the shaft radius), H tangential
// on the NSL_SERVO_SIDE side of the horn plane (-1: centred on the shroud
// crest).  Shaft 4.5 mm from the body's aft end.
module nsv_servo_body(clr = 0) {
    s = NSL_SERVO;
    rotate([0, 0, NSL_SHAFT_AZ])
        translate([norm([NSL_SHAFT[0], NSL_SHAFT[1]]) - s[1] / 2 - clr,
                   NSL_SERVO_SIDE > 0 ? 1.5 - clr : -(1.5 + s[2]) - clr,
                   NSL_SHAFT[2] - (s[0] - 4.5) - clr])
            cube([s[1] + 2 * clr, s[2] + 2 * clr, s[0] + 2 * clr]);
}

// Everything that moves, swept over the stroke (for cuts) or at fraction f.
module nsv_moving(f, d_add = 0) {
    th = nsv_th(f); ph = nsv_phi(f); ps = nsv_psi(f);
    nsv_seg(NSL_SHAFT, nsv_horn(th), 3.0 + d_add);                        // horn
    nsv_seg(nsv_horn(th), nsv_arm(ph + NSL_ARM_OFFSET, NSL_L_IN), 3.2 + d_add); // link + ball links
    nsv_seg(nsv_arm(ph + NSL_ARM_OFFSET, NSL_L_IN), NSL_C, 4.0 + d_add);  // bellcrank in-arm
    nsv_seg(NSL_C, nsv_arm(ph, NSL_L_OUT), 4.0 + d_add);                  // bellcrank out-arm
    nsv_seg(nsv_arm(ph, NSL_L_OUT), nsv_ball(ps), 3.2 + d_add);           // rod + ball link
}
// Aft part of the mechanism only (bellcrank output arm + rod): the part that
// leaves the canonical spine; it alone shapes the fairing.
module nsv_moving_aft(f, d_add = 0) {
    ph = nsv_phi(f); ps = nsv_psi(f);
    nsv_seg(NSL_C, nsv_arm(ph, NSL_L_OUT), 4.0 + d_add);
    nsv_seg(nsv_arm(ph, NSL_L_OUT), nsv_ball(ps), 3.2 + d_add);
}
module nsv_sweep_aft(d_add) { for (k = [0 : 6]) hull() { nsv_moving_aft(k / 7, d_add); nsv_moving_aft((k + 1) / 7, d_add); } }
module nsv_sweep(d_add) { for (k = [0 : 6]) hull() { nsv_moving(k / 7, d_add); nsv_moving((k + 1) / 7, d_add); } }

module nsv_shell() { scale([P64_K, P64_K, P64_A]) translate([-155.02, 190.79, 0]) import(NSV_SHELL, convexity = 6); }
// Outer mould line over the drive: the canonical shell plus the RESIZED
// canonical dorsal shroud (owner rule 2026-10-04: height grows only as a
// uniform resize of the canonical shroud; tools/dorsal_shroud_resize_64.py).
module nsv_outer() { union() { nsv_shell(); dorsal_shroud_64(); } }
module nsv_wedge(a0, a1, z0, z1, r1 = 80) {
    translate([0, 0, z0]) linear_extrude(z1 - z0)
        polygon(concat([[0, 0]], [for (a = [a0 : 2 : a1]) r1 * [cos(a), sin(a)]], [r1 * [cos(a1), sin(a1)]]));
}
// Material that stays: everything deeper than (skin - cover) — approximated by
// the shell shrunk radially by the cover thickness about the duct axis.
module offset_skin_inner() {
    k = 1 - NSV_COVER_T / 48.0;
    scale([k, k, 1]) nsv_outer();
}
NSV_COVER_SCREWS = [[252.5, 127.0 + NSV_DZ], [289.5, 127.0 + NSV_DZ], [287.0, 184.0 + NSV_DZ]];   // [az, z] on solid ledge
module nsv_cover_screw_axes(d, h0, h1) {
    for (s = NSV_COVER_SCREWS) rotate([0, 0, s[0]]) translate([h0, 0, s[1]])
        rotate([0, 90, 0]) cylinder(d = d, h = h1 - h0, $fn = 16);
}

module nsv_pod_cuts() {
    mirror([nsv_side() < 0 ? 1 : 0, 0, 0]) {
        nsv_servo_body(NSV_CLR);
        nsv_sweep(2 * NSV_CLR);
        // service wells: open the servo pocket and the bellcrank area up to
        // the cover so both lift out through the cover opening alone
        hull() { nsv_servo_body(NSV_CLR);
                 rotate([0, 0, NSL_SHAFT_AZ]) translate([0, 0, 0]) scale([1, 1, 1])
                     translate([norm([NSL_SHAFT[0], NSL_SHAFT[1]]) + 8, 1.5 - NSV_CLR,
                                NSL_SHAFT[2] - (NSL_SERVO[0] - 4.5) - NSV_CLR])
                         cube([4, NSL_SERVO[2] + 2 * NSV_CLR, NSL_SERVO[0] + 2 * NSV_CLR]); }
        translate(NSL_C) rotate([0, 0, NSL_C_AZ]) rotate([0, 90, 0])
            translate([0, 0, -1.5]) cylinder(r = NSL_L_OUT + 2.5, h = 12, $fn = 48);
        // pivot pin bore (radial), Ø2 press into the floor boss
        translate(NSL_C) rotate([0, 0, NSL_C_AZ]) translate([-6.0, 0, 0])
            rotate([0, 90, 0]) cylinder(d = 2.0, h = 6.0, $fn = 16);
        // cover opening: skin outside (skin - cover) over the spine wedge
        intersection() { nsv_wedge(NSV_SPINE_AZ[0], NSV_SPINE_AZ[1], NSV_SPINE_Z[0], NSV_SPINE_Z[1]);
                         difference() { cylinder(r = 80, h = 400); offset_skin_inner(); } }
        // M2 x 3 heat-set inserts for the captive cover screws (into the ledge)
        nsv_cover_screw_axes(3.2, 38.6, 44.0);
    }
}

// Pod-side shroud: the resized canonical dorsal shroud, with the drive's
// running space, the housing envelope aft of the joint (the nozzle slides off
// under it), the sleeve bore, the nozzle's retention-boss clearances and the
// two captive M3 screw counterbores removed.
module nsv_pod_adds() {
    mirror([nsv_side() < 0 ? 1 : 0, 0, 0]) difference() {
        dorsal_shroud_64();
        translate([0, 0, P64_Z_NOZ]) cylinder(r = 42.9, h = 30, $fn = 180);
        translate([0, 0, 90]) cylinder(r = 34.8, h = 140, $fn = 180);
        nsv_sweep(2 * NSV_CLR);
        for (a = [302, 316]) rotate([0, 0, a])
            translate([42.0, -3.8, P64_Z_NOZ + 0.7]) cube([4.0, 7.6, 30]);
        for (a = [302, 316]) rotate([0, 0, a]) translate([42.0, 0, P64_Z_NOZ + 5.0])
            rotate([0, 90, 0]) { cylinder(d = 3.4, h = 12, $fn = 16);
                                 translate([0, 0, 3.6]) cylinder(d = 5.8, h = 10, $fn = 20); }
    }
}

// Access cover = the skin removed by the opening, minus the moving sweep,
// with captive-screw clearance holes.
module nsv_cover() {
    mirror([nsv_side() < 0 ? 1 : 0, 0, 0]) difference() {
        intersection() { nsv_outer();
                         nsv_wedge(NSV_SPINE_AZ[0] + 0.3, NSV_SPINE_AZ[1] - 0.3,
                                   NSV_SPINE_Z[0] + 0.3, NSV_SPINE_Z[1] - 0.3);
                         difference() { cylinder(r = 80, h = 400); offset_skin_inner(); } }
        nsv_sweep(2 * NSV_CLR);
        nsv_cover_screw_axes(2.4, 38.0, 60.0);
    }
}

// Rod clearance in the RING frame (used by the 64 mm nozzle's ring): the rod
// body (not its last 1.8 mm = the ball) at each stroke point, rotated into the
// ring's own frame (ring turns by psi - closed) and shifted to ring z.
module nsv_rod_clearance_ring_frame(d = 4.0, z_noz = P64_Z_NOZ) {
    for (k = [0 : 7]) let(f = k / 7, ps = nsv_psi(f), tip = nsv_arm(nsv_phi(f), NSL_L_OUT),
                          b = nsv_ball(ps), u = (b - tip) / norm(b - tip))
        rotate([0, 0, -(ps - NSL_PSI_CLOSED)]) translate([0, 0, -z_noz])
            nsv_seg(tip, b - 1.8 * u, d);
}

// Slide-off clearance in the ring frame: the rod body (minus the ball) at the
// OPEN pose, swept 14 mm forward relative to the ring (the nozzle sliding aft).
module nsv_rod_slide_clearance_ring_frame(d = 4.0, z_noz = P64_Z_NOZ, travel = 14) {
    let(tip = nsv_arm(nsv_phi(1), NSL_L_OUT), b = nsv_ball(nsv_psi(1)), u = (b - tip) / norm(b - tip))
        rotate([0, 0, -(nsv_psi(1) - NSL_PSI_CLOSED)]) translate([0, 0, -z_noz])
            hull() { nsv_seg(tip, b - 1.8 * u, d);
                     translate([0, 0, -travel]) nsv_seg(tip, b - 1.8 * u, d); }
}

// Printed bellcrank (CF-PETG), in its own frame: pivot at the origin, axis z.
module nsv_bellcrank() {
    difference() {
        hull() {
            cylinder(d = 5.0, h = 3.0, $fn = 32);
            rotate([0, 0, NSL_ARM_OFFSET]) translate([NSL_L_IN, 0, 0]) cylinder(d = 4.2, h = 3.0, $fn = 24);
            translate([NSL_L_OUT, 0, 0]) cylinder(d = 4.2, h = 3.0, $fn = 24);
        }
        translate([0, 0, -1]) cylinder(d = 2.1, h = 5, $fn = 16);                       // pin
        rotate([0, 0, NSL_ARM_OFFSET]) translate([NSL_L_IN, 0, -1]) cylinder(d = 1.8, h = 5, $fn = 12); // M2 tap
        translate([NSL_L_OUT, 0, -1]) cylinder(d = 1.8, h = 5, $fn = 12);               // M2 tap
    }
}

if (is_undef(NSV_NO_RENDER)) {
    if (NSV_PART == "cover") nsv_cover();
    else if (NSV_PART == "bellcrank") nsv_bellcrank();
    else mirror([nsv_side() < 0 ? 1 : 0, 0, 0]) {
        color("Red") nsv_servo_body();
        color("Black") nsv_moving(0.5);
    }
}
