// GENERATED by tools/nozzle_servo_linkage_64.py — do not hand-edit.
// 64 mm nozzle servo linkage, STARBOARD nacelle-local frame (port = mirror x).
NSL_B_R = 39.0; NSL_B_Z = 203.134;
NSL_PSI_CLOSED = 292.5; NSL_PSI_OPEN = 268.75;
NSL_C = [-2.9786, -42.5960, 190.2742];  NSL_C_AZ = 266.0; NSL_C_R = 42.7;
NSL_U = [-0.997564, 0.069756, 0.000000];  NSL_V = [-0.000000, 0.000000, -1.000000];
NSL_L_OUT = 14.0; NSL_L_IN = 4.485; NSL_L_ROD = 12.136; NSL_LINK = 35.533879516517175;
NSL_PHI_CLOSED = 234.000; NSL_PHI_OPEN = 312.200;
NSL_ARM_OFFSET = -93.100;   // input arm angle - output arm angle
NSL_SHAFT = [6.9286, -39.2938, 155.2742];  NSL_SHAFT_AZ = 280.000;
NSL_HORN = 4.0; NSL_SERVO_SWEEP = 90.10;
NSL_TH_CLOSED = -41.90;
NSL_TH_OPEN = 48.20;
NSL_SERVO_SIDE = -1;   // servo body on the -az side of its horn plane (centred on the crest)
NSL_SERVO = [20.0, 7.0, 16.6];   // KST X06 L x W x H
// [REF-ACT-005] VERIFY
