// GENERATED by tools/nozzle_servo_linkage_64.py — do not hand-edit.
// 64 mm nozzle servo linkage, STARBOARD nacelle-local frame (port = mirror x).
NSL_B_R = 39.0; NSL_B_Z = 191.860;
NSL_PSI_CLOSED = 292.5; NSL_PSI_OPEN = 268.75;
NSL_C = [-10.8704, -40.5689, 179.0000];  NSL_C_AZ = 255.0; NSL_C_R = 42.0;
NSL_U = [-0.965926, 0.258819, 0.000000];  NSL_V = [-0.000000, 0.000000, -1.000000];
NSL_L_OUT = 14.0; NSL_L_IN = 4.485; NSL_L_ROD = 18.686; NSL_LINK = 26.073865334942944;
NSL_PHI_CLOSED = 231.000; NSL_PHI_OPEN = 309.200;
NSL_ARM_OFFSET = -90.100;   // input arm angle - output arm angle
NSL_SHAFT = [-6.2229, -39.7154, 153.0000];  NSL_SHAFT_AZ = -98.905;
NSL_HORN = 4.0; NSL_SERVO_SWEEP = 90.10; NSL_TH_CLOSED = -45.85; NSL_TH_OPEN = 44.25;
NSL_SERVO = [18.5, 7.6, 15.7];   // BMS-101DMG L x W x H [REF-ACT-004] VERIFY
